# Dərs 17 — صفت‌ها (Sifətlər)
# Mənbə: کتاب دوم, səh. 207-216

LESSON = {
    "number": 17,
    "title_fa": "صفت‌ها",
    "title_az": "Sifətlər",
    "available": True,
    "vocabulary": [
        {"fa": "شیرین", "reading": "şirin", "az": "Şirin"},
        {"fa": "ترش", "reading": "torş", "az": "Turş"},
        {"fa": "بالا", "reading": "bala", "az": "Yuxarı"},
        {"fa": "پایین", "reading": "payin", "az": "Aşağı"},
        {"fa": "نو", "reading": "nou", "az": "Təzə"},
        {"fa": "کهنه", "reading": "kohne", "az": "Köhnə"},
        {"fa": "ارزان", "reading": "ərzan", "az": "Ucuz"},
        {"fa": "گران", "reading": "gəran", "az": "Bahalı"},
        {"fa": "خیس", "reading": "xis", "az": "Yaş, islanmış"},
        {"fa": "خشک", "reading": "xoşk", "az": "Quru"},
        {"fa": "نرم", "reading": "nərm", "az": "Yumşaq"},
        {"fa": "زبر", "reading": "zebr", "az": "Sərt, kobud"},
        {"fa": "باز", "reading": "baz", "az": "Açıq"},
        {"fa": "بسته", "reading": "bəste", "az": "Bağlı"},
        {"fa": "روشن", "reading": "rouşən", "az": "İşıqlı"},
        {"fa": "تاریک", "reading": "tarik", "az": "Qaranlıq"},
        {"fa": "قشنگ (زیبا)", "reading": "qəşəng (ziba)", "az": "Gözəl"},
        {"fa": "زشت", "reading": "zeşt", "az": "Çirkin"},
        {"fa": "خوش‌حال", "reading": "xoşhal", "az": "Şad, xoşbəxt"},
        {"fa": "ناراحت", "reading": "narahat", "az": "Narahat, kədərli"},
        {"fa": "ثروتمند", "reading": "servətmənd", "az": "Varlı"},
        {"fa": "فقیر", "reading": "fəqir", "az": "Kasıb"},
        {"fa": "قوی", "reading": "qəvi", "az": "Güclü"},
        {"fa": "ضعیف", "reading": "zəif", "az": "Zəif"},
        {"fa": "شجاع", "reading": "şoja", "az": "Cəsur"},
        {"fa": "ترسو", "reading": "tərsu", "az": "Qorxaq"},
        {"fa": "می‌ترسد", "reading": "mitərsəd", "az": "qorxur"},
        {"fa": "لبخند می‌زند", "reading": "ləbxənd mizənəd", "az": "gülümsəyir"},
        {"fa": "می‌خندد", "reading": "mixəndəd", "az": "gülür"},
        {"fa": "گریه می‌کند", "reading": "gerye mikonəd", "az": "ağlayır"},
        {"fa": "جالب", "reading": "caleb", "az": "Maraqlı"},
        {"fa": "همه‌جور آدم", "reading": "həmecur adəm", "az": "Hər cür insan"},
        {"fa": "بغل‌دستی", "reading": "bəğəldəsti", "az": "Yan qonşusu (oturuşda)"},
        {"fa": "فرد", "reading": "fərd", "az": "Fərd"},
        {"fa": "به نظر من", "reading": "be nəzəre mən", "az": "mənim fikrimcə"},
        {"fa": "ولی", "reading": "vəli", "az": "amma, lakin"},
        {"fa": "خلاصه", "reading": "xolase", "az": "Xülasə"},
        {"fa": "خنده‌رو", "reading": "xəndero", "az": "Şən, gülərüz"},
        {"fa": "هرچه", "reading": "hərçe", "az": "hər nə"},
        {"fa": "می‌ایستد", "reading": "mi-istəd", "az": "dayanır"},
        {"fa": "شوخی می‌کند", "reading": "şuxi mikonəd", "az": "zarafat edir"},
        {"fa": "بازی می‌کند", "reading": "bazi mikonəd", "az": "oynayır"},
    ],
    "grammar_notes": [
        {
            "title_az": "Deyək — deməyək: sifət isimlə uzlaşmır",
            "title_fa": "بگوییم – نگوییم",
            "conjugations": [
                {"pronoun_fa": "آن مرد یک خانه‌ی بزرگ دارد. ✓", "form_fa": "آن مرد یک بزرگ خانه دارد. ✗"},
                {"pronoun_fa": "ما امروز غذای خوش‌مزه خوردیم. ✓", "form_fa": "ما امروز خوش‌مزه غذا خوردیم. ✗"},
                {"pronoun_fa": "در زمستان، لباس ضخیم بپوشید. ✓", "form_fa": "در زمستان، ضخیم لباس بپوشید. ✗"},
            ],
            "examples": [
                {
                    "fa": "در فارسی، صفت همیشه بعد از اسم می‌آید و بین آن‌ها «کسره» (اضافه) وجود دارد؛ مثلاً «خانه‌ی بزرگ».",
                    "reading_az": "Dər farsi, sifət həmişe bəd əz esm miayəd va beyne anha kəsre (əzafe) vocud darəd; mesəlan xane-ye bozorg.",
                    "az": "Fars dilində sifət həmişə isimdən sonra gəlir və aralarında kəsrə (izafə) olur; məsələn «xane-ye bozorg» (böyük ev).",
                },
                {
                    "fa": "همسرم خیّاط است. او لباس‌های زیبا می‌دوزد.",
                    "reading_az": "Həmsərəm xəyyat əst. U ləbashaye ziba miduzəd.",
                    "az": "Həyat yoldaşım dərzidir. O, gözəl paltarlar tikir.",
                },
                {
                    "fa": "سارا با آبرنگ، یک رنگین‌کمان زیبا نقّاشی می‌کند.",
                    "reading_az": "Sara ba abrəng, yek rənginkəman ziba nəqqaşi mikonəd.",
                    "az": "Sara akvarellə gözəl bir göy qurşağı çəkir.",
                },
                {
                    "fa": "من برای دخترم یک کیف بنفش و یک جامدادی آبی می‌خرم.",
                    "reading_az": "Mən bəraye doxtərəm yek kif bənəfş va yek camdadi abi mixərəm.",
                    "az": "Mən qızım üçün bənövşəyi bir çanta və mavi bir qələmqabı alıram.",
                },
                {
                    "fa": "رفتگرها خیابان‌های کثیف را تمیز می‌کنند.",
                    "reading_az": "Roftegərha xiyabanhaye kəsif ra təmiz mikonənd.",
                    "az": "Zibilyığanlar çirkli küçələri təmizləyir.",
                },
            ],
            "drills": [
                {
                    "title_fa": "لطفاً تصحیح کنید",
                    "instruction_az": "Səhv cümlələri düzəldin (sifəti isimdən sonraya, izafətlə köçürün).",
                    "items": [
                        {
                            "prompt_fa": "خواهرم زیبا لباس‌ها می‌دوزد.",
                            "answer_fa": "خواهرم لباس‌های زیبا می‌دوزد.",
                            "reading_az": "Xahərəm ləbashaye ziba miduzəd.",
                            "az": "Bacım gözəl paltarlar tikir.",
                        },
                        {
                            "prompt_fa": "مادرم هر روز لذیذ غذا می‌پزد.",
                            "answer_fa": "مادرم هر روز غذای لذیذ می‌پزد.",
                            "reading_az": "Madərəm hər ruz qəzaye ləziz mipəzəd.",
                            "az": "Anam hər gün dadlı yemək bişirir.",
                        },
                        {
                            "prompt_fa": "رنگ‌کار با صورتی رنگ، اتاق را رنگ می‌زند.",
                            "answer_fa": "رنگ‌کار با رنگ صورتی، اتاق را رنگ می‌زند.",
                            "reading_az": "Rəngkar ba rənge sorəti, otaq ra rəng mizənəd.",
                            "az": "Rəngsaz çəhrayı rənglə otağı rəngləyir.",
                        },
                        {
                            "prompt_fa": "آن ثروتمند خانم، چهار بزرگ خانه دارد.",
                            "answer_fa": "آن خانم ثروتمند، چهار خانه‌ی بزرگ دارد.",
                            "reading_az": "An xanome servətmənd, çəhar xane-ye bozorg darəd.",
                            "az": "O varlı xanımın dörd böyük evi var.",
                        },
                    ],
                },
            ],
        },
        {
            "title_az": "Deyək — deməyək: cəm halında sifət «ها»sız gəlir",
            "title_fa": "بگوییم – نگوییم (صفتِ جمع)",
            "conjugations": [
                {"pronoun_fa": "من لباس تمیز می‌پوشم. ✓ / لباس‌های تمیز می‌پوشم. ✓", "form_fa": "لباس‌های تمیزها می‌پوشم. ✗"},
            ],
            "examples": [
                {
                    "fa": "من لباس‌های تمیز می‌پوشم. (لباس‌های تمیزها ✗)",
                    "reading_az": "Mən ləbashaye təmiz mipuşəm. (Ləbashaye təmizha ✗)",
                    "az": "Mən təmiz paltarlar geyinirəm — sifət «تمیز» cəm şəkilçisi almır, isim özü cəmlənir.",
                },
                {
                    "fa": "انسان‌های شجاع نمی‌ترسند.",
                    "reading_az": "Insanhaye şoja nemitərsənd.",
                    "az": "Cəsur insanlar qorxmurlar.",
                },
                {
                    "fa": "مادرم غذاهای خوش‌مزه می‌پزد.",
                    "reading_az": "Madərəm qəzahaye xoşməze mipəzəd.",
                    "az": "Anam dadlı yeməklər bişirir.",
                },
                {
                    "fa": "محسن پیراهن‌های سفید را بیشتر از پیراهن‌های رنگی دوست دارد.",
                    "reading_az": "Mohsen pirahənhaye sefid ra biştər əz pirahənhaye rəngi dust darəd.",
                    "az": "Möhsün ağ köynəkləri rəngli köynəklərdən daha çox sevir.",
                },
                {
                    "fa": "ریحانه لباس‌های خشک را از روی طناب برمی‌دارد و لباس‌های خیس را پهن می‌کند.",
                    "reading_az": "Reyhane ləbashaye xoşk ra əz ruye tənab bərmidarəd va ləbashaye xis ra pəhn mikonəd.",
                    "az": "Reyhanə quru paltarları ipdən götürür və yaş paltarları sərir.",
                },
                {
                    "fa": "پدرم گفت: دخترم! گل‌های قشنگ‌ها را انتخاب کن و بخر.",
                    "reading_az": "Pedərəm goft: doxtərəm! Golhaye qəşəngha ra entexab kon va bexər.",
                    "az": "Səhv forma: «گل‌های قشنگ‌ها» — düzgünü «گل‌های قشنگ»dır.",
                },
            ],
            "drills": [
                {
                    "title_fa": "لطفاً تصحیح کنید",
                    "instruction_az": "Səhv cümlələri düzəldin (cəm sifət «ها» şəkilçisi almır).",
                    "items": [
                        {
                            "prompt_fa": "پیراهن‌های چروک‌ها را اتو بزنید.",
                            "answer_fa": "پیراهن‌های چروک را اتو بزنید.",
                            "reading_az": "Pirahənhaye çoruk ra otu bezanid.",
                            "az": "Qırışlı köynəkləri ütüləyin.",
                        },
                        {
                            "prompt_fa": "ما لباس‌های کثیف‌ها را با لباس‌شویی شستیم.",
                            "answer_fa": "ما لباس‌های کثیف را با لباس‌شویی شستیم.",
                            "reading_az": "Ma ləbashaye kəsif ra ba ləbasşuyi şostim.",
                            "az": "Biz çirkli paltarları paltaryuyanla yudduq.",
                        },
                        {
                            "prompt_fa": "انسان‌های قوی‌ها به انسان‌های ضعیف‌ها کمک می‌کنند.",
                            "answer_fa": "انسان‌های قوی به انسان‌های ضعیف کمک می‌کنند.",
                            "reading_az": "Insanhaye qəvi be insanhaye zəif komək mikonənd.",
                            "az": "Güclü insanlar zəif insanlara kömək edir.",
                        },
                        {
                            "prompt_fa": "پدرم گفت: دخترم! گل‌های قشنگ‌ها را انتخاب کن و بخر.",
                            "answer_fa": "پدرم گفت: دخترم! گل‌های قشنگ را انتخاب کن و بخر.",
                            "reading_az": "Pedərəm goft: doxtərəm! Golhaye qəşəng ra entexab kon va bexər.",
                            "az": "Atam dedi: Qızım! Gözəl gülləri seç və al.",
                        },
                    ],
                },
            ],
        },
        {
            "title_az": "Müqayisə (تفضیلی) və üstünlük (عالی) dərəcə şəkilçiləri: تر / ترین",
            "title_fa": "صفتِ برتر (تفضیلی) و برترین (عالی)",
            "conjugations": [
                {"pronoun_fa": "صفت ساده", "form_fa": "این پسر، چاق است."},
                {"pronoun_fa": "صفت برتر (تفضیلی) + از", "form_fa": "این پسر، چاق‌تر از آن پسر است."},
                {"pronoun_fa": "صفت برترین (عالی) + ترین", "form_fa": "این پسر، چاق‌ترین پسر است."},
            ],
            "examples": [
                {
                    "fa": "این صندلی، زیباتر از آن صندلی است. (زیباترین ✗ در این جمله چون مقایسه‌ی دوتایی است)",
                    "reading_az": "İn səndəli, zibatər əz an səndəli əst. (Zibatərin ✗ dər in comle çon moqayeseye dotayi əst.)",
                    "az": "Bu stul o stuldan gözəldir — iki şeyin müqayisəsində «-tər», üçdən çoxda «-tərin».",
                },
                {
                    "fa": "خانه‌ی حسن، بزرگ‌تر از خانه‌ی احمد است.",
                    "reading_az": "Xane-ye Həsən, bozorgtər əz xane-ye Əhməd əst.",
                    "az": "Həsənin evi Əhmədin evindən böyükdür.",
                },
                {
                    "fa": "کفش شما نوتر از کفش من است.",
                    "reading_az": "Kəfşe şoma noutər əz kəfşe mən əst.",
                    "az": "Sizin ayaqqabınız mənim ayaqqabımdan təzədir.",
                },
                {
                    "fa": "خط‌کش لیلا ارزان‌تر از خط‌کش نرگس است.",
                    "reading_az": "Xətkeşe Leyla ərzantər əz xətkeşe Nərges əst.",
                    "az": "Leylanın xətkeşi Nərgizin xətkeşindən ucuzdur.",
                },
                {
                    "fa": "این انگور، خوش‌مزه‌ترین انگور است.",
                    "reading_az": "İn əngur, xoşmezetərin əngur əst.",
                    "az": "Bu üzüm ən dadlı üzümdür.",
                },
                {
                    "fa": "محمّد قوی‌تر از سعید و یاسر است.",
                    "reading_az": "Mohəmməd qəvitər əz Səid o Yasər əst.",
                    "az": "Məhəmməd Səid və Yasirdən güclüdür.",
                },
            ],
            "drills": [
                {
                    "title_fa": "با گزینه‌ی درست کامل کنید",
                    "instruction_az": "Düzgün variantı seçərək cümləni tamamlayın (sadə, təfzili, yaxud üstünlük dərəcəsi).",
                    "items": [
                        {
                            "prompt_fa": "این کیف، ______ کیف است. (گران، گران‌تر، گران‌ترین)",
                            "answer_fa": "این کیف، گران‌ترین کیف است.",
                            "reading_az": "İn kif, gərantərin kif əst.",
                            "az": "Bu çanta ən bahalı çantadır.",
                        },
                        {
                            "prompt_fa": "من و دوستانم امروز ______ هستیم. (خوش‌حال، خوش‌حال‌تر، خوش‌حال‌ترین)",
                            "answer_fa": "من و دوستانم امروز خوش‌حال هستیم.",
                            "reading_az": "Mən o dustanəm əmruz xoşhal həstim.",
                            "az": "Mən və dostlarım bu gün xoşbəxtik.",
                        },
                        {
                            "prompt_fa": "محمّد و مهدی خیلی ______ هستند. (لاغر، لاغرتر، لاغرترین)",
                            "answer_fa": "محمّد و مهدی خیلی لاغر هستند.",
                            "reading_az": "Mohəmməd o Mehdi xeyli laqər həstənd.",
                            "az": "Məhəmməd və Mehdi çox arıqdırlar.",
                        },
                        {
                            "prompt_fa": "خط من، ______ از خط دوستم است. (زیبا، زیباتر، زیباترین)",
                            "answer_fa": "خط من، زیباتر از خط دوستم است.",
                            "reading_az": "Xətte mən, zibatər əz xətte dustəm əst.",
                            "az": "Mənim xəttim dostumun xəttindən gözəldir.",
                        },
                        {
                            "prompt_fa": "ژاکت جواد، ______ از ژاکت من است. (ضخیم، ضخیم‌تر، ضخیم‌ترین)",
                            "answer_fa": "ژاکت جواد، ضخیم‌تر از ژاکت من است.",
                            "reading_az": "Jakete Cavad, zoximtər əz jakete mən əst.",
                            "az": "Cavadın jaketi mənim jaketimdən qalındır.",
                        },
                        {
                            "prompt_fa": "این خیابان، ______ خیابان این شهر است. (خلوت، خلوت‌تر، خلوت‌ترین)",
                            "answer_fa": "این خیابان، خلوت‌ترین خیابان این شهر است.",
                            "reading_az": "İn xiyaban, xəlvattərin xiyabane in şəhr əst.",
                            "az": "Bu küçə bu şəhərin ən sakit küçəsidir.",
                        },
                    ],
                },
                {
                    "title_fa": "لطفاً تصحیح کنید",
                    "instruction_az": "Səhv cümlələri düzəldin (müqayisə «تر + از» ilə, üstünlük isə tək başına «ترین» ilə işlənir).",
                    "items": [
                        {
                            "prompt_fa": "محمّد قوی از سعید و یاسر است.",
                            "answer_fa": "محمّد قوی‌تر از سعید و یاسر است.",
                            "reading_az": "Mohəmməd qəvitər əz Səid o Yasər əst.",
                            "az": "Məhəmməd Səid və Yasirdən güclüdür.",
                        },
                        {
                            "prompt_fa": "کفش شما نوترین کفش من است.",
                            "answer_fa": "کفش شما نوتر از کفش من است.",
                            "reading_az": "Kəfşe şoma noutər əz kəfşe mən əst.",
                            "az": "Sizin ayaqqabınız mənim ayaqqabımdan təzədir.",
                        },
                        {
                            "prompt_fa": "خط‌کش لیلا ارزان‌تر خط‌کش نرگس است.",
                            "answer_fa": "خط‌کش لیلا ارزان‌تر از خط‌کش نرگس است.",
                            "reading_az": "Xətkeşe Leyla ərzantər əz xətkeşe Nərges əst.",
                            "az": "Leylanın xətkeşi Nərgizin xətkeşindən ucuzdur.",
                        },
                        {
                            "prompt_fa": "این اتاق، روشن‌تر اتاق است.",
                            "answer_fa": "این اتاق، روشن‌تر از آن اتاق است.",
                            "reading_az": "İn otaq, rouşəntər əz an otaq əst.",
                            "az": "Bu otaq o otaqdan daha işıqlıdır.",
                        },
                        {
                            "prompt_fa": "این انگور، خوش‌مزه‌ترین انگور از آن انگور است.",
                            "answer_fa": "این انگور، خوش‌مزه‌ترین انگور است.",
                            "reading_az": "İn əngur, xoşmezetərin əngur əst.",
                            "az": "Bu üzüm ən dadlı üzümdür.",
                        },
                    ],
                },
            ],
        },
        {
            "title_az": "«چرا» ؛ «چون» و «برای این‌که» (niyə? çünki, ona görə ki)",
            "title_fa": "«چرا» ؛ «چون» و «برای این‌که»",
            "conjugations": [
                {"pronoun_fa": "چرا امروز خیلی خوش‌حال هستی؟", "form_fa": "چون روز تولّد من است."},
                {"pronoun_fa": "چرا روسری و مانتوی آبی می‌پوشی؟", "form_fa": "برای این‌که رنگ آبی را زیاد دوست دارم."},
            ],
            "examples": [
                {
                    "fa": "چرا غذا نمی‌خوری؟ چون سیر هستم؛ گرسنه نیستم.",
                    "reading_az": "Çera qəza nemixori? Çon sir həstəm; gorosne nistəm.",
                    "az": "Niyə yemək yemirsən? Çünki toxam; ac deyiləm.",
                },
                {
                    "fa": "چرا تکلیف‌هایت را ننوشتی؟ برای این‌که دیروز مریض بودم.",
                    "reading_az": "Çera təklifhayət ra nəneveşti? Bəraye inke diruz mariz budəm.",
                    "az": "Niyə tapşırıqlarını yazmadın? Ona görə ki, dünən xəstə idim.",
                },
                {
                    "fa": "چرا لامپ‌ها را روشن کردند؟ چون هوا تاریک است.",
                    "reading_az": "Çera lamphara rouşən kərdənd? Çon həva tarik əst.",
                    "az": "Niyə lampaları yandırdılar? Çünki hava qaranlıqdır.",
                },
                {
                    "fa": "چرا چلوکباب زیاد دوست داری؟ چون چلوکباب بسیار خوش‌مزه است.",
                    "reading_az": "Çera çəlokəbab ziyad dust dari? Çon çəlokəbab besyar xoşməze əst.",
                    "az": "Niyə plov-kababı çox sevirsən? Çünki plov-kabab çox dadlıdır.",
                },
                {
                    "fa": "چرا لباس‌هایت را روی طناب آویزان کردی؟ چون لباس‌هایم خیس بود.",
                    "reading_az": "Çera ləbashayət ra ruye tənab avizan kərdi? Çon ləbashayəm xis bud.",
                    "az": "Niyə paltarlarını ip üstünə asdın? Çünki paltarlarım yaş idi.",
                },
                {
                    "fa": "چرا تلویزیون کم تماشا می‌کنی؟ برای این‌که درس‌ها و تکلیف‌هایم زیاد است.",
                    "reading_az": "Çera televizion kəm təmaşa mikoni? Bəraye inke dərsha va təklifhayəm ziyad əst.",
                    "az": "Niyə televizoru az izləyirsən? Ona görə ki, dərslərim və tapşırıqlarım çoxdur.",
                },
            ],
        },
    ],
    "exercises": [
        {
            "kind": "fill_blank",
            "instruction_az": "Uyğun sifətlə tamamlayın.",
            "word_bank": ["شجاع", "روشن", "تاریک", "می‌زنند", "می‌خندند", "ترش", "شیرین", "گران", "ارزان"],
            "items": [
                {
                    "fa_with_blank": "حسین ___ است، ترسو نیست.",
                    "correct_answer": "شجاع",
                    "reading_az": "şoja",
                    "az": "cəsur",
                    "full_reading_az": "Hosein şoja əst, tərsu nist.",
                    "full_translation_az": "Hüseyn cəsurdur, qorxaq deyil.",
                },
                {
                    "fa_with_blank": "روزها هوا ___ است و شب‌ها هوا تاریک است.",
                    "correct_answer": "روشن",
                    "reading_az": "rouşən",
                    "az": "işıqlı",
                    "full_reading_az": "Ruzha həva rouşən əst va şəbha həva tarik əst.",
                    "full_translation_az": "Gündüzlər hava işıqlı, gecələr isə qaranlıqdır.",
                },
                {
                    "fa_with_blank": "آن‌ها هنگام خوش‌حال بودن لبخند ___ یا می‌خندند.",
                    "correct_answer": "می‌زنند",
                    "reading_az": "mizənənd",
                    "az": "gülümsəyirlər",
                    "full_reading_az": "Anha hengame xoşhal budən ləbxənd mizənənd ya mixəndənd.",
                    "full_translation_az": "Onlar xoşbəxt olan zaman gülümsəyir və ya gülürlər.",
                },
                {
                    "fa_with_blank": "بعضی از لیموها ___ هستند و بعضی از لیموها شیرین هستند.",
                    "correct_answer": "ترش",
                    "reading_az": "torş",
                    "az": "turş",
                    "full_reading_az": "Bəzi əz limuha torş həstənd va bəzi əz limuha şirin həstənd.",
                    "full_translation_az": "Limonların bəziləri turş, bəziləri isə şirin olur.",
                },
                {
                    "fa_with_blank": "ثروتمندان لباس‌های ___ می‌پوشند و انسان‌های فقیر لباس‌های ارزان می‌پوشند.",
                    "correct_answer": "گران",
                    "reading_az": "gəran",
                    "az": "bahalı",
                    "full_reading_az": "Servətməndan ləbashaye gəran mipuşənd va insanhaye fəqir ləbashaye ərzan mipuşənd.",
                    "full_translation_az": "Varlılar bahalı paltarlar geyinir, kasıb insanlar isə ucuz paltarlar geyinir.",
                },
            ],
        },
        {
            "kind": "fill_blank",
            "instruction_az": "Müqayisə/üstünlük dərəcəsi ilə tamamlayın.",
            "word_bank": ["قوی", "ضعیف", "بیشتر", "خیس", "قوی‌ترین", "بزرگ‌ترین", "بالاتر"],
            "items": [
                {
                    "fa_with_blank": "احمد و سجّاد ___ هستند، ضعیف نیستند.",
                    "correct_answer": "قوی",
                    "reading_az": "qəvi",
                    "az": "güclü",
                    "full_reading_az": "Əhməd o Səccad qəvi həstənd, zəif nistənd.",
                    "full_translation_az": "Əhməd və Səccad güclüdürlər, zəif deyillər.",
                },
                {
                    "fa_with_blank": "این درخت ___ از آن درخت میوه دارد.",
                    "correct_answer": "بیشتر",
                    "reading_az": "biştər",
                    "az": "daha çox",
                    "full_reading_az": "İn dərəxt biştər əz an dərəxt mive darəd.",
                    "full_translation_az": "Bu ağacın o ağacdan daha çox meyvəsi var.",
                },
                {
                    "fa_with_blank": "من لباس‌های ___ را روی طناب آویزان کردم.",
                    "correct_answer": "خیس",
                    "reading_az": "xis",
                    "az": "yaş",
                    "full_reading_az": "Mən ləbashaye xis ra ruye tənab avizan kərdəm.",
                    "full_translation_az": "Mən yaş paltarları ipin üstünə asdım.",
                },
                {
                    "fa_with_blank": "شیر ___ و فیل بزرگ‌ترین حیوان جنگل هستند.",
                    "correct_answer": "قوی‌ترین",
                    "reading_az": "qəvitərin",
                    "az": "ən güclü",
                    "full_reading_az": "Şir qəvitərin va fil bozorgtərin heyvane cəngəl həstənd.",
                    "full_translation_az": "Şir meşənin ən güclü, fil isə ən böyük heyvanıdır.",
                },
                {
                    "fa_with_blank": "طبقه‌ی سوم ___ از طبقه‌ی دوم است.",
                    "correct_answer": "بالاتر",
                    "reading_az": "balatər",
                    "az": "daha yuxarı",
                    "full_reading_az": "Təbəqeye sevvom balatər əz təbəqeye dovvom əst.",
                    "full_translation_az": "Üçüncü mərtəbə ikinci mərtəbədən yuxarıdadır.",
                },
            ],
        },
        {
            "kind": "multiple_choice",
            "instruction_az": "«کلاس جالب ما» mətninə görə düzgün cavabı seçin.",
            "items": [
                {"question_fa": "کلاس نویسنده چگونه توصیف شده است؟", "options": ["یکی از بهترین و جالب‌ترین کلاس‌های مدرسه", "کوچک‌ترین کلاس مدرسه", "خلوت‌ترین کلاس مدرسه"], "correct_index": 0},
                {"question_fa": "لاغرترین فرد کلاس کیست و چند کیلو وزن دارد؟", "options": ["بغل‌دستی نویسنده؛ بیشتر از سی و پنج کیلو نیست", "معلّم کلاس؛ چهل کیلو", "دوست نویسنده؛ سی کیلو"], "correct_index": 0},
                {"question_fa": "قدبلندترین فرد کلاس چند متر قد دارد؟", "options": ["حدود دو متر و ده سانتی‌متر", "یک متر و هشتاد سانتی‌متر", "دو متر و پنجاه سانتی‌متر"], "correct_index": 0},
                {"question_fa": "کوتاه‌ترین دانش‌آموز کلاس چند قد دارد؟", "options": ["یک متر و بیست سانتی‌متر", "یک متر و پنجاه سانتی‌متر", "نود سانتی‌متر"], "correct_index": 0},
                {"question_fa": "دو نفر که قدشان خیلی فرق دارد، به چه چیزی تشبیه شده‌اند؟", "options": ["فیل و فنجان", "شیر و روباه", "کوه و دشت"], "correct_index": 0},
                {"question_fa": "چاق‌ترین فرد کلاس چند کیلو وزن دارد؟", "options": ["حدود صد و بیست کیلو", "حدود هشتاد کیلو", "حدود صد کیلو"], "correct_index": 0},
                {"question_fa": "چاق‌ترین فرد کلاس چگونه شخصیّتی دارد؟", "options": ["بسیار خوش‌اخلاق و شوخ", "بسیار ساکت و جدّی", "ترسو و ناراحت"], "correct_index": 0},
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Müqayisə dərəcəsi ilə cümlə qurun: «من / برنج ارزان / خریدن → من برنج ارزان می‌خرم، برنج گران نمی‌خرم.»",
            "example_prompt_fa": "من / برنج ارزان / خریدن",
            "example_answer_fa": "من برنج ارزان می‌خرم، برنج گران نمی‌خرم.",
            "example_reading_az": "Mən berence ərzan mixərəm, berence gəran nemixərəm.",
            "example_az": "Mən ucuz düyü alıram, bahalı düyü almıram.",
            "items": [
                {
                    "prompt_fa": "محمّد / لباس سفید / دوست داشتن",
                    "answer_fa": "محمّد لباس سفید دوست دارد، لباس رنگی دوست ندارد.",
                    "reading_az": "Mohəmməd ləbase sefid dust darəd, ləbase rəngi dust nədarəd.",
                    "az": "Məhəmməd ağ paltarı sevir, rəngli paltarı sevmir.",
                },
                {
                    "prompt_fa": "حسین / طبقه‌ی بالا / زندگی کردن",
                    "answer_fa": "حسین طبقه‌ی بالا زندگی می‌کند، طبقه‌ی پایین زندگی نمی‌کند.",
                    "reading_az": "Hosein təbəqeye bala zendegi mikonəd, təbəqeye payin zendegi nemikonəd.",
                    "az": "Hüseyn yuxarı mərtəbədə yaşayır, aşağı mərtəbədə yaşamır.",
                },
                {
                    "prompt_fa": "انسان ترسو / حیوان‌ها / ترسیدن",
                    "answer_fa": "انسان ترسو از حیوان‌ها می‌ترسد، انسان شجاع نمی‌ترسد.",
                    "reading_az": "Insane tərsu əz heyvanha mitərsəd, insane şoja nemitərsəd.",
                    "az": "Qorxaq insan heyvanlardan qorxur, cəsur insan qorxmur.",
                },
                {
                    "prompt_fa": "ثروتمندها / لباس نو و گران / پوشیدن",
                    "answer_fa": "ثروتمندها لباس نو و گران می‌پوشند، لباس کهنه نمی‌پوشند.",
                    "reading_az": "Servətməndha ləbase nou o gəran mipuşənd, ləbase kohne nemipuşənd.",
                    "az": "Varlılar təzə və bahalı paltar geyinir, köhnə paltar geyinmirlər.",
                },
            ],
        },
    ],
    "sentence_practice": {
        "listen_items": [
            {
                "fa": "غوره ترش است و انگور شیرین است.",
                "reading_az": "Qure torş əst va əngur şirin əst.",
                "az": "Qora turşdur, üzüm isə şirindir.",
            },
            {
                "fa": "موش‌ها از گربه‌ها می‌ترسند.",
                "reading_az": "Muşha əz gorbeha mitərsənd.",
                "az": "Siçanlar pişiklərdən qorxur.",
            },
            {
                "fa": "این کودک، گرسنه است و گریه می‌کند؛ او شیر می‌خواهد.",
                "reading_az": "İn kudək, gorosne əst va gerye mikonəd; u şir mixahəd.",
                "az": "Bu uşaq acdır və ağlayır; o, süd istəyir.",
            },
            {
                "fa": "بچّه‌ها هنگام جشن تولّدشان خوش‌حال هستند و می‌خندند.",
                "reading_az": "Bəççeha hengame cəşne touləduşan xoşhal həstənd va mixəndənd.",
                "az": "Uşaqlar ad günü şənliyində xoşbəxtdirlər və gülürlər.",
            },
            {
                "fa": "پنجره‌ی اتاق باز است یا پنجره‌ی اتاق بسته است.",
                "reading_az": "Pəncereye otaq baz əst ya pəncereye otaq bəste əst.",
                "az": "Otağın pəncərəsi açıqdır, yoxsa bağlıdır?",
            },
            {
                "fa": "مادران هنگام بیمار شدنِ کودکانشان، ناراحت هستند.",
                "reading_az": "Madəran hengame bimar şodəne kudəkaneşan, narahat həstənd.",
                "az": "Analar uşaqları xəstələndikdə narahat olurlar.",
            },
            {
                "fa": "در جنگل حیوان‌های قوی، حیوان‌های ضعیف را می‌خورند.",
                "reading_az": "Dər cəngəl heyvanhaye qəvi, heyvanhaye zəif ra mixorənd.",
                "az": "Meşədə güclü heyvanlar zəif heyvanları yeyir.",
            },
            {
                "fa": "خط بعضی از دانش‌آموزان در کتاب اوّل زشت است و در کتاب‌های بعد زیبا است.",
                "reading_az": "Xətte bəzi əz danışamuzan dər ketabe əvvəl zeşt əst va dər ketabhaye bəd ziba əst.",
                "az": "Bəzi şagirdlərin xətti birinci kitabda çirkin, sonrakı kitablarda isə gözəldir.",
            },
            {
                "fa": "پوست درخت، پوست آناناس و خربزه زبر است؛ پنبه، پوست گربه و دم روباه نرم است.",
                "reading_az": "Puste dərəxt, puste ananas o xərboze zebr əst; pənbe, puste gorbe o dome rubah nərm əst.",
                "az": "Ağacın qabığı, ananas və qovunun qabığı sərtdir; pambıq, pişiyin dərisi və tülkünün quyruğu yumşaqdır.",
            },
            {
                "fa": "لباس‌های من زیر باران خیس شد؛ آن‌ها را برای خشک‌کردن، کنار بخاری آویزان کردم.",
                "reading_az": "Ləbashaye mən zire baran xis şod; anha ra bəraye xoşkkərdən, kənare boxari avizan kərdəm.",
                "az": "Mənim paltarlarım yağış altında islandı; onları qurutmaq üçün soba kənarında asdım.",
            },
        ],
        "answer_items": [
            {
                "fa": "چرا دیروز به کلاس نرفتی؟",
                "reading_az": "Çera diruz be kelas nərəfti?",
                "az": "Niyə dünən sinfə getmədin?",
                "sample_answer_fa": "چون مریض بودم.",
                "sample_answer_reading_az": "Çon mariz budəm.",
                "sample_answer_az": "Çünki xəstə idim.",
            },
            {
                "fa": "چرا در کلاس را می‌بندید؟",
                "reading_az": "Çera dəre kelas ra mibəndid?",
                "az": "Niyə sinfin qapısını bağlayırsınız?",
                "sample_answer_fa": "چون هوا سرد است.",
                "sample_answer_reading_az": "Çon həva sərd əst.",
                "sample_answer_az": "Çünki hava soyuqdur.",
            },
            {
                "fa": "چرا جنگل، کوه و دریا را دوست داری؟",
                "reading_az": "Çera cəngəl, kuh o dərya ra dust dari?",
                "az": "Niyə meşəni, dağı və dənizi sevirsən?",
                "sample_answer_fa": "چون طبیعت آن‌ها بسیار زیباست.",
                "sample_answer_reading_az": "Çon təbiəte anha besyar zibast.",
                "sample_answer_az": "Çünki onların təbiəti çox gözəldir.",
            },
            {
                "fa": "چرا در زمستان، لباس‌های ضخیم می‌پوشیم؟",
                "reading_az": "Çera dər zemestan, ləbashaye zəxim mipuşim?",
                "az": "Niyə qışda qalın paltarlar geyinirik?",
                "sample_answer_fa": "برای این‌که هوا سرد است.",
                "sample_answer_reading_az": "Bəraye inke həva sərd əst.",
                "sample_answer_az": "Ona görə ki, hava soyuqdur.",
            },
        ],
    },
    "reading_text": {
        "title_fa": "کلاس جالب ما",
        "title_az": "Bizim maraqlı sinfimiz",
        "paragraphs_fa": [
            "کلاس ما یکی از بهترین و جالب‌ترین کلاس‌های مدرسه است. در کلاس ما همه‌جور آدمی هست؛ از کوتاه قد تا بلند قد، از چاقِ چاق تا لاغرِ لاغر.",
            "بغل‌دستی من لاغرترین فرد کلاس است. به نظرم بیشتر از سی و پنج کیلو وزن ندارد. قدبلندترین فرد کلاس ما حدود دو متر و ده سانتی‌متر است و کوتاه‌ترین دانش‌آموز کلاس ما یک متر و بیست سانتی‌متر قد دارد. این دو نفر وقتی کنار هم می‌ایستند، مانند فیل و فنجان هستند.",
            "یکی دیگر از هم‌کلاسی‌هایم، بسیار چاق است. وزن او حدود صد کیلو است؛ امّا چاق‌تر از او در هم کلاس ما هست: چاق‌ترین فرد کلاس ما صد و بیست کیلو وزن دارد. او بسیار خوش‌اخلاق است و همیشه با دیگران شوخی می‌کند.",
        ],
        "footnotes": [
            {"fa": "جالب", "az": "maraqlı"},
            {"fa": "بغل‌دستی", "az": "yan qonşusu"},
            {"fa": "به نظر من", "az": "mənim fikrimcə"},
            {"fa": "خلاصه", "az": "xülasə"},
        ],
        "full_translation_az": (
            "Bizim sinfimiz məktəbin ən yaxşı və ən maraqlı siniflərindən biridir. Sinfimizdə hər cür insan var; "
            "balacaboydan hündürboya qədər, çox arıqdan çox köküyə qədər.\n\n"
            "Yan qonşum sinfin ən arıq şəxsidir. Fikrimcə, otuz beş kiloqramdan çox çəkisi yoxdur. Sinfimizin ən "
            "hündürboylu şəxsi təxminən iki metr on santimetrdir, ən balacaboylu şagirdimiz isə bir metr iyirmi "
            "santimetr boydadır. Bu iki nəfər yan-yana durduqda fil və fincan kimi görünürlər.\n\n"
            "Sinif yoldaşlarımdan biri də çox kökdür. Onun çəkisi təxminən yüz kiloqramdır; amma sinfimizdə "
            "ondan da kökü var: sinfin ən kök şəxsinin çəkisi yüz iyirmi kiloqramdır. O, çox xoşrəftardır və "
            "həmişə başqaları ilə zarafat edir."
        ),
        "sentences": [
            {
                "fa": "کلاس ما یکی از بهترین و جالب‌ترین کلاس‌های مدرسه است.",
                "reading_az": "Kelase ma yeki əz behtərin o calebtərin kelashaye mədrese əst.",
                "az": "Bizim sinfimiz məktəbin ən yaxşı və ən maraqlı siniflərindən biridir.",
                "new_paragraph": True,
            },
            {
                "fa": "در کلاس ما همه‌جور آدمی هست؛ از کوتاه قد تا بلند قد، از چاقِ چاق تا لاغرِ لاغر.",
                "reading_az": "Dər kelase ma həmecur adəmi həst; əz kutah qəd ta bolənd qəd, əz çaqe çaq ta laqəre laqər.",
                "az": "Sinfimizdə hər cür insan var; balacaboydan hündürboya qədər, çox arıqdan çox köküyə qədər.",
            },
            {
                "fa": "بغل‌دستی من لاغرترین فرد کلاس است.",
                "reading_az": "Bəğəldəstiye mən laqərtərin fərde kelas əst.",
                "az": "Yan qonşum sinfin ən arıq şəxsidir.",
                "new_paragraph": True,
            },
            {
                "fa": "به نظرم بیشتر از سی و پنج کیلو وزن ندارد.",
                "reading_az": "Be nəzərəm biştər əz si o pənc kilo vəzn nədarəd.",
                "az": "Fikrimcə, otuz beş kiloqramdan çox çəkisi yoxdur.",
            },
            {
                "fa": "قدبلندترین فرد کلاس ما حدود دو متر و ده سانتی‌متر است و کوتاه‌ترین دانش‌آموز کلاس ما یک متر و بیست سانتی‌متر قد دارد.",
                "reading_az": "Qədbolənd tərin fərde kelase ma hodude do metr o dah santimetr əst va kutahtərin danışamuze kelase ma yek metr o bist santimetr qəd darəd.",
                "az": "Sinfimizin ən hündürboylu şəxsi təxminən iki metr on santimetrdir, ən balacaboylu şagirdimiz isə bir metr iyirmi santimetr boydadır.",
            },
            {
                "fa": "این دو نفر وقتی کنار هم می‌ایستند، مانند فیل و فنجان هستند.",
                "reading_az": "İn do nəfər vəqti kənare həm mi-istənd, manənde fil o fəncan həstənd.",
                "az": "Bu iki nəfər yan-yana durduqda fil və fincan kimi görünürlər.",
            },
            {
                "fa": "یکی دیگر از هم‌کلاسی‌هایم، بسیار چاق است.",
                "reading_az": "Yeki digər əz həmkelasihayəm, besyar çaq əst.",
                "az": "Sinif yoldaşlarımdan biri də çox kökdür.",
                "new_paragraph": True,
            },
            {
                "fa": "وزن او حدود صد کیلو است؛ امّا چاق‌تر از او در هم کلاس ما هست:",
                "reading_az": "Vəzne u hodude səd kilo əst; əmma çaqtər əz u dər həm kelase ma həst:",
                "az": "Onun çəkisi təxminən yüz kiloqramdır; amma sinfimizdə ondan da kökü var:",
            },
            {
                "fa": "چاق‌ترین فرد کلاس ما صد و بیست کیلو وزن دارد.",
                "reading_az": "Çaqtərin fərde kelase ma səd o bist kilo vəzn darəd.",
                "az": "Sinfin ən kök şəxsinin çəkisi yüz iyirmi kiloqramdır.",
            },
            {
                "fa": "او بسیار خوش‌اخلاق است و همیشه با دیگران شوخی می‌کند.",
                "reading_az": "U besyar xoşəxlaq əst va həmişe ba digəran şuxi mikonəd.",
                "az": "O, çox xoşrəftardır və həmişə başqaları ilə zarafat edir.",
            },
        ],
        "comprehension_questions": [
            {
                "question_fa": "کلاس نویسنده چگونه توصیف شده است؟",
                "reading_az": "Kelase nevisənde çegune touzif şode əst?",
                "az": "Müəllifin sinfi necə təsvir olunub?",
                "sample_answer_fa": "یکی از بهترین و جالب‌ترین کلاس‌های مدرسه.",
                "sample_answer_reading_az": "Yeki əz behtərin o calebtərin kelashaye mədrese.",
                "sample_answer_az": "Məktəbin ən yaxşı və ən maraqlı siniflərindən biri.",
            },
            {
                "question_fa": "لاغرترین فرد کلاس کیست و چند کیلو وزن دارد؟",
                "reading_az": "Laqərtərin fərde kelas kist va cənd kilo vəzn darəd?",
                "az": "Sinfin ən arıq şəxsi kimdir və neçə kiloqram çəkisi var?",
                "sample_answer_fa": "بغل‌دستی نویسنده؛ بیشتر از سی و پنج کیلو نیست.",
                "sample_answer_reading_az": "Bəğəldəstiye nevisənde; biştər əz si o pənc kilo nist.",
                "sample_answer_az": "Müəllifin yan qonşusu; otuz beş kiloqramdan çox deyil.",
            },
            {
                "question_fa": "قدبلندترین فرد کلاس چند متر قد دارد؟",
                "reading_az": "Qədbolənd tərin fərde kelas cənd metr qəd darəd?",
                "az": "Sinfin ən hündürboylu şəxsinin boyu neçə metrdir?",
                "sample_answer_fa": "حدود دو متر و ده سانتی‌متر.",
                "sample_answer_reading_az": "Hodude do metr o dah santimetr.",
                "sample_answer_az": "Təxminən iki metr on santimetr.",
            },
            {
                "question_fa": "کوتاه‌ترین دانش‌آموز کلاس چند قد دارد؟",
                "reading_az": "Kutahtərin danışamuze kelas cənd qəd darəd?",
                "az": "Sinfin ən balacaboylu şagirdinin boyu neçədir?",
                "sample_answer_fa": "یک متر و بیست سانتی‌متر.",
                "sample_answer_reading_az": "Yek metr o bist santimetr.",
                "sample_answer_az": "Bir metr iyirmi santimetr.",
            },
            {
                "question_fa": "دو نفر که قدشان خیلی فرق دارد، به چه چیزی تشبیه شده‌اند؟",
                "reading_az": "Do nəfər ke qədeşan xeyli fərq darəd, be çe çizi təşbih şodeənd?",
                "az": "Boyları çox fərqli olan iki nəfər nəyə bənzədilib?",
                "sample_answer_fa": "به فیل و فنجان.",
                "sample_answer_reading_az": "Be fil o fəncan.",
                "sample_answer_az": "Filə və fincana.",
            },
            {
                "question_fa": "چاق‌ترین فرد کلاس چند کیلو وزن دارد؟",
                "reading_az": "Çaqtərin fərde kelas cənd kilo vəzn darəd?",
                "az": "Sinfin ən kök şəxsi neçə kiloqram çəkisindədir?",
                "sample_answer_fa": "حدود صد و بیست کیلو.",
                "sample_answer_reading_az": "Hodude səd o bist kilo.",
                "sample_answer_az": "Təxminən yüz iyirmi kiloqram.",
            },
            {
                "question_fa": "چاق‌ترین فرد کلاس چگونه شخصیّتی دارد؟",
                "reading_az": "Çaqtərin fərde kelas çegune şəxsiyyəti darəd?",
                "az": "Sinfin ən kök şəxsinin xasiyyəti necədir?",
                "sample_answer_fa": "او بسیار خوش‌اخلاق است و همیشه با دیگران شوخی می‌کند.",
                "sample_answer_reading_az": "U besyar xoşəxlaq əst va həmişe ba digəran şuxi mikonəd.",
                "sample_answer_az": "O, çox xoşrəftardır və həmişə başqaları ilə zarafat edir.",
            },
        ],
    },
}
