# Dərs 18 — انسان و اعضای بدن (İnsan və bədən üzvləri)
# Mənbə: کتاب دوم, səh. 219-230

LESSON = {
    "number": 18,
    "title_fa": "انسان و اعضای بدن",
    "title_az": "İnsan və bədən üzvləri",
    "available": True,
    "vocabulary": [
        {"fa": "مهربان", "reading": "mehrəban", "az": "Mehriban"},
        {"fa": "نامهربان", "reading": "namehrəban", "az": "Mehribansız"},
        {"fa": "متواضع", "reading": "motəvaze", "az": "Təvazökar"},
        {"fa": "متکبّر", "reading": "motəkəbber", "az": "Təkəbbürlü"},
        {"fa": "نابینا (کور)", "reading": "nabina (kur)", "az": "Kor"},
        {"fa": "ناشنوا (کر)", "reading": "naşenəva (kər)", "az": "Kar"},
        {"fa": "معلول", "reading": "məlul", "az": "Əlil"},
        {"fa": "سر، ابرو، بازو", "reading": "sər, əbru, bazu", "az": "Baş, qaş, qol"},
        {"fa": "سینه", "reading": "sine", "az": "Sinə"},
        {"fa": "معده", "reading": "mede", "az": "Mədə"},
        {"fa": "ماهیچه (عضله)", "reading": "mahiçe (əzəle)", "az": "Əzələ"},
        {"fa": "استخوان", "reading": "ostoxan", "az": "Sümük"},
        {"fa": "نوزاد", "reading": "nouzad", "az": "Körpə (yenidoğulmuş)"},
        {"fa": "احترام می‌گذارد", "reading": "ehteram migozarəd", "az": "hörmət edir"},
        {"fa": "بغل می‌کند", "reading": "bəğəl mikonəd", "az": "qucaqlayır"},
        {"fa": "نوازش می‌کند", "reading": "nəvazeş mikonəd", "az": "sığallayır"},
        {"fa": "می‌بوسد", "reading": "mibusəd", "az": "öpür"},
        {"fa": "صحبت می‌کند", "reading": "sohbət mikonəd", "az": "danışır"},
        {"fa": "به دنیا می‌آید", "reading": "be donya miayəd", "az": "dünyaya gəlir"},
        {"fa": "از دنیا می‌رود", "reading": "əz donya mirəvəd", "az": "dünyadan köçür"},
        {"fa": "شانه می‌زند (کوتاه می‌کند)", "reading": "şane mizənəd (kutah mikonəd)", "az": "daramaq / qısaltmaq"},
        {"fa": "قسمت", "reading": "qesmət", "az": "Hissə"},
        {"fa": "محکم", "reading": "mohkəm", "az": "Möhkəm"},
        {"fa": "بهتر", "reading": "behtər", "az": "Daha yaxşı"},
        {"fa": "طعم و مزه", "reading": "tam o məze", "az": "Dad"},
        {"fa": "شور", "reading": "şur", "az": "Şor"},
        {"fa": "تند", "reading": "tond", "az": "Acı (yeməkdə)"},
        {"fa": "احساس می‌کند", "reading": "ehsas mikonəd", "az": "hiss edir"},
        {"fa": "حس می‌کند", "reading": "hes mikonəd", "az": "hiss edir"},
        {"fa": "نفس می‌کشد", "reading": "nəfəs mikeşəd", "az": "nəfəs alır"},
        {"fa": "حرف می‌زند", "reading": "hərf mizənəd", "az": "danışır"},
        {"fa": "راه می‌رود", "reading": "rah mirəvəd", "az": "yeriyir"},
        {"fa": "به وسیله‌یِ", "reading": "be vasileye", "az": "…vasitəsilə"},
        {"fa": "علاوه بر", "reading": "əlave bər", "az": "…dan əlavə"},
    ],
    "grammar_notes": [
        {
            "title_az": "«دست، دسته و…» — bənzər sözlərin fərqi",
            "title_fa": "دست، دسته و ...",
            "conjugations": [
                {"pronoun_fa": "دست (əl)", "form_fa": "انسان دو دست دارد."},
                {"pronoun_fa": "دسته (qulp/dəstə)", "form_fa": "پارچ و سطل دسته دارند."},
                {"pronoun_fa": "پا (ayaq)", "form_fa": "ما دو پا داریم."},
                {"pronoun_fa": "پایه (ayaq/dayaq — mebel üçün)", "form_fa": "این صندلی، چهار پایه دارد."},
                {"pronoun_fa": "چشم (göz)", "form_fa": "انسان‌ها و حیوان‌ها چشم دارند."},
                {"pronoun_fa": "چشمه (bulaq)", "form_fa": "در کوه و جنگل چشمه وجود دارد."},
                {"pronoun_fa": "دندان (diş)", "form_fa": "این دندان است."},
                {"pronoun_fa": "دندانه (dişcik — hərflərdə)", "form_fa": "حرف «س» سه دندانه دارد."},
                {"pronoun_fa": "ریش (saqqal)", "form_fa": "این مرد، ریش دارد."},
                {"pronoun_fa": "ریشه (kök)", "form_fa": "درخت ریشه دارد."},
                {"pronoun_fa": "شاخ (buynuz)", "form_fa": "گاو شاخ دارد."},
                {"pronoun_fa": "شاخه (budaq)", "form_fa": "درخت شاخه دارد."},
            ],
            "examples": [
                {
                    "fa": "بدن انسان، اعضای گوناگونی دارد؛ امّا بعضی از واژه‌ها با اضافه‌شدن یک حرف، معنای دیگری پیدا می‌کنند.",
                    "reading_az": "Bədəne insan, əzaye gunaguni darəd; əmma bəzi əz vajeha ba əzafe-şodəne yek hərf, məənaye digəri peyda mikonənd.",
                    "az": "İnsan bədəninin müxtəlif üzvləri var; amma bəzi sözlər bir hərf artıqla başqa məna qazanır (dəst→dəstə, pa→paye).",
                },
                {
                    "fa": "پارچ و سطل دسته دارند؛ امّا انسان دست دارد.",
                    "reading_az": "Parç va sətl dəste darənd; əmma insan dəst darəd.",
                    "az": "Dolça və vedrənin qulpu (دسته) olur; insanın isə əli (دست) olur.",
                },
                {
                    "fa": "این صندلی چهار پایه دارد؛ ما دو پا داریم.",
                    "reading_az": "İn səndəli çəhar paye darəd; ma do pa darim.",
                    "az": "Bu stulun dörd ayağı (پایه) var; bizim isə iki ayağımız (پا) var.",
                },
                {
                    "fa": "در کوه و جنگل چشمه وجود دارد؛ انسان‌ها و حیوان‌ها چشم دارند.",
                    "reading_az": "Dər kuh va cəngəl çeşme vocud darəd; insanha va heyvanha çeşm darənd.",
                    "az": "Dağda və meşədə bulaq (چشمه) olur; insanların və heyvanların gözü (چشم) olur.",
                },
                {
                    "fa": "درخت، ریشه و شاخه دارد؛ این مرد ریش دارد و آن گاو شاخ دارد.",
                    "reading_az": "Dərəxt, rişe va şaxe darəd; in mərd riş darəd va an gav şax darəd.",
                    "az": "Ağacın kökü (ریشه) və budağı (شاخه) var; bu kişinin saqqalı (ریش), o inəyin isə buynuzu (شاخ) var.",
                },
            ],
        },
        {
            "title_az": "«مالِ …» quruluşu — sahiblik (kimindir?)",
            "title_fa": "مالِ ........",
            "conjugations": [
                {"pronoun_fa": "این دوچرخه‌ی آبی، مالِ کیست؟", "form_fa": "این دوچرخه‌ی آبی، مالِ من است."},
            ],
            "examples": [
                {
                    "fa": "این عینک، مالِ من است و آن عینک، مالِ برادرم صادق است.",
                    "reading_az": "İn eynək, male mən əst va an eynək, male bəradərəm Sadeq əst.",
                    "az": "Bu eynək mənimdir, o eynək isə qardaşım Sadiqindir.",
                },
                {
                    "fa": "یکی از این دفترها، مالِ خواهرم پروین است.",
                    "reading_az": "Yeki əz in dəftərha, male xahərəm Pərvin əst.",
                    "az": "Bu dəftərlərdən biri bacım Pərvinindir.",
                },
                {
                    "fa": "این عصا مالِ کیست؟ این عصا، مالِ پدربزرگم است.",
                    "reading_az": "İn əsa male kist? İn əsa, male pedərbozorgəm əst.",
                    "az": "Bu əl ağacı kimindir? Bu əl ağacı babamındır.",
                },
                {
                    "fa": "آیا آن خانه‌ی زیبا مالِ عبّاس است؟ بله، آن خانه‌ی زیبا، مالِ عبّاس است.",
                    "reading_az": "Aya an xane-ye ziba male Əbbas əst? Bəle, an xane-ye ziba, male Əbbas əst.",
                    "az": "O gözəl ev Abbasınmıdır? Bəli, o gözəl ev Abbasındır.",
                },
                {
                    "fa": "این انگشتر، مالِ کیست؟ این انگشتر، مالِ دوستم است.",
                    "reading_az": "İn əngoştər, male kist? İn əngoştər, male dustəm əst.",
                    "az": "Bu üzük kimindir? Bu üzük dostumundur.",
                },
            ],
            "drills": [
                {
                    "title_fa": "مانند مثال بپرسید و پاسخ دهید",
                    "instruction_az": 'Nümunə kimi soruşub cavab verin: "انگشتر / دوستم → این انگشتر، مالِ کیست؟ این انگشتر، مالِ دوستم است."',
                    "items": [
                        {
                            "prompt_fa": "پالتو / برادرِ حسن",
                            "answer_fa": "این پالتو، مالِ کیست؟ این پالتو، مالِ برادرِ حسن است.",
                            "reading_az": "İn palto, male kist? İn palto, male bəradəre Həsən əst.",
                            "az": "Bu palto kimindir? Bu palto Həsənin qardaşınındır.",
                        },
                        {
                            "prompt_fa": "جامدادی / برادرزاده‌ام ریحانه",
                            "answer_fa": "این جامدادی، مالِ کیست؟ این جامدادی، مالِ برادرزاده‌ام ریحانه است.",
                            "reading_az": "İn camdadi, male kist? İn camdadi, male bəradərzadeəm Reyhane əst.",
                            "az": "Bu qələmqabı kimindir? Bu qələmqabı qardaşımın qızı Reyhanənindir.",
                        },
                        {
                            "prompt_fa": "آپارتمان / عمویم",
                            "answer_fa": "این آپارتمان، مالِ کیست؟ این آپارتمان، مالِ عمویم است.",
                            "reading_az": "İn apartman, male kist? İn apartman, male əmuyəm əst.",
                            "az": "Bu mənzil kimindir? Bu mənzil əmimindir.",
                        },
                        {
                            "prompt_fa": "مداد رنگی / فرزندِ جواد",
                            "answer_fa": "این مداد رنگی، مالِ کیست؟ این مداد رنگی، مالِ فرزندِ جواد است.",
                            "reading_az": "İn medade rəngi, male kist? İn medade rəngi, male fərzəde Cavad əst.",
                            "az": "Bu rəngli karandaş kimindir? Bu rəngli karandaş Cavadın övladınındır.",
                        },
                        {
                            "prompt_fa": "گل‌فروشی / آقا مهدی",
                            "answer_fa": "این گل‌فروشی، مالِ کیست؟ این گل‌فروشی، مالِ آقا مهدی است.",
                            "reading_az": "İn golforuşi, male kist? İn golforuşi, male ağaye Mehdi əst.",
                            "az": "Bu gül mağazası kimindir? Bu gül mağazası cənab Mehdinindir.",
                        },
                        {
                            "prompt_fa": "ساعت مچی / پسرِ محمّد",
                            "answer_fa": "این ساعت مچی، مالِ کیست؟ این ساعت مچی، مالِ پسرِ محمّد است.",
                            "reading_az": "İn saəte moçi, male kist? İn saəte moçi, male pesəre Mohəmməd əst.",
                            "az": "Bu qol saatı kimindir? Bu qol saatı Məhəmmədin oğlunundur.",
                        },
                    ],
                },
            ],
        },
    ],
    "exercises": [
        {
            "kind": "fill_blank",
            "instruction_az": "Uyğun sözlə tamamlayın.",
            "word_bank": ["نوزاد", "مهربان", "معلول", "نابینا", "ناشنوا"],
            "items": [
                {
                    "fa_with_blank": "کسی که دیگران را دوست دارد و به آن‌ها کمک می‌کند، ___ است.",
                    "correct_answer": "مهربان",
                    "reading_az": "mehrəban",
                    "az": "mehriban",
                    "full_reading_az": "Kəsi ke digəran ra dust darəd va be anha komək mikonəd, mehrəban əst.",
                    "full_translation_az": "Başqalarını sevən və onlara kömək edən kəs mehribandır.",
                },
                {
                    "fa_with_blank": "کسی که دست و پایش سالم نیست، ___ است.",
                    "correct_answer": "معلول",
                    "reading_az": "məlul",
                    "az": "əlil",
                    "full_reading_az": "Kəsi ke dəst va payəş saləm nist, məlul əst.",
                    "full_translation_az": "Əl-ayağı sağlam olmayan kəs əlildir.",
                },
                {
                    "fa_with_blank": "به بچّه‌ای که دو یا سه هفته سن دارد، ___ می‌گویند.",
                    "correct_answer": "نوزاد",
                    "reading_az": "nouzad",
                    "az": "körpə",
                    "full_reading_az": "Be bəççeyi ke do ya se həfte sen darəd, nouzad migoyənd.",
                    "full_translation_az": "İki-üç həftəlik uşağa körpə deyirlər.",
                },
                {
                    "fa_with_blank": "کسی که چشمانش نمی‌بیند، ___ است.",
                    "correct_answer": "نابینا",
                    "reading_az": "nabina",
                    "az": "kor",
                    "full_reading_az": "Kəsi ke çeşmanəş nemibinəd, nabina əst.",
                    "full_translation_az": "Gözləri görməyən kəs kordur.",
                },
                {
                    "fa_with_blank": "کسی که گوش‌هایش نمی‌شنود، ___ است.",
                    "correct_answer": "ناشنوا",
                    "reading_az": "naşenəva",
                    "az": "kar",
                    "full_reading_az": "Kəsi ke guşhayəş nemişenəvəd, naşenəva əst.",
                    "full_translation_az": "Qulaqları eşitməyən kəs kardır.",
                },
            ],
        },
        {
            "kind": "fill_blank",
            "instruction_az": "«دست، دسته؛ پا، پایه؛ چشم، چشمه» kimi cüt sözlərdən doğru olanı seçin.",
            "word_bank": ["دسته", "پایه", "چشمه", "دندانه", "ریشه"],
            "items": [
                {
                    "fa_with_blank": "پارچ و سطل ___ دارند.",
                    "correct_answer": "دسته",
                    "reading_az": "dəste",
                    "az": "qulp",
                    "full_reading_az": "Parç va sətl dəste darənd.",
                    "full_translation_az": "Dolça və vedrənin qulpu var.",
                },
                {
                    "fa_with_blank": "این صندلی، چهار ___ دارد.",
                    "correct_answer": "پایه",
                    "reading_az": "paye",
                    "az": "ayaq (dayaq)",
                    "full_reading_az": "İn səndəli, çəhar paye darəd.",
                    "full_translation_az": "Bu stulun dörd ayağı var.",
                },
                {
                    "fa_with_blank": "در کوه و جنگل ___ وجود دارد.",
                    "correct_answer": "چشمه",
                    "reading_az": "çeşme",
                    "az": "bulaq",
                    "full_reading_az": "Dər kuh va cəngəl çeşme vocud darəd.",
                    "full_translation_az": "Dağda və meşədə bulaq var.",
                },
                {
                    "fa_with_blank": "حرف «س» سه ___ دارد.",
                    "correct_answer": "دندانه",
                    "reading_az": "dəndane",
                    "az": "dişcik",
                    "full_reading_az": "Hərfe se, se dəndane darəd.",
                    "full_translation_az": "«س» hərfinin üç dişciyi var.",
                },
                {
                    "fa_with_blank": "درخت ___ دارد.",
                    "correct_answer": "ریشه",
                    "reading_az": "rişe",
                    "az": "kök",
                    "full_reading_az": "Dərəxt rişe darəd.",
                    "full_translation_az": "Ağacın kökü var.",
                },
            ],
        },
        {
            "kind": "multiple_choice",
            "instruction_az": "«بدن انسان» mətninə görə düzgün cavabı seçin.",
            "items": [
                {"question_fa": "بدن انسان از چه قسمت‌هایی تشکیل شده است؟", "options": ["پوست، گوشت، خون، استخوان و...", "فقط پوست و استخوان", "فقط گوشت"], "correct_index": 0},
                {"question_fa": "ما با پوستمان چه چیزهایی را احساس می‌کنیم؟", "options": ["گرمی، سردی، زبری و نرمی", "فقط رنگ‌ها", "فقط صداها"], "correct_index": 0},
                {"question_fa": "در بدن انسان چند عدد استخوان وجود دارد؟", "options": ["بیش از دویست عدد", "پنجاه عدد", "هزار عدد"], "correct_index": 0},
                {"question_fa": "محکم‌ترین و بلندترین استخوان بدن انسان کدام است؟", "options": ["استخوان ران", "استخوان دست", "استخوان جمجمه"], "correct_index": 0},
                {"question_fa": "چرا بعضی از مردم از عینک استفاده می‌کنند؟", "options": ["چون چشم‌هایشان ضعیف است و خوب نمی‌بینند", "چون گوش‌هایشان درد می‌کند", "برای زیبایی"], "correct_index": 0},
                {"question_fa": "با زبان چه چیزی را حس می‌کنیم؟", "options": ["طعم و مزه‌ی خوردنی‌ها", "بوی گل‌ها", "صداها"], "correct_index": 0},
                {"question_fa": "قلب در بدن چه‌کار می‌کند؟", "options": ["خون را به همه‌جای بدن می‌رساند", "غذا را هضم می‌کند", "صدا را می‌شنود"], "correct_index": 0},
                {"question_fa": "با دست چه کارهایی می‌کنیم؟", "options": ["می‌نویسیم، غذا می‌خوریم و وسایل را برمی‌داریم", "فقط راه می‌رویم", "فقط می‌شنویم"], "correct_index": 0},
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi cümlə qurun: «گوش: ما به وسیله‌ی گوش می‌شنویم.»",
            "items": [
                {
                    "prompt_fa": "دست",
                    "answer_fa": "ما به وسیله‌ی دست می‌نویسیم.",
                    "reading_az": "Ma be vasileye dəst minevisim.",
                    "az": "Biz əl vasitəsilə yazırıq.",
                },
                {
                    "prompt_fa": "بینی",
                    "answer_fa": "ما به وسیله‌ی بینی نفس می‌کشیم و بو می‌کنیم.",
                    "reading_az": "Ma be vasileye bini nəfəs mikeşim va bu mikonim.",
                    "az": "Biz burun vasitəsilə nəfəs alırıq və iy duyuruq.",
                },
                {
                    "prompt_fa": "چشم",
                    "answer_fa": "ما به وسیله‌ی چشم می‌بینیم.",
                    "reading_az": "Ma be vasileye çeşm mibinim.",
                    "az": "Biz göz vasitəsilə görürük.",
                },
                {
                    "prompt_fa": "زبان",
                    "answer_fa": "ما به وسیله‌ی زبان حرف می‌زنیم و طعم غذا را حس می‌کنیم.",
                    "reading_az": "Ma be vasileye zəban hərf mizənim va tame qəza ra hes mikonim.",
                    "az": "Biz dil vasitəsilə danışırıq və yeməyin dadını hiss edirik.",
                },
                {
                    "prompt_fa": "پا",
                    "answer_fa": "ما به وسیله‌ی پا راه می‌رویم.",
                    "reading_az": "Ma be vasileye pa rah mirəvim.",
                    "az": "Biz ayaq vasitəsilə yeriyirik.",
                },
            ],
        },
    ],
    "sentence_practice": {
        "listen_items": [
            {
                "fa": "مادر، نوزادش را بغل می‌کند و می‌بوسد.",
                "reading_az": "Madər, nouzadəş ra bəğəl mikonəd va mibusəd.",
                "az": "Ana körpəsini qucaqlayır və öpür.",
            },
            {
                "fa": "کودکانتان را نوازش کنید و ببوسید.",
                "reading_az": "Kudəkanetan ra nəvazeş konid va bebusid.",
                "az": "Uşaqlarınızı sığallayın və öpün.",
            },
            {
                "fa": "هر روز در این بیمارستان حدود بیست نوزاد به دنیا می‌آید.",
                "reading_az": "Hər ruz dər in bimarestan hodude bist nouzad be donya miayəd.",
                "az": "Hər gün bu xəstəxanada təxminən iyirmi körpə dünyaya gəlir.",
            },
            {
                "fa": "من دیروز به دیدن مادربزرگم رفتم و با او صحبت کردم.",
                "reading_az": "Mən diruz be didəne madərbozorgəm rəftəm va ba u sohbət kərdəm.",
                "az": "Mən dünən nənəmi görməyə getdim və onunla söhbət etdim.",
            },
            {
                "fa": "دوستم معلول است؛ او برای راه رفتن از عصا استفاده می‌کند.",
                "reading_az": "Dustəm məlul əst; u bəraye rah-rəftən əz əsa estefade mikonəd.",
                "az": "Dostum əlildir; o yeriməkdən ötrü əl ağacından istifadə edir.",
            },
            {
                "fa": "علی به مرد نابینا کمک کرد و او را به آن طرف خیابان برد.",
                "reading_az": "Əli be mərde nabina komək kərd va u ra be an tərəfe xiyaban bord.",
                "az": "Əli kor kişiyə kömək etdi və onu küçənin o tərəfinə apardı.",
            },
            {
                "fa": "مادربزرگ سعید، هفتاد و پنج سال زندگی کرد؛ او پارسال از دنیا رفت.",
                "reading_az": "Madərbozorge Səid, həftad o pənc sal zendegi kərd; u parsal əz donya rəft.",
                "az": "Səidin nənəsi yetmiş beş il yaşadı; o keçən il dünyadan köçdü.",
            },
            {
                "fa": "استادمان گفت: روز مادر به دیدن مادرتان بروید و دست ایشان را ببوسید.",
                "reading_az": "Ostademan goft: ruze madər be didəne madəretan bəravid va dəste işan ra bebusid.",
                "az": "Müəllimimiz dedi: Ana günü ananızı görməyə gedin və onun əlindən öpün.",
            },
            {
                "fa": "هر روز در جهان هزاران نفر از دنیا می‌روند و هزاران نفر به دنیا می‌آیند.",
                "reading_az": "Hər ruz dər cəhan hezaran nəfər əz donya mirəvənd va hezaran nəfər be donya miayənd.",
                "az": "Hər gün dünyada minlərlə insan dünyadan köçür və minlərlə insan dünyaya gəlir.",
            },
            {
                "fa": "پدربزرگم همیشه نوه‌هایش را نوازش می‌کند. او بسیار مهربان است.",
                "reading_az": "Pedərbozorgəm həmişe nəvehayəş ra nəvazeş mikonəd. U besyar mehrəban əst.",
                "az": "Babam həmişə nəvələrini sığallayır. O, çox mehribandır.",
            },
            {
                "fa": "نابینا کسی است که چشمانش نمی‌بیند و ناشنوا کسی است که گوش‌هایش نمی‌شنود.",
                "reading_az": "Nabina kəsi əst ke çeşmanəş nemibinəd va naşenəva kəsi əst ke guşhayəş nemişenəvəd.",
                "az": "Kor gözləri görməyən adamdır, kar isə qulaqları eşitməyən adamdır.",
            },
            {
                "fa": "طلبه‌های این کلاس مهربان و متواضع هستند. آن‌ها به استادهایشان احترام می‌گذارند.",
                "reading_az": "Təlabehaye in kelas mehrəban va motəvaze həstənd. Anha be ostadhayeşan ehteram migozarənd.",
                "az": "Bu sinfin tələbələri mehriban və təvazökardır. Onlar müəllimlərinə hörmət edirlər.",
            },
        ],
        "answer_items": [
            {
                "fa": "در صورت انسان چه چیزهایی وجود دارد؟",
                "reading_az": "Dər surəte insan çe çizhayi vocud darəd?",
                "az": "İnsanın üzündə hansı şeylər var?",
                "sample_answer_fa": "در صورت انسان چشم، ابرو، مژه، بینی، لب، سبیل، گونه و چانه وجود دارد.",
                "sample_answer_reading_az": "Dər surəte insan çeşm, əbru, moje, bini, ləb, sebil, gune va çane vocud darəd.",
                "sample_answer_az": "İnsanın üzündə göz, qaş, kirpik, burun, dodaq, bığ, yanaq və çənə var.",
            },
            {
                "fa": "با زبان، چشم و گوش چه کار می‌کنید؟",
                "reading_az": "Ba zəban, çeşm va guş çekar mikonid?",
                "az": "Dillə, gözlə və qulaqla nə edirsiniz?",
                "sample_answer_fa": "با زبان حرف می‌زنیم، با چشم می‌بینیم و با گوش می‌شنویم.",
                "sample_answer_reading_az": "Ba zəban hərf mizənim, ba çeşm mibinim va ba guş mişenəvim.",
                "sample_answer_az": "Dillə danışırıq, gözlə görürük və qulaqla eşidirik.",
            },
            {
                "fa": "زانو و آرنج کجای بدن قرار دارند؟",
                "reading_az": "Zanu va arənc kocaye bədən qərar darənd?",
                "az": "Diz və dirsək bədənin harasında yerləşir?",
                "sample_answer_fa": "زانو در پا و آرنج در دست قرار دارد.",
                "sample_answer_reading_az": "Zanu dər pa va arənc dər dəst qərar darəd.",
                "sample_answer_az": "Diz ayaqda, dirsək isə qolda yerləşir.",
            },
            {
                "fa": "در شکم انسان چه چیزهایی هست؟",
                "reading_az": "Dər şekəme insan çe çizhayi həst?",
                "az": "İnsanın qarnında nələr var?",
                "sample_answer_fa": "در شکم انسان معده، روده‌ی کوچک، روده‌ی بزرگ و کبد وجود دارد.",
                "sample_answer_reading_az": "Dər şekəme insan mede, rudeye kuçek, rudeye bozorg va kəbəd vocud darəd.",
                "sample_answer_az": "İnsanın qarnında mədə, nazik bağırsaq, yoğun bağırsaq və qaraciyər var.",
            },
            {
                "fa": "زبان و معده در کجا قرار دارند؟",
                "reading_az": "Zəban va mede dər koca qərar darənd?",
                "az": "Dil və mədə harada yerləşir?",
                "sample_answer_fa": "زبان در دهان و معده در شکم قرار دارد.",
                "sample_answer_reading_az": "Zəban dər dəhan va mede dər şekəm qərar darəd.",
                "sample_answer_az": "Dil ağızda, mədə isə qarında yerləşir.",
            },
            {
                "fa": "یک دست چند انگشت دارد؟",
                "reading_az": "Yek dəst çənd əngoşt darəd?",
                "az": "Bir əldə neçə barmaq var?",
                "sample_answer_fa": "یک دست پنج انگشت دارد.",
                "sample_answer_reading_az": "Yek dəst pənc əngoşt darəd.",
                "sample_answer_az": "Bir əldə beş barmaq var.",
            },
        ],
    },
    "reading_text": {
        "title_fa": "بدن انسان",
        "title_az": "İnsan bədəni",
        "paragraphs_fa": [
            "بدن انسان قسمت‌های گوناگونی، مانندِ پوست، گوشت، خون، استخوان و... دارد. رنگ پوست انسان‌ها گوناگون است. بعضی از انسان‌ها زردپوست هستند؛ بعضی سیاه‌پوست، برخی سرخ‌پوست و بعضی دیگر سفیدپوست هستند. ما به وسیله‌ی پوست، گرمی، سردی، زبری و نرمی را احساس می‌کنیم.",
            "در بدن انسان، بیش از دویست عدد استخوان وجود دارد. استخوان‌ها بسیار محکم هستند. محکم‌ترین و بلندترین استخوان بدن انسان، استخوان ران است.",
            "در بدن انسان، دو چشم برای دیدن و دو گوش برای شنیدن وجود دارد. بعضی از مردم، چشم‌هایشان ضعیف است و خوب نمی‌بینند. آن‌ها برای بهتر دیدن از عینک استفاده می‌کنند.",
            "ما با بینی علاوه بر نفس کشیدن، بوی غذاها، بوی گل‌ها، عطرها و... را احساس می‌کنیم. به وسیله‌ی زبان حرف می‌زنیم و طعم و مزه‌ی خوردنی‌ها، مانندِ شیرین بودن عسل، شور بودن نمک، تند بودن فلفل و ترش بودن بعضی از میوه‌ها را حس می‌کنیم.",
            "در بدن ما اعضای دیگری هم وجود دارد، مانندِ قلب که به وسیله‌ی آن خون به همه‌جای بدن می‌رسد؛ پا که به وسیله‌ی آن راه می‌رویم و دست که به وسیله‌ی آن غذا می‌خوریم، می‌نویسیم و وسایل را برمی‌داریم.",
        ],
        "footnotes": [
            {"fa": "به وسیله‌یِ", "az": "…vasitəsilə"},
            {"fa": "علاوه بر", "az": "…-dan əlavə"},
            {"fa": "برخی: بعضی", "az": "bəziləri"},
        ],
        "full_translation_az": (
            "İnsan bədəni dəri, ət, qan, sümük və s. kimi müxtəlif hissələrdən ibarətdir. İnsanların dəri rəngi "
            "müxtəlifdir. Bəzi insanlar sarı dərili, bəziləri qara dərili, bəziləri qırmızı dərili, digərləri isə "
            "ağ dərilidirlər. Biz dəri vasitəsilə isti, soyuq, kobud və yumşaq olmağı hiss edirik.\n\n"
            "İnsan bədənində iki yüzdən çox sümük var. Sümüklər çox möhkəmdir. İnsan bədəninin ən möhkəm və ən "
            "uzun sümüyü bud sümüyüdür.\n\n"
            "İnsan bədənində görmək üçün iki göz, eşitmək üçün iki qulaq var. Bəzi insanların gözləri zəifdir və "
            "yaxşı görmürlər. Onlar daha yaxşı görmək üçün eynəkdən istifadə edirlər.\n\n"
            "Biz burunla nəfəs almaqdan əlavə, yeməklərin iyini, güllərin ətrini, ətirləri və s. hiss edirik. Dil "
            "vasitəsilə danışırıq və balın şirin, duzun şor, istiotun acı, bəzi meyvələrin isə turş olmasını hiss "
            "edirik.\n\n"
            "Bədənimizdə başqa üzvlər də var, məsələn ürək ki, onun vasitəsilə qan bədənin hər yerinə çatır; "
            "ayaq ki, onun vasitəsilə yeriyirik; əl isə onun vasitəsilə yemək yeyirik, yazırıq və əşyaları "
            "götürürük."
        ),
        "sentences": [
            {
                "fa": "بدن انسان قسمت‌های گوناگونی، مانندِ پوست، گوشت، خون، استخوان و... دارد.",
                "reading_az": "Bədəne insan qesməthaye gunaguni, manənde pust, guşt, xun, ostoxan va ... darəd.",
                "az": "İnsan bədəni dəri, ət, qan, sümük və s. kimi müxtəlif hissələrdən ibarətdir.",
                "new_paragraph": True,
            },
            {
                "fa": "رنگ پوست انسان‌ها گوناگون است.",
                "reading_az": "Rənge puste insanha gunagun əst.",
                "az": "İnsanların dəri rəngi müxtəlifdir.",
            },
            {
                "fa": "بعضی از انسان‌ها زردپوست هستند؛ بعضی سیاه‌پوست، برخی سرخ‌پوست و بعضی دیگر سفیدپوست هستند.",
                "reading_az": "Bəzi əz insanha zərdpust həstənd; bəzi siyahpust, bəxi sorxpust va bəzi digər sefidpust həstənd.",
                "az": "Bəzi insanlar sarı dərili, bəziləri qara dərili, bəziləri qırmızı dərili, digərləri isə ağ dərilidirlər.",
            },
            {
                "fa": "ما به وسیله‌ی پوست، گرمی، سردی، زبری و نرمی را احساس می‌کنیم.",
                "reading_az": "Ma be vasileye pust, gərmi, sərdi, zəbri va nərmi ra ehsas mikonim.",
                "az": "Biz dəri vasitəsilə isti, soyuq, kobud və yumşaq olmağı hiss edirik.",
            },
            {
                "fa": "در بدن انسان، بیش از دویست عدد استخوان وجود دارد.",
                "reading_az": "Dər bədəne insan, biş əz devist ədəd ostoxan vocud darəd.",
                "az": "İnsan bədənində iki yüzdən çox sümük var.",
                "new_paragraph": True,
            },
            {
                "fa": "استخوان‌ها بسیار محکم هستند.",
                "reading_az": "Ostoxanha besyar mohkəm həstənd.",
                "az": "Sümüklər çox möhkəmdir.",
            },
            {
                "fa": "محکم‌ترین و بلندترین استخوان بدن انسان، استخوان ران است.",
                "reading_az": "Mohkəmtərin va bolənd tərin ostoxane bədəne insan, ostoxane ran əst.",
                "az": "İnsan bədəninin ən möhkəm və ən uzun sümüyü bud sümüyüdür.",
            },
            {
                "fa": "در بدن انسان، دو چشم برای دیدن و دو گوش برای شنیدن وجود دارد.",
                "reading_az": "Dər bədəne insan, do çeşm bəraye didən va do guş bəraye şenidən vocud darəd.",
                "az": "İnsan bədənində görmək üçün iki göz, eşitmək üçün iki qulaq var.",
                "new_paragraph": True,
            },
            {
                "fa": "بعضی از مردم، چشم‌هایشان ضعیف است و خوب نمی‌بینند.",
                "reading_az": "Bəzi əz mərdom, çeşmhayeşan zəif əst va xub nemibinənd.",
                "az": "Bəzi insanların gözləri zəifdir və yaxşı görmürlər.",
            },
            {
                "fa": "آن‌ها برای بهتر دیدن از عینک استفاده می‌کنند.",
                "reading_az": "Anha bəraye behtər didən əz eynək estefade mikonənd.",
                "az": "Onlar daha yaxşı görmək üçün eynəkdən istifadə edirlər.",
            },
            {
                "fa": "ما با بینی علاوه بر نفس کشیدن، بوی غذاها، بوی گل‌ها، عطرها و... را احساس می‌کنیم.",
                "reading_az": "Ma ba bini əlave bər nəfəs-kəşidən, buye qəzaha, buye golha, ətrha va ... ra ehsas mikonim.",
                "az": "Biz burunla nəfəs almaqdan əlavə, yeməklərin iyini, güllərin ətrini, ətirləri və s. hiss edirik.",
                "new_paragraph": True,
            },
            {
                "fa": "به وسیله‌ی زبان حرف می‌زنیم و طعم و مزه‌ی خوردنی‌ها، مانندِ شیرین بودن عسل، شور بودن نمک، تند بودن فلفل و ترش بودن بعضی از میوه‌ها را حس می‌کنیم.",
                "reading_az": "Be vasileye zəban hərf mizənim va tam o məzeye xordəniha, manənde şirin budəne əsəl, şur budəne nəmək, tond budəne felfel va torş budəne bəzi əz miveha ra hes mikonim.",
                "az": "Dil vasitəsilə danışırıq və balın şirin, duzun şor, istiotun acı, bəzi meyvələrin isə turş olmasını hiss edirik.",
            },
            {
                "fa": "در بدن ما اعضای دیگری هم وجود دارد، مانندِ قلب که به وسیله‌ی آن خون به همه‌جای بدن می‌رسد؛ پا که به وسیله‌ی آن راه می‌رویم و دست که به وسیله‌ی آن غذا می‌خوریم، می‌نویسیم و وسایل را برمی‌داریم.",
                "reading_az": "Dər bədəne ma əzaye digəri həm vocud darəd, manənde qəlb ke be vasileye an xun be həme-caye bədən mirəsəd; pa ke be vasileye an rah mirəvim va dəst ke be vasileye an qəza mixorim, minevisim va vəsayel ra bərmidarim.",
                "az": "Bədənimizdə başqa üzvlər də var, məsələn ürək ki, onun vasitəsilə qan bədənin hər yerinə çatır; ayaq ki, onun vasitəsilə yeriyirik; əl isə onun vasitəsilə yemək yeyirik, yazırıq və əşyaları götürürük.",
                "new_paragraph": True,
            },
        ],
        "comprehension_questions": [
            {
                "question_fa": "پوست انسان‌ها چه رنگ است؟",
                "reading_az": "Puste insanha çe rəngi əst?",
                "az": "İnsanların dərisi nə rəngdədir?",
                "sample_answer_fa": "رنگ پوست انسان‌ها گوناگون است؛ بعضی زردپوست، بعضی سیاه‌پوست، برخی سرخ‌پوست و بعضی سفیدپوست هستند.",
                "sample_answer_reading_az": "Rənge puste insanha gunagun əst; bəzi zərdpust, bəzi siyahpust, bəxi sorxpust va bəzi sefidpust həstənd.",
                "sample_answer_az": "İnsanların dəri rəngi müxtəlifdir; bəziləri sarı dərili, bəziləri qara dərili, bəziləri qırmızı dərili, bəziləri isə ağ dərilidir.",
            },
            {
                "question_fa": "بلندترین استخوان بدن کدام است؟",
                "reading_az": "Bolənd tərin ostoxane bədən kodam əst?",
                "az": "Bədənin ən uzun sümüyü hansıdır?",
                "sample_answer_fa": "بلندترین استخوان بدن انسان، استخوان ران است.",
                "sample_answer_reading_az": "Bolənd tərin ostoxane bədəne insan, ostoxane ran əst.",
                "sample_answer_az": "İnsan bədəninin ən uzun sümüyü bud sümüyüdür.",
            },
            {
                "question_fa": "بینی برای چیست؟",
                "reading_az": "Bini bəraye çist?",
                "az": "Burun nə üçündür?",
                "sample_answer_fa": "بینی برای نفس کشیدن و احساس بوها است.",
                "sample_answer_reading_az": "Bini bəraye nəfəs-kəşidən va ehsase buha əst.",
                "sample_answer_az": "Burun nəfəs almaq və qoxuları hiss etmək üçündür.",
            },
            {
                "question_fa": "چرا بعضی از انسان‌ها از عینک استفاده می‌کنند؟",
                "reading_az": "Çera bəzi əz insanha əz eynək estefade mikonənd?",
                "az": "Nə üçün bəzi insanlar eynəkdən istifadə edir?",
                "sample_answer_fa": "چون چشم‌هایشان ضعیف است و خوب نمی‌بینند.",
                "sample_answer_reading_az": "Çon çeşmhayeşan zəif əst va xub nemibinənd.",
                "sample_answer_az": "Çünki gözləri zəifdir və yaxşı görmürlər.",
            },
            {
                "question_fa": "انسان از زبان برای چه کارهایی استفاده می‌کند؟",
                "reading_az": "İnsan əz zəban bəraye çe karhayi estefade mikonəd?",
                "az": "İnsan dildən nə üçün istifadə edir?",
                "sample_answer_fa": "انسان از زبان برای حرف زدن و حس کردن طعم و مزه‌ی خوردنی‌ها استفاده می‌کند.",
                "sample_answer_reading_az": "İnsan əz zəban bəraye hərf-zədən va hes-kərdəne tam o məzeye xordəniha estefade mikonəd.",
                "sample_answer_az": "İnsan dildən danışmaq və yeməklərin dadını hiss etmək üçün istifadə edir.",
            },
            {
                "question_fa": "انسان به وسیله‌ی پوست، چه چیزهایی را احساس می‌کند؟",
                "reading_az": "İnsan be vasileye pust, çe çizhayi ra ehsas mikonəd?",
                "az": "İnsan dəri vasitəsilə nələri hiss edir?",
                "sample_answer_fa": "انسان به وسیله‌ی پوست، گرمی، سردی، زبری و نرمی را احساس می‌کند.",
                "sample_answer_reading_az": "İnsan be vasileye pust, gərmi, sərdi, zəbri va nərmi ra ehsas mikonəd.",
                "sample_answer_az": "İnsan dəri vasitəsilə isti, soyuq, kobud və yumşaq olmağı hiss edir.",
            },
            {
                "question_fa": "انسان به وسیله‌ی پاها و دست‌هایش چه‌کار می‌کند؟",
                "reading_az": "İnsan be vasileye paha va dəsthayəş çekar mikonəd?",
                "az": "İnsan ayaqları və əlləri vasitəsilə nə edir?",
                "sample_answer_fa": "انسان به وسیله‌ی پا راه می‌رود و به وسیله‌ی دست غذا می‌خورد، می‌نویسد و وسایل را برمی‌دارد.",
                "sample_answer_reading_az": "İnsan be vasileye pa rah mirəvəd va be vasileye dəst qəza mixorəd, minevisəd va vəsayel ra bərmidarəd.",
                "sample_answer_az": "İnsan ayaqla yeriyir, əllə isə yemək yeyir, yazır və əşyaları götürür.",
            },
        ],
    },
}
