# Dərs 11 — مکان (Yer)
# Mənbə: کتاب دوم, səh. 135-146

LESSON = {
    "number": 11,
    "title_fa": "مکان",
    "title_az": "Yer",
    "available": True,
    "vocabulary": [
        {"fa": "حرم", "reading": "hərəm", "az": "Hərəm (ziyarətgah)"},
        {"fa": "حوزه‌ی علمیّه", "reading": "houzeye elmiyye", "az": "Elmi hövzə (dini seminariya)"},
        {"fa": "کتاب‌خانه", "reading": "ketabxane", "az": "Kitabxana"},
        {"fa": "کاخ", "reading": "kax", "az": "Saray"},
        {"fa": "موزه", "reading": "muze", "az": "Muzey"},
        {"fa": "سینما", "reading": "sinəma", "az": "Kinoteatr"},
        {"fa": "بوستان (پارک)", "reading": "bustan (park)", "az": "Park"},
        {"fa": "باغ وحش", "reading": "bağe vəhş", "az": "Zoopark"},
        {"fa": "دور", "reading": "dur", "az": "Uzaq"},
        {"fa": "نزدیک", "reading": "nəzdik", "az": "Yaxın"},
        {"fa": "کتاب‌فروشی", "reading": "ketabforuşi", "az": "Kitab mağazası"},
        {"fa": "نمایش‌گاه", "reading": "nəmayeşgah", "az": "Sərgi"},
        {"fa": "دادگاه", "reading": "dadgah", "az": "Məhkəmə"},
        {"fa": "آرایش‌گاه", "reading": "arayeşgah", "az": "Bərbərxana, gözəllik salonu"},
        {"fa": "تعمیرگاه", "reading": "təmirgah", "az": "Təmir emalatxanası"},
        {"fa": "کارخانه", "reading": "karxane", "az": "Zavod"},
        {"fa": "عکّاسی", "reading": "əkkasi", "az": "Fotoatelye"},
        {"fa": "خیّاطی", "reading": "xəyyati", "az": "Dərzixana"},
        {"fa": "نانوایی", "reading": "nanvayi", "az": "Çörəkxana"},
        {"fa": "داخل", "reading": "daxel", "az": "İçəri"},
        {"fa": "خارج", "reading": "xarec", "az": "Bayır, çöl"},
        {"fa": "باز می‌کند", "reading": "baz mikonəd", "az": "açır"},
        {"fa": "می‌بندد", "reading": "mibəndəd", "az": "bağlayır"},
        {"fa": "می‌ماند", "reading": "mimanəd", "az": "qalır"},
        {"fa": "برمی‌گردد", "reading": "bərmigərdəd", "az": "qayıdır"},
        {"fa": "مناسبت", "reading": "monasebət", "az": "Münasibət (vəsilə)"},
        {"fa": "جشن تولّد", "reading": "cəşne touləd", "az": "Ad günü"},
        {"fa": "دسته گل", "reading": "dəste gol", "az": "Gül dəstəsi"},
        {"fa": "شاخه", "reading": "şaxe", "az": "Budaq, sap (gül üçün)"},
        {"fa": "خوش‌بو", "reading": "xoşbu", "az": "Ətirli"},
        {"fa": "گلاب", "reading": "golab", "az": "Gülab"},
        {"fa": "یکی از", "reading": "yeki əz", "az": "…lərdən biri"},
        {"fa": "هدیه می‌کند (می‌دهد)", "reading": "hedye mikonəd (midəhəd)", "az": "hədiyyə edir (verir)"},
    ],
    "grammar_notes": [
        {
            "title_az": "Deyək — deməyək: «برای + məsdər» quruluşu",
            "title_fa": "بگوییم – نگوییم",
            "conjugations": [
                {"pronoun_fa": "من برای لباس دوختن به خیّاطی می‌روم. ✓", "form_fa": "من برای لباس می‌دوزم، به خیّاطی می‌روم. ✗"},
                {"pronoun_fa": "حسین برای درس خواندن به قم می‌آید. ✓", "form_fa": "حسین برای درس می‌خواند به قم می‌آید. ✗"},
            ],
            "examples": [
                {"fa": "«برای» sözündən sonra fel həmişə məsdər (mundarici) formada gəlir, indiki zaman felilə yox.", "az": "«برای» sözündən sonra fel məsdər formasında olmalıdır (…-mək üçün), indiki zamanda deyil."},
                {"fa": "یوسف برای گوشت خریدن به قصّابی می‌رود.", "reading_az": "Yusof bəraye guşt xəridən be qəssabi mirəvəd.", "az": "Yusif ət almaq üçün qəssabxanaya gedir."},
                {"fa": "مریم برای اندازه‌گرفتنِ قدّش، از متر استفاده می‌کند.", "reading_az": "Məryəm bəraye andazegereftəne qəddəş, əz metr estefade mikonəd.", "az": "Məryəm boyunu ölçmək üçün metrdən istifadə edir."},
                {"fa": "زهرا و پدرش برای نماز خواندن به مسجد می‌آیند.", "reading_az": "Zəhra va pedərəş bəraye nəmaz xandən be məsced miayənd.", "az": "Zəhra və atası namaz qılmaq üçün məscidə gəlirlər."},
                {"fa": "خواهرم برای کمک‌کردن به مادرم، هر روز ظرف‌ها را می‌شوید.", "reading_az": "Xahərəm bəraye komək kərdən be madərəm, hər ruz zərfha ra mişuyəd.", "az": "Bacım anama kömək etmək üçün hər gün qabları yuyur."},
            ],
        },
        {
            "title_az": "Həftənin günləri",
            "title_fa": "روزهای هفته",
            "conjugations": [
                {"pronoun_fa": "۱", "form_fa": "شنبه"},
                {"pronoun_fa": "۲", "form_fa": "یک‌شنبه"},
                {"pronoun_fa": "۳", "form_fa": "دوشنبه"},
                {"pronoun_fa": "۴", "form_fa": "سه‌شنبه"},
                {"pronoun_fa": "۵", "form_fa": "چهارشنبه"},
                {"pronoun_fa": "۶", "form_fa": "پنج‌شنبه"},
                {"pronoun_fa": "۷", "form_fa": "جمعه"},
            ],
            "examples": [
                {"fa": "در ایران، کارخانه‌ها، اداره‌ها، مدرسه‌ها و دانش‌گاه‌ها روزهای جمعه تعطیل هستند.", "reading_az": "Dər Iran, karxaneha, edareha, mædreseha va daneşgahha ruzhaye come tətil həstənd.", "az": "İranda zavodlar, idarələr, məktəblər və universitetlər cümə günləri işləmir."},
                {"fa": "ما روزهای یک‌شنبه و پنج‌شنبه، ساعت هفت به استخر می‌رویم و ساعت نه برمی‌گردیم.", "reading_az": "Ma ruzhaye yekşənbe va pəncşənbe, saəte həft be estəxr mirəvim va saəte no bərmigərdim.", "az": "Biz bazar və cümə axşamı günləri saat yeddidə hovuza gedirik və saat doqquzda qayıdırıq."},
                {"fa": "من و پدرم روزهای پنج‌شنبه به روستا می‌رویم و در مزرعه به پدربزرگمان کمک می‌کنیم.", "reading_az": "Mən va pedərəm ruzhaye pəncşənbe be rusta mirəvim va dər məzree be pedərbozorgeman komək mikonim.", "az": "Mən və atam cümə axşamı günləri kəndə gedirik və tarlada babamıza kömək edirik."},
                {"fa": "دکتر عبّاسی روزهای شنبه و یک‌شنبه در تهران و روز دوشنبه در قم بیماران را معاینه می‌کند.", "reading_az": "Doktor Əbbasi ruzhaye şənbe va yekşənbe dər Tehran va ruze doşənbe dər Qom bimaran ra moayene mikonəd.", "az": "Doktor Abbasi şənbə və bazar günləri Tehranda, bazar ertəsi günü isə Qumda xəstələri müayinə edir."},
                {"fa": "در بسیاری از کشورها روزهای شنبه و یک‌شنبه تعطیل است؛ امّا در ایران جمعه‌ها تعطیل است.", "reading_az": "Dər besyari əz kəşvərha ruzhaye şənbe va yekşənbe tətil əst; əmma dər Iran comeha tətil əst.", "az": "Bir çox ölkədə şənbə və bazar günləri istirahət günüdür; amma İranda cümə günü istirahət günüdür."},
                {"fa": "محلّ‌کار ناصر خیلی دور است. او هر هفته شنبه به آن‌جا می‌رود و تا چهارشنبه آن‌جا می‌ماند.", "reading_az": "Məhəlle kare Naser xeyli dur əst. U hər həfte şənbe be anja mirəvəd va ta çəharşənbe anja mimanəd.", "az": "Nasirin iş yeri çox uzaqdır. O, hər həftə şənbə günü ora gedir və çərşənbəyə qədər orada qalır."},
                {"fa": "لغزش «ن» به «م» پیش از «ب»: شنبه → شمبه (تلفّظ)", "reading_az": "Şənbe (nəvis) → şəmbe (təlæffoz).", "az": "Fars dilində «ن» hərfi «ب»-dan əvvəl «م» kimi tələffüz olunur: شنبه → «şəmbe»."},
            ],
            "drills": [
                {
                    "title_fa": "جایگزین کنید",
                    "instruction_az": "Nümunə kimi əvəz edin: «مادربزرگم / دوشنبه / خانه‌ی ما / جمعه → مادربزرگم دوشنبه به خانه‌ی ما می‌آید و تا جمعه روز آن‌جا می‌ماند.»",
                    "items": [
                        {"prompt_fa": "من / شنبه / کشورم / سه‌شنبه", "answer_fa": "من شنبه به کشورم می‌روم و تا سه‌شنبه آن‌جا می‌مانم.", "reading_az": "Mən şənbe be kəşvərəm mirəvəm va ta seşənbe anja mimanəm.", "az": "Mən şənbə günü öz ölkəmə gedirəm və çərşənbəyədək orada qalıram."},
                        {"prompt_fa": "برادرم / یک‌شنبه / تهران / یک سال", "answer_fa": "برادرم یک‌شنبه به تهران می‌آید و یک سال آن‌جا می‌ماند.", "reading_az": "Bəradərəm yekşənbe be Tehran miayəd va yek sal anja mimanəd.", "az": "Qardaşım bazar günü Tehrana gəlir və orada bir il qalır."},
                        {"prompt_fa": "ما / چهارشنبه / روستا / جمعه", "answer_fa": "ما چهارشنبه به روستا می‌رویم و تا جمعه آن‌جا می‌مانیم.", "reading_az": "Ma çəharşənbe be rusta mirəvim va ta come anja mimanim.", "az": "Biz çərşənbə günü kəndə gedirik və cüməyədək orada qalırıq."},
                        {"prompt_fa": "رئیس‌جمهور / امروز / شهر ما / دو روز", "answer_fa": "رئیس‌جمهور امروز به شهر ما می‌آید و دو روز آن‌جا می‌ماند.", "reading_az": "Rəisecomhur emruz be şəhre ma miayəd va do ruz anja mimanəd.", "az": "Prezident bu gün bizim şəhərimizə gəlir və orada iki gün qalır."},
                    ],
                },
            ],
        },
        {
            "title_az": "Sual sözü «چند شنبه» (həftənin hansı günü?)",
            "title_fa": "واژه‌ی پرسشی «چند شنبه»",
            "conjugations": [
                {"pronoun_fa": "امروز چند شنبه است؟", "form_fa": "امروز پنج‌شنبه است."},
                {"pronoun_fa": "پدرت چند شنبه به ایران می‌آید؟", "form_fa": "پدرم دوشنبه به ایران می‌آید."},
            ],
            "examples": [
                {"fa": "لیلا چند شنبه لباس‌هایش را می‌شوید؟ او روزهای دوشنبه و جمعه لباس‌هایش را می‌شوید.", "reading_az": "Leyla çənd şənbe lebashayəş ra mişuyəd? U ruzhaye doşənbe va come lebashayəş ra mişuyəd.", "az": "Leyla həftənin hansı günləri paltarlarını yuyur? O, bazar ertəsi və cümə günləri yuyur."},
                {"fa": "زهرا و حسین چند شنبه به کشورشان برمی‌گردند؟ آن‌ها شنبه یا یک‌شنبه برمی‌گردند.", "reading_az": "Zəhra va Hoseyn çənd şənbe be kəşvəreşan bərmigərdənd? Anha şənbe ya yekşənbe bərmigərdənd.", "az": "Zəhra və Hüseyn həftənin hansı günü öz ölkələrinə qayıdırlar? Onlar şənbə və ya bazar günü qayıdırlar."},
                {"fa": "شما چند شنبه اتاق‌تان را تمیز می‌کنید؟ ما روزهای پنج‌شنبه اتاقمان را تمیز می‌کنیم.", "reading_az": "Şoma çənd şənbe otaqetan ra təmiz mikonid? Ma ruzhaye pəncşənbe otaqeman ra təmiz mikonim.", "az": "Siz otağınızı həftənin hansı günü təmizləyirsiniz? Biz cümə axşamı günləri təmizləyirik."},
                {"fa": "محمّد چند شنبه‌ها به کلاس فارسی می‌رود؟ او از شنبه تا چهارشنبه به کلاس فارسی می‌رود.", "reading_az": "Məhəmməd çənd şənbeha be kelase farsi mirəvəd? U əz şənbe ta çəharşənbe be kelase farsi mirəvəd.", "az": "Məhəmməd fars dili dərsinə həftənin hansı günləri gedir? O, şənbədən çərşənbəyə qədər fars dili dərsinə gedir."},
            ],
        },
        {
            "title_az": "Zaman zərfləri: پریروز؛ دیروز؛ امروز؛ فردا؛ پس‌فردا",
            "title_fa": "قید زمان «... دیروز؛ امروز؛ فردا؛ ...»",
            "conjugations": [
                {"pronoun_fa": "سه روز قبل", "form_fa": "شنبه"},
                {"pronoun_fa": "پریروز", "form_fa": "دوشنبه"},
                {"pronoun_fa": "دیروز", "form_fa": "سه‌شنبه"},
                {"pronoun_fa": "امروز", "form_fa": "چهارشنبه"},
                {"pronoun_fa": "فردا", "form_fa": "پنج‌شنبه"},
                {"pronoun_fa": "پس‌فردا", "form_fa": "جمعه"},
                {"pronoun_fa": "سه روز بعد", "form_fa": "شنبه"},
            ],
            "examples": [
                {"fa": "امروز سه‌شنبه است. فردا چهارشنبه است. پس‌فردا پنج‌شنبه است.", "reading_az": "Emruz seşənbe əst. Fərda çəharşənbe əst. Pəsfərda pəncşənbe əst.", "az": "Bu gün çərşənbə axşamıdır. Sabah çərşənbədir. Birigün cümə axşamıdır."},
                {"fa": "دیروز دوشنبه بود. پریروز یک‌شنبه بود. سه روز قبل شنبه بود.", "reading_az": "Diruz doşənbe bud. Pəriruz yekşənbe bud. Se ruze qəbl şənbe bud.", "az": "Dünən bazar ertəsi idi. Srağagün bazar günü idi. Üç gün əvvəl şənbə idi."},
                {"fa": "دیروز جمعه بود؛ من دیروز درخانه بودم.", "reading_az": "Diruz come bud; mən diruz dər xane budəm.", "az": "Dünən cümə idi; mən dünən evdə idim."},
                {"fa": "امروز شنبه است؛ من امروز در دانش‌گاه هستم.", "reading_az": "Emruz şənbe əst; mən emruz dər daneşgah hastəm.", "az": "Bu gün şənbədir; mən bu gün universitetdəyəm."},
            ],
        },
        {
            "title_az": "Keçmiş zaman feli «بودم؛ بودی؛ بود؛ ...» (idim, idin, idi...)",
            "title_fa": "فعل گذشته‌ی «بودم؛ بودی؛ بود؛ ...»",
            "conjugations": [
                {"pronoun_fa": "من", "form_fa": "هستم (امروز) → بودم (دیروز)"},
                {"pronoun_fa": "تو", "form_fa": "هستی → بودی"},
                {"pronoun_fa": "او", "form_fa": "هست (است) → بود"},
                {"pronoun_fa": "ما", "form_fa": "هستیم → بودیم"},
                {"pronoun_fa": "شما", "form_fa": "هستید → بودید"},
                {"pronoun_fa": "آن‌ها", "form_fa": "هستند → بودند"},
            ],
            "examples": [
                {"fa": "من فردا در خانه هستم. من دیروز در دانش‌گاه بودم.", "reading_az": "Mən fərda dər xane hastəm. Mən diruz dər daneşgah budəm.", "az": "Mən sabah evdəyəm. Mən dünən universitetdə idim."},
                {"fa": "دیروز جمعه بود؛ من دیروز درخانه بودم.", "reading_az": "Diruz come bud; mən diruz dər xane budəm.", "az": "Dünən cümə idi; mən dünən evdə idim."},
                {"fa": "امروز شنبه است؛ من امروز در دانش‌گاه هستم.", "reading_az": "Emruz şənbe əst; mən emruz dər daneşgah hastəm.", "az": "Bu gün şənbədir; mən bu gün universitetdəyəm."},
                {"fa": "ما دیروز و پریروز در خانه نبودیم؛ ما این دو روز در خانه‌ی پدربزرگمان بودیم.", "reading_az": "Ma diruz va pəriruz dər xane nəbudim; ma in do ruz dər xaneye pedərbozorgeman budim.", "az": "Biz dünən və srağagün evdə deyildik; bu iki gün babamızın evində idik."},
                {"fa": "مادربزرگم امروز در خانه‌ی عمویم است. او دیروز در خانه‌ی ما بود.", "reading_az": "Madərbozorgəm emruz dər xaneye əmuyəm əst. U diruz dər xaneye ma bud.", "az": "Nənəm bu gün əmimin evindədir. O, dünən bizim evimizdə idi."},
                {"fa": "عبّاس امروز به تهران می‌رود یا فردا؟ او امروز نمی‌رود؛ فردا یا پس‌فردا به تهران می‌رود.", "reading_az": "Əbbas emruz be Tehran mirəvəd ya fərda? U emruz nemirəvəd; fərda ya pəsfərda be Tehran mirəvəd.", "az": "Abbas bu gün Tehrana gedir, yoxsa sabah? O bu gün getmir; sabah və ya birigün Tehrana gedir."},
                {"fa": "دوستت دیروز اینجا بود، الآن کجاست؟ او الآن در کتاب‌خانه است.", "reading_az": "Dustet diruz inja bud, əlan kocast? U əlan dər ketabxane əst.", "az": "Dostun dünən burada idi, indi haradadır? O indi kitabxanadadır."},
                {"fa": "دیروز چندشنبه بود؟ دیروز یک‌شنبه بود.", "reading_az": "Diruz çənd şənbe bud? Diruz yekşənbe bud.", "az": "Dünən həftənin hansı günü idi? Dünən bazar günü idi."},
            ],
        },
    ],
    "exercises": [
        {
            "kind": "fill_blank",
            "instruction_az": "«بود؛ نبود؛ هستم؛ بودم» ilə tamamlayın.",
            "word_bank": ["بود", "هستید", "بودند", "بودیم", "نبودیم", "است"],
            "items": [
                {
                    "fa_with_blank": "دیروز جمعه ___ ؛ من دیروز در خانه بودم.",
                    "correct_answer": "بود",
                    "reading_az": "bud",
                    "az": "idi",
                    "full_reading_az": "Diruz come bud; mən diruz dər xane budəm.",
                    "full_translation_az": "Dünən cümə idi; mən dünən evdə idim.",
                },
                {
                    "fa_with_blank": "امروز شنبه ___ ؛ من امروز در دانش‌گاه ___ .",
                    "correct_answer": "است",
                    "reading_az": "əst",
                    "az": "-dir",
                    "full_reading_az": "Emruz şənbe əst; mən emruz dər daneşgah hastəm.",
                    "full_translation_az": "Bu gün şənbədir; mən bu gün universitetdəyəm.",
                },
                {
                    "fa_with_blank": "ما دیروز و پریروز در خانه ___ ؛ ما در خانه‌ی پدربزرگمان بودیم.",
                    "correct_answer": "نبودیم",
                    "reading_az": "nəbudim",
                    "az": "deyildik",
                    "full_reading_az": "Ma diruz va pəriruz dər xane nəbudim; ma dər xaneye pedərbozorgeman budim.",
                    "full_translation_az": "Biz dünən və srağagün evdə deyildik; biz babamızın evində idik.",
                },
                {
                    "fa_with_blank": "ما دیروز درخانه‌ی پدربزرگمان ___ .",
                    "correct_answer": "بودیم",
                    "reading_az": "budim",
                    "az": "idik",
                    "full_reading_az": "Ma diruz dər xaneye pedərbozorgeman budim.",
                    "full_translation_az": "Biz dünən babamızın evində idik.",
                },
                {
                    "fa_with_blank": "شما الآن کجا ___ ؟ ما الآن در کلاس هستیم.",
                    "correct_answer": "هستید",
                    "reading_az": "hastid",
                    "az": "-siniz",
                    "full_reading_az": "Şoma əlan koca hastid? Ma əlan dər kelas hastim.",
                    "full_translation_az": "Siz indi haradasınız? Biz indi sinifdəyik.",
                },
                {
                    "fa_with_blank": "دوستانت پریروز اینجا ___ ؟ بله، دوستانم پریروز اینجا بودند.",
                    "correct_answer": "بودند",
                    "reading_az": "budənd",
                    "az": "idilər",
                    "full_reading_az": "Dustanet pəriruz inja budənd? Bəle, dustanəm pəriruz inja budənd.",
                    "full_translation_az": "Dostların srağagün burada idilərmi? Bəli, dostlarım srağagün burada idilər.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "«برای + məsdər» quruluşu ilə cümlə düzəldin: «او / لباس دوختن / خیّاطی → او برای لباس دوختن به خیّاطی می‌رود.»",
            "items": [
                {"prompt_fa": "ما / درس خواندن / حوزه‌ی علمیّه", "answer_fa": "ما برای درس خواندن به حوزه‌ی علمیّه می‌رویم.", "reading_az": "Ma bəraye dərs xandən be houzeye elmiyye mirəvim.", "az": "Biz dərs oxumaq üçün elmi hövzəyə gedirik."},
                {"prompt_fa": "دانش‌جوها / مطالعه‌کردن / کتاب‌خانه", "answer_fa": "دانش‌جوها برای مطالعه‌کردن به کتاب‌خانه می‌روند.", "reading_az": "Daneşcuha bəraye motaleə kərdən be ketabxane mirəvənd.", "az": "Tələbələr mütaliə etmək üçün kitabxanaya gedirlər."},
                {"prompt_fa": "خواهرم / دیدن فیلم / سینما", "answer_fa": "خواهرم برای دیدن فیلم به سینما می‌رود.", "reading_az": "Xahərəm bəraye didəne film be sinəma mirəvəd.", "az": "Bacım film görmək üçün kinoteatra gedir."},
                {"prompt_fa": "من و دوستم / خریدنِ نان / نانوایی", "answer_fa": "من و دوستم برای خریدنِ نان به نانوایی می‌رویم.", "reading_az": "Mən va dustəm bəraye xəridəne nan be nanvayi mirəvim.", "az": "Mən və dostum çörək almaq üçün çörəkxanaya gedirik."},
                {"prompt_fa": "پدرم / تعمیرکردنِ ماشین / تعمیرگاه", "answer_fa": "پدرم برای تعمیرکردنِ ماشین به تعمیرگاه می‌رود.", "reading_az": "Pedərəm bəraye təmir kərdəne maşin be təmirgah mirəvəd.", "az": "Atam maşını təmir etmək üçün təmir emalatxanasına gedir."},
                {"prompt_fa": "او / گرفتنِ عکس / عکّاسی", "answer_fa": "او برای گرفتنِ عکس به عکّاسی می‌رود.", "reading_az": "U bəraye gereftəne əks be əkkasi mirəvəd.", "az": "O, şəkil çəkdirmək üçün fotoateljeyə gedir."},
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "«یکی از» ilə cümlə qurun: «ما / کتاب‌های فارسی / خواندن → ما یکی از کتاب‌های فارسی را می‌خوانیم.»",
            "items": [
                {"prompt_fa": "فرزندم / سیب‌ها / خوردن", "answer_fa": "فرزندم یکی از سیب‌ها را می‌خورد.", "reading_az": "Fərzəndəm yeki əz sibha ra mixorəd.", "az": "Övladım almalardan birini yeyir."},
                {"prompt_fa": "احمد / پنجره‌ها / بازکردن", "answer_fa": "احمد یکی از پنجره‌ها را باز می‌کند.", "reading_az": "Əhməd yeki əz pəncereha ra baz mikonəd.", "az": "Əhməd pəncərələrdən birini açır."},
                {"prompt_fa": "مریم / کتاب‌ها / هدیه‌دادن", "answer_fa": "مریم یکی از کتاب‌ها را هدیه می‌دهد.", "reading_az": "Məryəm yeki əz ketabha ra hedye midəhəd.", "az": "Məryəm kitablardan birini hədiyyə edir."},
                {"prompt_fa": "ما / کتاب‌فروشی‌ها / رفتن", "answer_fa": "ما به یکی از کتاب‌فروشی‌ها می‌رویم.", "reading_az": "Ma be yeki əz ketabforuşiha mirəvim.", "az": "Biz kitab mağazalarından birinə gedirik."},
                {"prompt_fa": "من / پیراهن سفید / پوشیدن", "answer_fa": "من یکی از پیراهن‌های سفید را می‌پوشم.", "reading_az": "Mən yeki əz pirahənhaye səfid ra mipuşəm.", "az": "Mən ağ köynəklərdən birini geyinirəm."},
                {"prompt_fa": "پدرم / فرودگاه‌ها / کارکردن", "answer_fa": "پدرم در یکی از فرودگاه‌ها کار می‌کند.", "reading_az": "Pedərəm dər yeki əz forudgahha kar mikonəd.", "az": "Atam hava limanlarından birində işləyir."},
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi əvəz edin: «مردم برای خرید گُل به گُل‌فروشی می‌روند.»",
            "items": [
                {"prompt_fa": "دانش‌جوها / خریدنِ کتاب / کتاب‌فروشی", "answer_fa": "دانش‌جوها برای خریدن کتاب به کتاب‌فروشی می‌روند.", "reading_az": "Daneşcuha bəraye xəridəne ketab be ketabforuşi mirəvənd.", "az": "Tələbələr kitab almaq üçün kitab mağazasına gedirlər."},
                {"prompt_fa": "دانش‌آموزان / دیدنِ حیوان‌ها / باغ وحش", "answer_fa": "دانش‌آموزان برای دیدنِ حیوان‌ها به باغ وحش می‌روند.", "reading_az": "Daneşamuzan bəraye didəne heyvanha be bağe vəhş mirəvənd.", "az": "Şagirdlər heyvanları görmək üçün zooparka gedirlər."},
                {"prompt_fa": "پدر و مادرم / زیارت‌کردنِ حرم امام رضا / مشهد", "answer_fa": "پدر و مادرم برای زیارت‌کردنِ حرم امام رضا به مشهد می‌روند.", "reading_az": "Pedər va madərəm bəraye ziyarət kərdəne hərəme Emam Reza be Məşhəd mirəvənd.", "az": "Ata-anam İmam Rzanın hərəmini ziyarət etmək üçün Məşhədə gedirlər."},
                {"prompt_fa": "من / گرفتنِ پول / بانک", "answer_fa": "من برای گرفتنِ پول به بانک می‌روم.", "reading_az": "Mən bəraye gereftəne pul be bank mirəvəm.", "az": "Mən pul almaq üçün banka gedirəm."},
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Vaxt zərfləri ilə cavab verin.",
            "items": [
                {"prompt_fa": "امروز چهارشنبه است. دیروز چند شنبه بود؟", "answer_fa": "دیروز سه‌شنبه بود.", "reading_az": "Diruz seşənbe bud.", "az": "Dünən çərşənbə axşamı idi."},
                {"prompt_fa": "امروز چهارشنبه است. فردا چند شنبه است؟", "answer_fa": "فردا پنج‌شنبه است.", "reading_az": "Fərda pəncşənbe əst.", "az": "Sabah cümə axşamıdır."},
                {"prompt_fa": "امروز چهارشنبه است. پس‌فردا چند شنبه است؟", "answer_fa": "پس‌فردا جمعه است.", "reading_az": "Pəsfərda come əst.", "az": "Birigün cümədir."},
                {"prompt_fa": "امروز چهارشنبه است. پریروز چند شنبه بود؟", "answer_fa": "پریروز دوشنبه بود.", "reading_az": "Pəriruz doşənbe bud.", "az": "Srağagün bazar ertəsi idi."},
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "«چند شنبه» ilə soruşub cavab verin: «شما چند شنبه به استخر می‌روید؟ ما یک‌شنبه و پنج‌شنبه به استخر می‌رویم.»",
            "items": [
                {"prompt_fa": "دوستانتان / برگشتن به کشورشان / یک‌شنبه", "answer_fa": "دوستانتان چند شنبه به کشورشان برمی‌گردند؟ آن‌ها یک‌شنبه برمی‌گردند.", "reading_az": "Dustanetan çənd şənbe be kəşvəreşan bərmigərdənd? Anha yekşənbe bərmigərdənd.", "az": "Dostlarınız həftənin hansı günü öz ölkələrinə qayıdırlar? Onlar bazar günü qayıdırlar."},
                {"prompt_fa": "شما / تمیزکردنِ اتاق / پنج‌شنبه", "answer_fa": "شما چند شنبه اتاقتان را تمیز می‌کنید؟ ما پنج‌شنبه اتاقمان را تمیز می‌کنیم.", "reading_az": "Şoma çənd şənbe otaqetan ra təmiz mikonid? Ma pəncşənbe otaqeman ra təmiz mikonim.", "az": "Siz otağınızı həftənin hansı günü təmizləyirsiniz? Biz cümə axşamı təmizləyirik."},
                {"prompt_fa": "دانش‌گاه شما / تعطیل بودن / جمعه", "answer_fa": "دانش‌گاه شما چند شنبه تعطیل است؟ دانش‌گاه ما جمعه تعطیل است.", "reading_az": "Daneşgahe şoma çənd şənbe tətil əst? Daneşgahe ma come tətil əst.", "az": "Sizin universitetiniz həftənin hansı günü bağlıdır? Bizim universitetimiz cümə günü bağlıdır."},
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi cümlə qurun: «من ساعت هفت به مدرسه می‌روم و ساعت دوازده به خانه برمی‌گردم.»",
            "items": [
                {"prompt_fa": "کارمندها / ساعت هفت / اداره / سه", "answer_fa": "کارمندها ساعت هفت به اداره می‌روند و ساعت سه به خانه برمی‌گردند.", "reading_az": "Karməndha saəte həft be edare mirəvənd va saəte se be xane bərmigərdənd.", "az": "Əməkdaşlar saat yeddidə idarəyə gedirlər və saat üçdə evə qayıdırlar."},
                {"prompt_fa": "علی / ساعت ده / آرایش‌گاه / یک ساعت بعد", "answer_fa": "علی ساعت ده به آرایش‌گاه می‌رود و یک ساعت بعد به خانه برمی‌گردد.", "reading_az": "Əli saəte dəh be arayeşgah mirəvəd va yek saət bəd be xane bərmigərdəd.", "az": "Əli saat onda bərbərxanaya gedir və bir saat sonra evə qayıdır."},
                {"prompt_fa": "ما / فردا / کشورمان / ده روز بعد", "answer_fa": "ما فردا به کشورمان می‌رویم و ده روز بعد برمی‌گردیم.", "reading_az": "Ma fərda be kəşvəreman mirəvim va dəh ruz bəd bərmigərdim.", "az": "Biz sabah öz ölkəmizə gedirik və on gün sonra qayıdırıq."},
                {"prompt_fa": "آن کارگران / صبح / کارخانه / شب", "answer_fa": "آن کارگران صبح به کارخانه می‌روند و شب به خانه برمی‌گردند.", "reading_az": "An kargəran sobh be karxane mirəvənd va şəb be xane bərmigərdənd.", "az": "O fəhlələr səhər zavoda gedirlər və axşam evə qayıdırlar."},
            ],
        },
    ],
    "sentence_practice": {
        "listen_exercises": [
            {
                "items": [
                    {"fa": "در حوزه‌ی علمیّه‌ی قم، حدود سی‌هزار طلبه درس می‌خوانند.", "reading_az": "Dər houzeye elmiyyeye Qom, hodude si hezar tələbe dərs mixanənd.", "az": "Qumun elmi hövzəsində təxminən otuz min tələbə oxuyur."},
                    {"fa": "کنار دریای خزر، یک کارخانه‌ی بزرگ هست. در آن کارخانه، کشتی و قایق می‌سازند.", "reading_az": "Kənare dəryaye Xəzər, yek karxaneye bozorg həst. Dər an karxane, keşti va qayeq misazənd.", "az": "Xəzər dənizinin kənarında böyük bir zavod var. O zavodda gəmi və qayıq düzəldirlər."},
                    {"fa": "پدرم گاهی من و برادرم را برای دیدن حیوان‌ها به باغ وحش می‌برد.", "reading_az": "Pedərəm gahi mən va bəradərəm ra bəraye didəne heyvanha be bağe vəhş mibərəd.", "az": "Atam bəzən məni və qardaşımı heyvanları görmək üçün zooparka aparır."},
                    {"fa": "کشور پاکستان، نزدیک ایران است و کشور کانادا از ایران دور است.", "reading_az": "Kəşvəre Pakestan, nəzdike Iran əst va kəşvəre Kanada əz Iran dur əst.", "az": "Pakistan İrana yaxındır, Kanada isə İrandan uzaqdır."},
                    {"fa": "ما برای زیارت خانه‌ی خدا به مکّه می‌رویم و ده روز در آن‌جا می‌مانیم.", "reading_az": "Ma bəraye ziyarəte xaneye Xoda be Məkke mirəvim va dəh ruz dər anja mimanim.", "az": "Biz Allahın evini ziyarət etmək üçün Məkkəyə gedirik və orada on gün qalırıq."},
                    {"fa": "من ساعت چهار به کتاب‌خانه می‌روم؛ سه ساعت در آن‌جا می‌مانم و ساعت هفت به خانه برمی‌گردم.", "reading_az": "Mən saəte çəhar be ketabxane mirəvəm; se saət dər anja mimanəm va saəte həft be xane bərmigərdəm.", "az": "Mən saat dörddə kitabxanaya gedirəm; orada üç saat qalıram və saat yeddidə evə qayıdıram."},
                    {"fa": "سلیمان تعمیرکار لباس‌شویی است. او هر روز صبح، تعمیرگاهش را باز می‌کند و شب می‌بندد.", "reading_az": "Solyeman təmirkare lebasşuyi əst. U hər ruz sobh, təmirgahəş ra baz mikonəd va şəb mibəndəd.", "az": "Süleyman paltaryuyan təmirçisidir. O, hər gün səhər təmirxanasını açır və axşam bağlayır."},
                    {"fa": "نزدیک خانه‌ی ما بوستان، کتاب‌فروشی، خیّاطی، عکّاسی، آرایش‌گاه و نانوایی هست.", "reading_az": "Nəzdike xaneye ma bustan, ketabforuşi, xəyyati, əkkasi, arayeşgah va nanvayi həst.", "az": "Evimizin yaxınlığında park, kitab mağazası, dərzixana, fotoatelye, bərbərxana və çörəkxana var."},
                    {"fa": "ماهی‌ها از آب خارج زندگی می‌کنند یا داخل آب؟ ماهی‌ها داخل آب زندگی می‌کنند.", "reading_az": "Mahiha əz ab xarec zendegi mikonənd ya daxele ab? Mahiha daxele ab zendegi mikonənd.", "az": "Balıqlar suyun bayırında yaşayır, yoxsa içində? Balıqlar suyun içində yaşayır."},
                    {"fa": "عمویم نمایش‌گاه ماشین دارد. او در نمایش‌گاهش ماشین‌های مختلف می‌فروشد.", "reading_az": "Əmuyəm nəmayeşgahe maşin darəd. U dər nəmayeşgaheş maşinhaye moxtəlef mifəruşəd.", "az": "Əmimin avtomobil sərgisi var. O, sərgisində müxtəlif avtomobillər satır."},
                    {"fa": "من و دوستانم امروز برای دیدن فیلم حضرت مریم (س) به سینما می‌رویم.", "reading_az": "Mən va dustanəm emruz bəraye didəne filme Həzrəte Məryəm be sinəma mirəvim.", "az": "Mən və dostlarım bu gün Həzrət Məryəm filminə baxmaq üçün kinoteatra gedirik."},
                    {"fa": "پدر من قاضی است و در دادگاه کار می‌کند.", "reading_az": "Pedəre mən qazi əst va dər dadgah kar mikonəd.", "az": "Atam hakimdir və məhkəmədə işləyir."},
                ],
            },
        ],
        "answer_items": [
            {"fa": "امروز چند شنبه است؟", "reading_az": "Emruz çənd şənbe əst?", "az": "Bu gün həftənin hansı günüdür?"},
            {
                "fa": "شما چند شنبه‌ها به استخر می‌روید؟",
                "reading_az": "Şoma çənd şənbeha be estəxr mirəvid?",
                "az": "Siz həftənin hansı günləri hovuza gedirsiniz?",
                "sample_answer_fa": "ما روزهای یک‌شنبه و پنج‌شنبه به استخر می‌رویم.",
                "sample_answer_reading_az": "Ma ruzhaye yekşənbe va pəncşənbe be estəxr mirəvim.",
                "sample_answer_az": "Biz bazar və cümə axşamı günləri hovuza gedirik.",
            },
            {
                "fa": "شما چند شنبه اتاق‌تان را تمیز می‌کنید؟",
                "reading_az": "Şoma çənd şənbe otaqetan ra təmiz mikonid?",
                "az": "Siz otağınızı həftənin hansı günü təmizləyirsiniz?",
                "sample_answer_fa": "ما روزهای پنج‌شنبه اتاقمان را تمیز می‌کنیم.",
                "sample_answer_reading_az": "Ma ruzhaye pəncşənbe otaqeman ra təmiz mikonim.",
                "sample_answer_az": "Biz cümə axşamı günləri otağımızı təmizləyirik.",
            },
            {
                "fa": "دوستانتان چند شنبه به کشورشان برمی‌گردند؟",
                "reading_az": "Dustanetan çənd şənbe be kəşvəreşan bərmigərdənd?",
                "az": "Dostlarınız həftənin hansı günü öz ölkələrinə qayıdırlar?",
                "sample_answer_fa": "دوستانم شنبه یا یک‌شنبه به کشورشان برمی‌گردند.",
                "sample_answer_reading_az": "Dustanəm şənbe ya yekşənbe be kəşvəreşan bərmigərdənd.",
                "sample_answer_az": "Dostlarım şənbə və ya bazar günü öz ölkələrinə qayıdırlar.",
            },
            {
                "fa": "چند شنبه‌ها دانش‌گاه تعطیل است؟",
                "reading_az": "Çənd şənbeha daneşgah tətil əst?",
                "az": "Universitet həftənin hansı günü bağlıdır?",
                "sample_answer_fa": "دانش‌گاه‌ها روزهای جمعه تعطیل هستند.",
                "sample_answer_reading_az": "Daneşgahha ruzhaye come tətil həstənd.",
                "sample_answer_az": "Universitetlər cümə günləri bağlıdır.",
            },
        ],
    },
    "reading_text": {
        "title_fa": "گل‌فروشی",
        "title_az": "Gülçülük dükanı",
        "paragraphs_fa": [
            "نزدیک خانه‌ی ما یک گل‌فروشی بزرگ است. در آن گل‌فروشی، گل‌های زیبا و رنگارنگ وجود دارد. مردم زیادی هر روز به این گل‌فروشی می‌آیند و گل‌های گوناگون، مانندِ رُز، یاس، لاله، نرگس، شقایق و... انتخاب می‌کنند و می‌خرند.",
            "آن‌ها علاوه بر خریدن گل برای خانه‌هایشان، به مناسبت‌های مختلف، مانندِ روزِ مادر، روز پدر، جشن تولّد و ازدواج یک شاخه یا یک دسته گل زیبا می‌خرند و هدیه می‌دهند.",
            "در جهان، صدها گل با رنگ‌های زیبا و اسم‌های گوناگون وجود دارد. یکی از گل‌های زیبا و خوش‌بو در ایران، گل‌محمّدی است.",
            "از گل محمّدی، گُلاب و عطر درست می‌کنند. مردم از عطر برای خوش‌بو کردن بدن و لباس‌هایشان و از گلاب برای خوش‌بو کردن غذا، بستنی و شیرینی‌ها استفاده می‌کنند.",
            "خوش‌بوترین گلاب ایران، گلاب قمصرِ کاشان است که هر سال با این گلاب، خانه‌ی کعبه را می‌شویند.",
        ],
        "footnotes": [
            {"fa": "مناسبت", "az": "münasibət"},
            {"fa": "جشن تولّد", "az": "ad günü"},
            {"fa": "دسته گل / شاخه", "az": "gül dəstəsi / sap"},
            {"fa": "خوش‌بو", "az": "ətirli"},
            {"fa": "یکی از", "az": "…lərdən biri"},
        ],
        "full_translation_az": (
            "Evimizin yaxınlığında böyük bir gülçülük dükanı var. O gülçülük dükanında gözəl və rəngbərəng güllər "
            "var. Hər gün çoxlu insan bu dükana gəlir və rəngbərəng gülləri, məsələn qızılgül, yasəmən, lalə, "
            "nərgiz, şəqayiq və s. seçib alır.\n\n"
            "Onlar evləri üçün gül almaqdan əlavə, ana günü, ata günü, ad günü və toy kimi müxtəlif münasibətlərdə "
            "bir sap və ya bir dəstə gözəl gül alıb hədiyyə edirlər.\n\n"
            "Dünyada gözəl rəngli və müxtəlif adlı yüzlərlə gül var. İranda gözəl və ətirli güllərdən biri "
            "Məhəmmədi gülüdür.\n\n"
            "Məhəmmədi gülündən gülab və ətir hazırlanır. İnsanlar ətirdən bədən və paltarlarını ətirləndirmək "
            "üçün, gülabdan isə yemək, dondurma və şirniyyatları ətirləndirmək üçün istifadə edirlər.\n\n"
            "İranın ən ətirli gülabı Kaşan şəhərinin Qəmsər gülabıdır ki, hər il bu gülabla Kəbənin evi yuyulur."
        ),
        "sentences": [
            {
                "fa": "نزدیک خانه‌ی ما یک گل‌فروشی بزرگ است.",
                "reading_az": "Nəzdike xaneye ma yek golforuşiye bozorg əst.",
                "az": "Evimizin yaxınlığında böyük bir gülçülük dükanı var.",
                "new_paragraph": True,
            },
            {
                "fa": "در آن گل‌فروشی، گل‌های زیبا و رنگارنگ وجود دارد.",
                "reading_az": "Dər an golforuşi, golhaye ziba va rəngarəng vocud darəd.",
                "az": "O gülçülük dükanında gözəl və rəngbərəng güllər var.",
            },
            {
                "fa": "مردم زیادی هر روز به این گل‌فروشی می‌آیند و گل‌های گوناگون، مانندِ رُز، یاس، لاله، نرگس، شقایق و... انتخاب می‌کنند و می‌خرند.",
                "reading_az": "Mərdome ziyadi hər ruz be in golforuşi miayənd va golhaye gunagun, manənde roz, yas, lale, nərges, şəqayeq va... entexab mikonənd va mixərənd.",
                "az": "Hər gün çoxlu insan bu dükana gəlir və rəngbərəng gülləri, məsələn qızılgül, yasəmən, lalə, nərgiz, şəqayiq və s. seçib alır.",
            },
            {
                "fa": "آن‌ها علاوه بر خریدن گل برای خانه‌هایشان، به مناسبت‌های مختلف، مانندِ روزِ مادر، روز پدر، جشن تولّد و ازدواج یک شاخه یا یک دسته گل زیبا می‌خرند و هدیه می‌دهند.",
                "reading_az": "Anha əlave bər xəridəne gol bəraye xanehayeşan, be monasebathaye moxtəlef, manənde ruze madər, ruze pedər, cəşne touləd va ezdevac yek şaxe ya yek dəste gole ziba mixərənd va hedye midəhənd.",
                "az": "Onlar evləri üçün gül almaqdan əlavə, ana günü, ata günü, ad günü və toy kimi müxtəlif münasibətlərdə bir sap və ya bir dəstə gözəl gül alıb hədiyyə edirlər.",
                "new_paragraph": True,
            },
            {
                "fa": "در جهان، صدها گل با رنگ‌های زیبا و اسم‌های گوناگون وجود دارد.",
                "reading_az": "Dər cəhan, sədha gol ba rənghaye ziba va esmhaye gunagun vocud darəd.",
                "az": "Dünyada gözəl rəngli və müxtəlif adlı yüzlərlə gül var.",
                "new_paragraph": True,
            },
            {
                "fa": "یکی از گل‌های زیبا و خوش‌بو در ایران، گل‌محمّدی است.",
                "reading_az": "Yeki əz golhaye ziba va xoşbu dər Iran, golmohəmmədi əst.",
                "az": "İranda gözəl və ətirli güllərdən biri Məhəmmədi gülüdür.",
            },
            {
                "fa": "از گل محمّدی، گُلاب و عطر درست می‌کنند.",
                "reading_az": "Əz gole mohəmmədi, golab va ətr dorost mikonənd.",
                "az": "Məhəmmədi gülündən gülab və ətir hazırlanır.",
                "new_paragraph": True,
            },
            {
                "fa": "مردم از عطر برای خوش‌بو کردن بدن و لباس‌هایشان و از گلاب برای خوش‌بو کردن غذا، بستنی و شیرینی‌ها استفاده می‌کنند.",
                "reading_az": "Mərdom əz ətr bəraye xoşbu kərdəne bədən va lebashayeşan va əz golab bəraye xoşbu kərdəne qəza, bəstəni va şirinihal estefade mikonənd.",
                "az": "İnsanlar ətirdən bədən və paltarlarını ətirləndirmək üçün, gülabdan isə yemək, dondurma və şirniyyatları ətirləndirmək üçün istifadə edirlər.",
            },
            {
                "fa": "خوش‌بوترین گلاب ایران، گلاب قمصرِ کاشان است که هر سال با این گلاب، خانه‌ی کعبه را می‌شویند.",
                "reading_az": "Xoşbutərine golabe Iran, golabe Qəmsəre Kaşan əst ke hər sal ba in golab, xaneye Kəbe ra mişuyənd.",
                "az": "İranın ən ətirli gülabı Kaşan şəhərinin Qəmsər gülabıdır ki, hər il bu gülabla Kəbənin evi yuyulur.",
                "new_paragraph": True,
            },
        ],
        "comprehension_questions": [
            {
                "question_fa": "مردم به چه مناسبت‌هایی گل می‌خرند؟",
                "reading_az": "Mərdom be çe monasebathayi gol mixərənd?",
                "az": "İnsanlar hansı münasibətlərdə gül alırlar?",
                "sample_answer_fa": "مردم به مناسبت‌های مختلف، مانندِ روزِ مادر، روز پدر، جشن تولّد و ازدواج گل می‌خرند.",
                "sample_answer_reading_az": "Mərdom be monasebathaye moxtəlef, manənde ruze madər, ruze pedər, cəşne touləd va ezdevac gol mixərənd.",
                "sample_answer_az": "İnsanlar ana günü, ata günü, ad günü və toy kimi müxtəlif münasibətlərdə gül alırlar.",
            },
            {
                "question_fa": "از کدام گُل، گلاب درست می‌کنند؟",
                "reading_az": "Əz kodam gol, golab dorost mikonənd?",
                "az": "Hansı güldən gülab hazırlanır?",
                "sample_answer_fa": "از گل محمّدی، گلاب درست می‌کنند.",
                "sample_answer_reading_az": "Əz gole mohəmmədi, golab dorost mikonənd.",
                "sample_answer_az": "Məhəmmədi gülündən gülab hazırlanır.",
            },
            {
                "question_fa": "هر سال با کدام گلاب خانه‌ی کعبه را می‌شویند؟",
                "reading_az": "Hər sal ba kodam golab xaneye Kəbe ra mişuyənd?",
                "az": "Hər il Kəbənin evi hansı gülabla yuyulur?",
                "sample_answer_fa": "هر سال با گلاب قمصرِ کاشان، خانه‌ی کعبه را می‌شویند.",
                "sample_answer_reading_az": "Hər sal ba golabe Qəmsəre Kaşan, xaneye Kəbe ra mişuyənd.",
                "sample_answer_az": "Hər il Kaşanın Qəmsər gülabı ilə Kəbənin evi yuyulur.",
            },
            {
                "question_fa": "مردم از عطر و گلاب برای چه کارهایی استفاده می‌کنند؟",
                "reading_az": "Mərdom əz ətr va golab bəraye çe karhayi estefade mikonənd?",
                "az": "İnsanlar ətir və gülabdan hansı işlər üçün istifadə edirlər?",
                "sample_answer_fa": "مردم از عطر برای خوش‌بو کردن بدن و لباس‌هایشان و از گلاب برای خوش‌بو کردن غذا، بستنی و شیرینی‌ها استفاده می‌کنند.",
                "sample_answer_reading_az": "Mərdom əz ətr bəraye xoşbu kərdəne bədən va lebashayeşan va əz golab bəraye xoşbu kərdəne qəza, bəstəni va şirinihal estefade mikonənd.",
                "sample_answer_az": "İnsanlar ətirdən bədən və paltarlarını, gülabdan isə yemək, dondurma və şirniyyatları ətirləndirmək üçün istifadə edirlər.",
            },
            {
                "question_fa": "در کشور شما چه گل‌هایی وجود دارد؟",
                "reading_az": "Dər kəşvəre şoma çe golhayi vocud darəd?",
                "az": "Sizin ölkənizdə hansı güllər var?",
            },
            {
                "question_fa": "شما کدام گل را بیشتر دوست دارید؟",
                "reading_az": "Şoma kodam gol ra bişttər dust darid?",
                "az": "Siz hansı gülü daha çox sevirsiniz?",
            },
            {
                "question_fa": "در جشن ازدواج یا تولّد دوستانتان چه چیزهایی هدیه می‌دهید؟",
                "reading_az": "Dər cəşne ezdevac ya touləde dustanetan çe çizhayi hedye midəhid?",
                "az": "Dostlarınızın toy və ya ad günündə nə hədiyyə edirsiniz?",
            },
        ],
    },
}
