# Dərs 4 — شغل ۱ (Peşə 1)
# Mənbə: کتاب دوم, səh. 51-62

LESSON = {
    "number": 4,
    "title_fa": "شغل ۱",
    "title_az": "Peşə 1",
    "available": True,
    "vocabulary": [
        {"fa": "رئیس‌جمهور", "reading": "rəis-comhur", "az": "Prezident"},
        {"fa": "پادشاه (شاه)", "reading": "padeşah (şah)", "az": "Padşah (şah)"},
        {"fa": "مدیر", "reading": "modir", "az": "Müdir (direktor)"},
        {"fa": "معلّم (استاد)", "reading": "moəllem (ostad)", "az": "Müəllim"},
        {"fa": "دانش‌آموز", "reading": "daneşamuz", "az": "Şagird"},
        {"fa": "دانش‌جو", "reading": "daneşcu", "az": "Tələbə"},
        {"fa": "پزشک (دکتر)", "reading": "pezeşk (doktor)", "az": "Həkim"},
        {"fa": "دندان‌پزشک", "reading": "dəndanpezeşk", "az": "Diş həkimi"},
        {"fa": "مهندس", "reading": "mohəndes", "az": "Mühəndis"},
        {"fa": "بنّا", "reading": "bənna", "az": "Bənna"},
        {"fa": "کارگر", "reading": "kargər", "az": "Fəhlə"},
        {"fa": "آهنگر", "reading": "ahəngər", "az": "Dəmirçi"},
        {"fa": "نجّار", "reading": "nəccar", "az": "Dülgər"},
        {"fa": "خیّاط", "reading": "xəyyat", "az": "Dərzi"},
        {"fa": "کفّاش", "reading": "kəffaş", "az": "Çəkməçi"},
        {"fa": "عکّاس", "reading": "əkkas", "az": "Fotoqraf"},
        {"fa": "قصّاب", "reading": "qəssab", "az": "Qəssab"},
        {"fa": "معاینه می‌کند", "reading": "moayene mikonəd", "az": "müayinə edir"},
        {"fa": "نسخه می‌نویسد", "reading": "nosxe minevisəd", "az": "resept yazır"},
        {"fa": "می‌سازد", "reading": "misazəd", "az": "tikir, düzəldir"},
        {"fa": "می‌دوزد", "reading": "miduzəd", "az": "tikir (paltar)"},
        {"fa": "درس می‌دهد", "reading": "dərs midəhəd", "az": "dərs deyir"},
        {"fa": "کار می‌کند", "reading": "kar mikonəd", "az": "işləyir"},
        {"fa": "گاهی", "reading": "gahi", "az": "bəzən"},
        {"fa": "امّا", "reading": "əmma", "az": "amma"},
        {"fa": "بیمارستان", "reading": "bimarestan", "az": "Xəstəxana"},
        {"fa": "بازنشسته", "reading": "bazneşəste", "az": "Təqaüdçü"},
        {"fa": "خانه‌دار", "reading": "xanedar", "az": "Evdar"},
        {"fa": "شصت", "reading": "şəst", "az": "Altmış"},
        {"fa": "شش‌نفره", "reading": "şeş-nəfəre", "az": "Altı nəfərlik"},
    ],
    "grammar_notes": [
        {
            "title_az": "Mənfi fel «نیستم؛ نیستی؛ ...» (deyiləm, deyilsən...)",
            "title_fa": "فعل منفی «نیستم؛ نیستی؛ ...»",
            "conjugations": [
                {"pronoun_fa": "من", "form_fa": "هستم / نیستم"},
                {"pronoun_fa": "تو", "form_fa": "هستی / نیستی"},
                {"pronoun_fa": "او", "form_fa": "هست (است) / نیست"},
                {"pronoun_fa": "ما", "form_fa": "هستیم / نیستیم"},
                {"pronoun_fa": "شما", "form_fa": "هستید / نیستید"},
                {"pronoun_fa": "آن‌ها", "form_fa": "هستند / نیستند"},
            ],
            "examples": [
                {"fa": "من نجّار هستم؛ آهنگر نیستم.", "reading_az": "Mən nəccar hastəm; ahəngər nistəm.", "az": "Mən dülgərəm; dəmirçi deyiləm."},
                {"fa": "من خیّاط هستم؛ کفّاش نیستم.", "reading_az": "Mən xəyyat hastəm; kəffaş nistəm.", "az": "Mən dərziyəm; çəkməçi deyiləm."},
                {"fa": "شما (تو) معلّم هستی؛ مدیر نیستی.", "reading_az": "Şoma (to) moəllem hasti; modir nisti.", "az": "Sən müəllimsən; müdir deyilsən."},
                {"fa": "او پلیس نیست؛ قاضی است.", "reading_az": "U polis nist; qazi əst.", "az": "O, polis deyil; hakimdir."},
                {"fa": "ما دانش‌آموز نیستیم؛ دانش‌جو هستیم.", "reading_az": "Ma daneşamuz nistim; daneşcu hastim.", "az": "Biz şagird deyilik; tələbəyik."},
                {"fa": "آن‌ها کارگر هستند؛ بنّا نیستند.", "reading_az": "Anha kargər həstənd; bənna nistənd.", "az": "Onlar fəhlədirlər; bənna deyillər."},
            ],
            "drills": [
                {
                    "title_fa": "مانند مثال بپرسید و پاسخ دهید",
                    "instruction_az": "Nümunə kimi soruşun və cavab verin",
                    "example_fa": "آن‌ها / پرستار / پزشک: آیا آن‌ها پرستار هستند؟ *نه*، آن‌ها پرستار نیستند؛ پزشک هستند.",
                    "example_reading_az": "Anha / pərəstar / pezeşk: Aya anha pərəstar həstənd? Nə, anha pərəstar nistənd; pezeşk həstənd.",
                    "example_az": "Onlar / tibb bacısı / həkim: Onlar tibb bacısıdırmı? Xeyr, onlar tibb bacısı deyil; həkimdir.",
                    "items": [
                        {
                            "prompt_fa": "شما / چوپان / شکارچی",
                            "answer_fa": "آیا شما چوپان هستید؟ نه، ما چوپان نیستیم؛ شکارچی هستیم.",
                            "reading_az": "Aya şoma çupan hastid? Nə, ma çupan nistim; şekarçi hastim.",
                            "az": "Siz çobansınızmı? Xeyr, biz çoban deyilik; ovçuyuq.",
                        },
                        {
                            "prompt_fa": "مریم / خیّاط / خیّاط",
                            "answer_fa": "آیا مریم خیّاط است؟ بله، مریم خیّاط است.",
                            "reading_az": "Aya Məryəm xəyyat əst? Bəle, Məryəm xəyyat əst.",
                            "az": "Məryəm dərzidirmi? Bəli, Məryəm dərzidir.",
                        },
                        {
                            "prompt_fa": "آن‌ها / نجّار / نجّار",
                            "answer_fa": "آیا آن‌ها نجّار هستند؟ بله، آن‌ها نجّار هستند.",
                            "reading_az": "Aya anha nəccar həstənd? Bəle, anha nəccar həstənd.",
                            "az": "Onlar dülgərdirmi? Bəli, onlar dülgərdir.",
                        },
                        {
                            "prompt_fa": "این خانم / مهندس / دکتر",
                            "answer_fa": "آیا این خانم مهندس است؟ نه، او مهندس نیست؛ دکتر است.",
                            "reading_az": "Aya in xanom mohəndes əst? Nə, u mohəndes nist; doktor əst.",
                            "az": "Bu xanım mühəndisdirmi? Xeyr, o, mühəndis deyil; həkimdir.",
                        },
                        {
                            "prompt_fa": "شما / قاضی / قاضی",
                            "answer_fa": "آیا شما قاضی هستید؟ بله، من قاضی هستم.",
                            "reading_az": "Aya şoma qazi hastid? Bəle, mən qazi hastəm.",
                            "az": "Siz hakimsinizmi? Bəli, mən hakiməm.",
                        },
                        {
                            "prompt_fa": "من و علی / دانش‌آموز / دانش‌جو",
                            "answer_fa": "آیا شما دانش‌آموز هستید؟ نه، ما دانش‌آموز نیستیم؛ دانش‌جو هستیم.",
                            "reading_az": "Aya şoma daneşamuz hastid? Nə, ma daneşamuz nistim; daneşcu hastim.",
                            "az": "Siz şagirdsinizmi? Xeyr, biz şagird deyilik; tələbəyik.",
                        },
                        {
                            "prompt_fa": "نرگس و سوسن / مدیر / معلّم",
                            "answer_fa": "آیا نرگس و سوسن مدیر هستند؟ نه، آن‌ها مدیر نیستند؛ معلّم هستند.",
                            "reading_az": "Aya Nərges va Susən modir həstənd? Nə, anha modir nistənd; moəllem həstənd.",
                            "az": "Nərgiz və Susən müdirdirmi? Xeyr, onlar müdir deyil; müəllimdir.",
                        },
                        {
                            "prompt_fa": "آن آقا / رئیس‌جمهور / پادشاه",
                            "answer_fa": "آیا آن آقا رئیس‌جمهور است؟ نه، او رئیس‌جمهور نیست؛ پادشاه است.",
                            "reading_az": "Aya an ağa rəis-comhur əst? Nə, u rəis-comhur nist; padeşah əst.",
                            "az": "O kişi prezidentdirmi? Xeyr, o, prezident deyil; padşahdır.",
                        },
                    ],
                },
            ],
        },
        {
            "title_az": "Sual sözü «چه‌کاره» (nəçidir?)",
            "title_fa": "واژه‌ی پرسشی «چه‌کاره»",
            "conjugations": [],
            "examples": [
                {"fa": "او چه‌کاره است؟ = شغل او چیست؟ او مهندس رایانه است.", "reading_az": "U çekare əst? = Şoğle u çist? U mohəndese rayane əst.", "az": "O nəçidir? = Onun peşəsi nədir? O, kompüter mühəndisidir."},
                {"fa": "فاطمه خانم چه‌کاره است؟ ایشان پزشک هستند.", "reading_az": "Fateme xanom çekare əst? İşan pezeşk həstənd.", "az": "Fatimə xanım nəçidir? O (hörmətlə), həkimdir."},
                {"fa": "شغل آن آقا چیست؟ او خیّاط است.", "reading_az": "Şoğle an ağa çist? U xəyyat əst.", "az": "O kişinin peşəsi nədir? O, dərzidir."},
                {"fa": "علی و زینب چه‌کاره هستند؟ آن‌ها دانش‌جو هستند.", "reading_az": "Əli va Zeynəb çekare həstənd? Anha daneşcu həstənd.", "az": "Əli və Zeynəb nəçidirlər? Onlar tələbədirlər."},
                {"fa": "برادر من مهندس است. برادر شما چه‌کاره است؟ برادر من قاضی است.", "reading_az": "Bəradəre mən mohəndes əst. Bəradəre şoma çekare əst? Bəradəre mən qazi əst.", "az": "Mənim qardaşım mühəndisdir. Sizin qardaşınız nəçidir? Mənim qardaşım hakimdir."},
                {"fa": "خیّاط‌ها چه‌کار می‌کنند؟ خیّاط‌ها لباس می‌دوزند.", "reading_az": "Xəyyatha çekar mikonənd? Xəyyatha lebas miduzənd.", "az": "Dərzilər nə edirlər? Dərzilər paltar tikirlər."},
                {"fa": "بنّا چه‌کار می‌کند؟ بنّا خانه می‌سازد.", "reading_az": "Bənna çekar mikonəd? Bənna xane misazəd.", "az": "Bənna nə edir? Bənna ev tikir."},
                {"fa": "دندان‌پزشک چه‌کار می‌کند؟ دندان بیمارها را معاینه می‌کند.", "reading_az": "Dəndanpezeşk çekar mikonəd? Dəndane bimarha ra moayene mikonəd.", "az": "Diş həkimi nə edir? Xəstələrin dişlərini müayinə edir."},
            ],
            "drills": [
                {
                    "title_fa": "مانند مثال بپرسید و پاسخ دهید",
                    "instruction_az": "Nümunə kimi soruşun və cavab verin",
                    "example_fa": "برادرت / معلّم: برادرت چه‌کاره است؟ برادرم معلّم است. معلّم چه‌کار می‌کند؟ معلّم درس می‌دهد.",
                    "example_reading_az": "Bəradərət / moəllem: Bəradərət çekare əst? Bəradərəm moəllem əst. Moəllem çekar mikonəd? Moəllem dərs midəhəd.",
                    "example_az": "Qardaşın / müəllim: Qardaşın nəçidir? Qardaşım müəllimdir. Müəllim nə edir? Müəllim dərs deyir.",
                    "items": [
                        {
                            "prompt_fa": "شما / طلبه",
                            "answer_fa": "شما چه‌کاره هستید؟ من طلبه هستم. طلبه درس دین می‌خواند.",
                            "reading_az": "Şoma çekare hastid? Mən təllabe hastəm. Təllabe dərse din mixanəd.",
                            "az": "Siz nəçisiniz? Mən tələbəyəm. Tələbə din dərsi oxuyur.",
                        },
                        {
                            "prompt_fa": "آن‌ها / نجّار",
                            "answer_fa": "آن‌ها چه‌کاره هستند؟ آن‌ها نجّار هستند. نجّار میز و صندلی می‌سازد.",
                            "reading_az": "Anha çekare həstənd? Anha nəccar həstənd. Nəccar miz va səndəli misazəd.",
                            "az": "Onlar nəçidir? Onlar dülgərdir. Dülgər masa və stul düzəldir.",
                        },
                        {
                            "prompt_fa": "هادی / آهنگر",
                            "answer_fa": "هادی چه‌کاره است؟ هادی آهنگر است. آهنگر با آهن کار می‌کند.",
                            "reading_az": "Hadi çekare əst? Hadi ahəngər əst. Ahəngər ba ahən kar mikonəd.",
                            "az": "Hadi nəçidir? Hadi dəmirçidir. Dəmirçi dəmirlə işləyir.",
                        },
                        {
                            "prompt_fa": "دوستتان / آشپز",
                            "answer_fa": "دوستتان چه‌کاره است؟ دوستم آشپز است. آشپز غذا می‌پزد.",
                            "reading_az": "Dustetan çekare əst? Dustəm aşpəz əst. Aşpəz qəza mipəzəd.",
                            "az": "Dostunuz nəçidir? Dostum aşpazdır. Aşpaz yemək bişirir.",
                        },
                        {
                            "prompt_fa": "مادرت / خیّاط",
                            "answer_fa": "مادرت چه‌کاره است؟ مادرم خیّاط است. خیّاط لباس می‌دوزد.",
                            "reading_az": "Madərət çekare əst? Madərəm xəyyat əst. Xəyyat lebas miduzəd.",
                            "az": "Anan nəçidir? Anam dərzidir. Dərzi paltar tikir.",
                        },
                        {
                            "prompt_fa": "پدربزرگ علی / پزشک",
                            "answer_fa": "پدربزرگ علی چه‌کاره است؟ او پزشک است. پزشک بیمارها را معاینه می‌کند و نسخه می‌نویسد.",
                            "reading_az": "Pedərbozorge Əli çekare əst? U pezeşk əst. Pezeşk bimarha ra moayene mikonəd va nosxe minevisəd.",
                            "az": "Əlinin babası nəçidir? O, həkimdir. Həkim xəstələri müayinə edir və resept yazır.",
                        },
                    ],
                },
            ],
        },
        {
            "title_az": "Təşdid « ـّ » (qoşa oxunan samit)",
            "title_fa": "تشدید « ـّ »",
            "conjugations": [
                {"pronoun_fa": "می‌نویسیم:", "form_fa": "بنّا؛ کفّاش؛ عکّاس؛ قصّاب"},
                {"pronoun_fa": "می‌خوانیم:", "form_fa": "بننا؛ کففاش؛ عککاس؛ قصصاب"},
            ],
            "examples": [
                {"fa": "عکّاس؛ کفّاش؛ نجّار؛ بنّا؛ قصّاب؛ خیّاط", "reading_az": "Əkkas; kəffaş; nəccar; bənna; qəssab; xəyyat.", "az": "əkkas; kəffaş; nəccar; bənna; qəssab; xəyyat — təşdidli samit qoşa oxunur."},
                {"fa": "معلّم؛ محمّد؛ ذرّت؛ پلّه؛ ذرّه‌بین؛ زرّافه", "reading_az": "Moəllem; Mohəmməd; zorrət; pelle; zərrebin; zərrafe.", "az": "moəllem; Mohəmməd; zorrət; pelle; zərrebin; zərrafe"},
                {"fa": "مکّه؛ بچّه؛ مجلّه؛ سکّه؛ ارّه؛ غوّاص", "reading_az": "Məkkə; bəççe; məcəlle; sekke; ərre; ğəvvas.", "az": "Məkkə; bəççe; məcəlle; sekke; ərre; ğəvvas"},
                {"fa": "این آقا عکّاس است. عکّاس، دوربین دارد.", "reading_az": "İn ağa əkkas əst. Əkkas, durbin darəd.", "az": "Bu kişi fotoqrafdır. Fotoqrafın fotoaparatı var."},
                {"fa": "آن‌ها کفّاش هستند. کفّاش‌ها کفش می‌دوزند.", "reading_az": "Anha kəffaş həstənd. Kəffaşha kəfş miduzənd.", "az": "Onlar çəkməçidirlər. Çəkməçilər ayaqqabı tikirlər."},
                {"fa": "محمّد نجّار است. نجّارها چوب و ارّه دارند.", "reading_az": "Mohəmməd nəccar əst. Nəccarha çub va ərre darənd.", "az": "Məhəmməd dülgərdir. Dülgərlərin taxtası və mişarı var."},
            ],
        },
    ],
    "exercises": [
        {
            "kind": "fill_blank",
            "instruction_az": "Nümunə kimi tamamlayın: «من و حامد بنّا نیستیم؛ مهندس هستیم.»",
            "word_bank": ["نیست", "نیستیم", "نیستید", "نیستند", "است", "هستند"],
            "items": [
                {
                    "fa_with_blank": "مریم معلّم است؛ مدیر ___ .",
                    "correct_answer": "نیست",
                    "reading_az": "nist",
                    "az": "deyil",
                    "full_reading_az": "Məryəm moəllem əst; modir nist.",
                    "full_translation_az": "Məryəm müəllimdir; müdir deyil.",
                },
                {
                    "fa_with_blank": "من و زینب خیّاط هستیم؛ عکّاس ___ .",
                    "correct_answer": "نیستیم",
                    "reading_az": "nistim",
                    "az": "deyilik",
                    "full_reading_az": "Mən va Zeynəb xəyyat hastim; əkkas nistim.",
                    "full_translation_az": "Mən və Zeynəb dərziyik; fotoqraf deyilik.",
                },
                {
                    "fa_with_blank": "تو و فاطمه پرستار هستید؛ پزشک ___ .",
                    "correct_answer": "نیستید",
                    "reading_az": "nistid",
                    "az": "deyilsiniz",
                    "full_reading_az": "To va Fateme pərəstar hastid; pezeşk nistid.",
                    "full_translation_az": "Sən və Fatimə tibb bacısısınız; həkim deyilsiniz.",
                },
                {
                    "fa_with_blank": "آن خانم دندان‌پزشک است؛ پرستار ___ .",
                    "correct_answer": "نیست",
                    "reading_az": "nist",
                    "az": "deyil",
                    "full_reading_az": "An xanom dəndanpezeşk əst; pərəstar nist.",
                    "full_translation_az": "O xanım diş həkimidir; tibb bacısı deyil.",
                },
                {
                    "fa_with_blank": "آن آقا چوپان است؛ او قصّاب ___ .",
                    "correct_answer": "نیست",
                    "reading_az": "nist",
                    "az": "deyil",
                    "full_reading_az": "An ağa çupan əst; u qəssab nist.",
                    "full_translation_az": "O kişi çobandır; o, qəssab deyil.",
                },
                {
                    "fa_with_blank": "علی و احمد پلیس هستند؛ قاضی ___ .",
                    "correct_answer": "نیستند",
                    "reading_az": "nistənd",
                    "az": "deyillər",
                    "full_reading_az": "Əli va Əhməd polis həstənd; qazi nistənd.",
                    "full_translation_az": "Əli və Əhməd polisdir; hakim deyillər.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi: «یوسف / عکّاس / دوربین → یوسف چه‌کاره است؟ او عکّاس است. عکّاس چه دارد؟ عکّاس دوربین دارد.»",
            "items": [
                {
                    "prompt_fa": "محمّد / خیّاط / قیچی، سوزن و اتو",
                    "answer_fa": "محمّد چه‌کاره است؟ او خیّاط است. خیّاط چه دارد؟ خیّاط قیچی، سوزن و اتو دارد.",
                    "reading_az": "Mohəmməd çekare əst? U xəyyat əst. Xəyyat çe darəd? Xəyyat qeyçi, suzən va otu darəd.",
                    "az": "Məhəmməd nəçidir? O, dərzidir. Dərzinin nəyi var? Dərzinin qayçısı, iynəsi və ütüsü var.",
                },
                {
                    "prompt_fa": "زهرا خانم / استاد / رایانه و کتاب",
                    "answer_fa": "زهرا خانم چه‌کاره است؟ ایشان استاد هستند. استاد چه دارد؟ استاد رایانه و کتاب دارد.",
                    "reading_az": "Zəhra xanom çekare əst? İşan ostad həstənd. Ostad çe darəd? Ostad rayane va ketab darəd.",
                    "az": "Zəhra xanım nəçidir? O, müəllimdir. Müəllimin nəyi var? Müəllimin komputeri və kitabı var.",
                },
                {
                    "prompt_fa": "دخترت / دانش‌جو / کیف و نوشت‌افزار",
                    "answer_fa": "دخترت چه‌کاره است؟ دخترم دانش‌جو است. دانش‌جو چه دارد؟ دانش‌جو کیف و نوشت‌افزار دارد.",
                    "reading_az": "Doxtərət çekare əst? Doxtərəm daneşcu əst. Daneşcu çe darəd? Daneşcu kif va neveştəfzar darəd.",
                    "az": "Qızın nəçidir? Qızım tələbədir. Tələbənin nəyi var? Tələbənin çantası və yazı ləvazimatı var.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "«امّا» sözü ilə cümlə qurun: «من رایانه / دوستم → من رایانه دارم؛ امّا دوستم رایانه ندارد.»",
            "items": [
                {
                    "prompt_fa": "زهرا عینک / همسرش",
                    "answer_fa": "زهرا عینک دارد؛ امّا همسرش عینک ندارد.",
                    "reading_az": "Zəhra eynək darəd; əmma həmsərəş eynək nədarəd.",
                    "az": "Zəhranın eynəyi var; amma həyat yoldaşının eynəyi yoxdur.",
                },
                {
                    "prompt_fa": "همسرم عمو / من",
                    "answer_fa": "همسرم عمو دارد؛ امّا من عمو ندارم.",
                    "reading_az": "Həmsərəm əmu darəd; əmma mən əmu nədaram.",
                    "az": "Həyat yoldaşımın əmisi var; amma mənim əmim yoxdur.",
                },
                {
                    "prompt_fa": "سعید چاق / برادرش لاغر",
                    "answer_fa": "سعید چاق است؛ امّا برادرش لاغر است.",
                    "reading_az": "Səid çaq əst; əmma bəradərəş lağər əst.",
                    "az": "Səid kökdür; amma qardaşı arıqdır.",
                },
                {
                    "prompt_fa": "ما مجرّد / آن‌ها متأهل",
                    "answer_fa": "ما مجرّد هستیم؛ امّا آن‌ها متأهل هستند.",
                    "reading_az": "Ma mocərrəd hastim; əmma anha motəəhhel həstənd.",
                    "az": "Biz subayıq; amma onlar evlidir.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi: «دوستم / مدیر / مدرسه‌ی ابن سینا → دوستم مدیر است. او در مدرسه‌ی ابن سینا کار می‌کند.»",
            "items": [
                {
                    "prompt_fa": "عموی نادر / نگهبان / بانک ملّی ایران",
                    "answer_fa": "عموی نادر نگهبان است. او در بانک ملّی ایران کار می‌کند.",
                    "reading_az": "Əmuye Nadər negəhban əst. U dər banke melliye Iran kar mikonəd.",
                    "az": "Nadirin əmisi keşikçidir. O, İranın Milli Bankında işləyir.",
                },
                {
                    "prompt_fa": "پدربزرگم / استاد / دانش‌گاه تهران",
                    "answer_fa": "پدربزرگم استاد است. ایشان در دانش‌گاه تهران کار می‌کنند.",
                    "reading_az": "Pedərbozorgəm ostad əst. İşan dər daneşgahe Tehran kar mikonənd.",
                    "az": "Babam müəllimdir. O, Tehran Universitetində işləyir.",
                },
                {
                    "prompt_fa": "زهرا و طاهره / پرستار / بیمارستان امام سجّاد",
                    "answer_fa": "زهرا و طاهره پرستار هستند. آن‌ها در بیمارستان امام سجّاد کار می‌کنند.",
                    "reading_az": "Zəhra va Tahere pərəstar həstənd. Anha dər bimarestane Emam Səccad kar mikonənd.",
                    "az": "Zəhra və Tahirə tibb bacısıdır. Onlar İmam Səccad xəstəxanasında işləyirlər.",
                },
            ],
        },
    ],
    "sentence_practice": {
        "listen_exercises": [
            {
                "items": [
                    {
                        "fa": "پدرم نجّار است. او میز و صندلی می‌سازد.",
                        "reading_az": "Pedərəm nəccar əst. U miz va səndəli misazəd.",
                        "az": "Atam dülgərdir. O, masa və stul düzəldir.",
                    },
                    {
                        "fa": "آن مرد، رفتگر است. او خیابان را جارو می‌کند.",
                        "reading_az": "An mərd, roftegər əst. U xiyaban ra caru mikonəd.",
                        "az": "O kişi zibilyığandır. O, küçəni süpürür.",
                    },
                    {
                        "fa": "نادر و سلیمان کارگر هستند. آن‌ها به بنّا کمک می‌کنند.",
                        "reading_az": "Nadər va Soleyman kargər həstənd. Anha be bənna komək mikonənd.",
                        "az": "Nadir və Süleyman fəhlədir. Onlar bənnaya kömək edirlər.",
                    },
                    {
                        "fa": "آن خانم، استاد ما است؛ ایشان به ما زبان فارسی درس می‌دهد.",
                        "reading_az": "An xanom, ostade ma əst; işan be ma zəbane farsi dərs midəhəd.",
                        "az": "O xanım bizim müəlliməmizdir; o bizə fars dili öyrədir.",
                    },
                    {
                        "fa": "ما مهندسِ رایانه هستیم و در جامعة المصطفی کار می‌کنیم.",
                        "reading_az": "Ma mohəndese rayane hastim va dər Cameətol-Mostəfa kar mikonim.",
                        "az": "Biz kompüter mühəndisiyik və əl-Müstəfa Cəmiyyətində işləyirik.",
                    },
                    {
                        "fa": "برادرم بنّا است و خانه می‌سازد. خواهرم خیّاط است و لباس می‌دوزد.",
                        "reading_az": "Bəradərəm bənna əst va xane misazəd. Xahərəm xəyyat əst va lebas miduzəd.",
                        "az": "Qardaşım bənnadır və ev tikir. Bacım dərzidir və paltar tikir.",
                    },
                    {
                        "fa": "نجّار با چوب، در و پنجره می‌سازد و آهنگر با آهن، در و پنجره می‌سازد.",
                        "reading_az": "Nəccar ba çub, dər va pəncəre misazəd va ahəngər ba ahən, dər va pəncəre misazəd.",
                        "az": "Dülgər taxtadan qapı və pəncərə düzəldir, dəmirçi isə dəmirdən qapı və pəncərə düzəldir.",
                    },
                    {
                        "fa": "احمد و دوستش دانش‌جو هستند. آن‌ها در دانش‌گاه تهران درس می‌خوانند.",
                        "reading_az": "Əhməd va dustəş daneşcu həstənd. Anha dər daneşgahe Tehran dərs mixanənd.",
                        "az": "Əhməd və dostu tələbədir. Onlar Tehran Universitetində oxuyurlar.",
                    },
                    {
                        "fa": "محمّد و فاطمه دانش‌آموز هستند؛ پدرشان معلّم است و مادرشان مدیر مدرسه است.",
                        "reading_az": "Mohəmməd va Fateme daneşamuz həstənd; pedərşan moəllem əst va madərşan modire mædrese əst.",
                        "az": "Məhəmməd və Fatimə şagirddir; ataları müəllim, anaları isə məktəb müdiridir.",
                    },
                    {
                        "fa": "من و همسرم پزشک هستیم. ما بیمارها را معاینه می‌کنیم و برای آن‌ها دارو می‌نویسیم.",
                        "reading_az": "Mən va həmsərəm pezeşk hastim. Ma bimarha ra moayene mikonim va bəraye anha daru minevisim.",
                        "az": "Mən və həyat yoldaşım həkimik. Biz xəstələri müayinə edirik və onlara dərman yazırıq.",
                    },
                ],
            },
        ],
        "answer_items": [
            {
                "fa": "اسم رئیس‌جمهور کشورتان چیست؟",
                "reading_az": "Esme rəis-comhure kəşvəretan çist?",
                "az": "Ölkənizin prezidentinin adı nədir?",
            },
            {
                "fa": "آهنگر و نجّار چه‌کار می‌کنند؟",
                "reading_az": "Ahəngər va nəccar çekar mikonənd?",
                "az": "Dəmirçi və dülgər nə iş görür?",
                "sample_answer_fa": "آهنگر با آهن کار می‌کند و نجّار با چوب کار می‌کند.",
                "sample_answer_reading_az": "Ahəngər ba ahən kar mikonəd va nəccar ba çub kar mikonəd.",
                "sample_answer_az": "Dəmirçi dəmirlə, dülgər isə taxta ilə işləyir.",
            },
            {
                "fa": "آیا برادرتان مهندس رایانه است؟",
                "reading_az": "Aya bəradəretan mohəndese rayane əst?",
                "az": "Qardaşınız kompüter mühəndisidirmi?",
                "sample_answer_fa": "بله، برادرم مهندس رایانه است.",
                "sample_answer_reading_az": "Bəle, bəradərəm mohəndese rayane əst.",
                "sample_answer_az": "Bəli, qardaşım kompüter mühəndisidir.",
            },
            {
                "fa": "آیا خیّاط میز و صندلی نمی‌سازد؟",
                "reading_az": "Aya xəyyat miz va səndəli nemisazəd?",
                "az": "Dərzi masa və stul düzəltmir?",
                "sample_answer_fa": "بله، خیّاط میز و صندلی نمی‌سازد؛ او لباس می‌دوزد.",
                "sample_answer_reading_az": "Bəle, xəyyat miz va səndəli nemisazəd; u lebas miduzəd.",
                "sample_answer_az": "Bəli, dərzi masa və stul düzəltmir; o, paltar tikir.",
            },
            {
                "fa": "پزشک چه‌کار می‌کند؟",
                "reading_az": "Pezeşk çekar mikonəd?",
                "az": "Həkim nə iş görür?",
                "sample_answer_fa": "پزشک بیمارها را معاینه می‌کند و نسخه می‌نویسد.",
                "sample_answer_reading_az": "Pezeşk bimarha ra moayene mikonəd va nosxe minevisəd.",
                "sample_answer_az": "Həkim xəstələri müayinə edir və resept yazır.",
            },
        ],
    },
    "reading_text": {
        "title_fa": "خانواده‌ی من",
        "title_az": "Mənim ailəm",
        "paragraphs_fa": [
            "من در یک خانواده‌ی شش‌نفره زندگی می‌کنم. اسمم نرگس است. من متأهل هستم. نام همسرم، صادق است. من و صادق دانش‌جو هستیم و در دانش‌گاه تهران درس می‌خوانیم.",
            "همسرم، برادر و خواهر ندارد؛ امّا من یک خواهر و دو برادر دارم. خواهرم شهربانو، از من کوچک‌تر است. او دانش‌آموز است و در مدرسه‌ی شهید بهشتی درس می‌خواند.",
            "برادرم سجّاد، مهندس رایانه است. ایشان در فرودگاه امام‌خمینی تهران کار می‌کند و برادرم حسن، دکترِ قلب است. او در بیمارستان ابوعلی سینا کار می‌کند.",
            "مادرم خانه‌دار است و پدرم معلّم بازنشسته است. ایشان شصت سال دارد. او گاهی کتاب مطالعه می‌کند، گاهی روزنامه می‌خواند و گاهی در کارهای خانه به مادرم کمک می‌کند.",
            "من خانواده‌ام را بسیار دوست دارم.",
        ],
        "footnotes": [
            {"fa": "خانه‌دار", "az": "evdar"},
            {"fa": "بازنشسته", "az": "təqaüdçü"},
            {"fa": "شصت", "az": "altmış"},
            {"fa": "گاهی", "az": "bəzən"},
            {"fa": "امّا", "az": "amma"},
        ],
        "full_translation_az": (
            "Mən altı nəfərlik bir ailədə yaşayıram. Adım Nərgizdir. Mən evliyəm. Həyat yoldaşımın adı Sadiqdir. "
            "Mən və Sadiq tələbəyik və Tehran Universitetində oxuyuruq.\n\n"
            "Həyat yoldaşımın qardaşı və bacısı yoxdur; amma mənim bir bacım və iki qardaşım var. Bacım Şəhrbanu "
            "məndən kiçikdir. O, şagirddir və Şəhid Behişti məktəbində oxuyur.\n\n"
            "Qardaşım Səccad kompüter mühəndisidir. O, Tehranın İmam Xomeyni hava limanında işləyir. Qardaşım "
            "Həsən isə ürək həkimidir. O, Əbu Əli Sina xəstəxanasında işləyir.\n\n"
            "Anam evdar qadındır, atam isə təqaüdçü müəllimdir. Onun altmış yaşı var. O, bəzən kitab oxuyur, "
            "bəzən qəzet oxuyur, bəzən də ev işlərində anama kömək edir.\n\n"
            "Mən ailəmi çox sevirəm."
        ),
        "sentences": [
            {"fa": "من در یک خانواده‌ی شش‌نفره زندگی می‌کنم.", "reading_az": "Mən dər yek xanevade-ye şeş-nəfəre zendegi mikonəm.", "az": "Mən altı nəfərlik bir ailədə yaşayıram.", "new_paragraph": True},
            {"fa": "اسمم نرگس است.", "reading_az": "Esməm Nərges əst.", "az": "Adım Nərgizdir."},
            {"fa": "من متأهل هستم.", "reading_az": "Mən motəəhhel hastəm.", "az": "Mən evliyəm."},
            {"fa": "نام همسرم، صادق است.", "reading_az": "Name həmsərəm, Sadeq əst.", "az": "Həyat yoldaşımın adı Sadiqdir."},
            {
                "fa": "من و صادق دانش‌جو هستیم و در دانش‌گاه تهران درس می‌خوانیم.",
                "reading_az": "Mən va Sadeq daneşcu hastim va dər daneşgahe Tehran dərs mixanim.",
                "az": "Mən və Sadiq tələbəyik və Tehran Universitetində oxuyuruq.",
            },
            {
                "fa": "همسرم، برادر و خواهر ندارد؛ امّا من یک خواهر و دو برادر دارم.",
                "reading_az": "Həmsərəm, bəradər va xahər nədarəd; əmma mən yek xahər va do bəradər daram.",
                "az": "Həyat yoldaşımın qardaşı və bacısı yoxdur; amma mənim bir bacım və iki qardaşım var.",
                "new_paragraph": True,
            },
            {"fa": "خواهرم شهربانو، از من کوچک‌تر است.", "reading_az": "Xahərəm Şəhrbanu, əz mən kuçektər əst.", "az": "Bacım Şəhrbanu məndən kiçikdir."},
            {
                "fa": "او دانش‌آموز است و در مدرسه‌ی شهید بهشتی درس می‌خواند.",
                "reading_az": "U daneşamuz əst va dər mædrese-ye Şəhide Beheşti dərs mixanəd.",
                "az": "O, şagirddir və Şəhid Behişti məktəbində oxuyur.",
            },
            {"fa": "برادرم سجّاد، مهندس رایانه است.", "reading_az": "Bəradərəm Səccad, mohəndese rayane əst.", "az": "Qardaşım Səccad kompüter mühəndisidir.", "new_paragraph": True},
            {"fa": "ایشان در فرودگاه امام‌خمینی تهران کار می‌کند.", "reading_az": "İşan dər forudgahe Emam Xomeyniye Tehran kar mikonəd.", "az": "O, Tehranın İmam Xomeyni hava limanında işləyir."},
            {"fa": "برادرم حسن، دکترِ قلب است.", "reading_az": "Bəradərəm Həsən, doktore qəlb əst.", "az": "Qardaşım Həsən ürək həkimidir."},
            {"fa": "او در بیمارستان ابوعلی سینا کار می‌کند.", "reading_az": "U dər bimarestane Əbuəli Sina kar mikonəd.", "az": "O, Əbu Əli Sina xəstəxanasında işləyir."},
            {
                "fa": "مادرم خانه‌دار است و پدرم معلّم بازنشسته است.",
                "reading_az": "Madərəm xanedar əst va pedərəm moəlleme bazneşəste əst.",
                "az": "Anam evdar qadındır, atam isə təqaüdçü müəllimdir.",
                "new_paragraph": True,
            },
            {"fa": "ایشان شصت سال دارد.", "reading_az": "İşan şəst sal darəd.", "az": "Onun altmış yaşı var."},
            {
                "fa": "او گاهی کتاب مطالعه می‌کند، گاهی روزنامه می‌خواند و گاهی در کارهای خانه به مادرم کمک می‌کند.",
                "reading_az": "U gahi ketab motaleə mikonəd, gahi ruzname mixanəd va gahi dər karhaye xane be madərəm komək mikonəd.",
                "az": "O, bəzən kitab oxuyur, bəzən qəzet oxuyur, bəzən də ev işlərində anama kömək edir.",
            },
            {"fa": "من خانواده‌ام را بسیار دوست دارم.", "reading_az": "Mən xanevadeəm ra besyar dust daram.", "az": "Mən ailəmi çox sevirəm.", "new_paragraph": True},
        ],
        "comprehension_questions": [
            {
                "question_fa": "نرگس و همسرش چه‌کاره هستند؟",
                "reading_az": "Nərges va həmsərəş çekare həstənd?",
                "az": "Nərgiz və həyat yoldaşı nəçidir?",
                "sample_answer_fa": "نرگس و همسرش دانش‌جو هستند.",
                "sample_answer_reading_az": "Nərges va həmsərəş daneşcu həstənd.",
                "sample_answer_az": "Nərgiz və həyat yoldaşı tələbədir.",
            },
            {
                "question_fa": "آیا پدر نرگس الآن درس می‌دهد؟",
                "reading_az": "Aya pedəre Nərges əl-an dərs midəhəd?",
                "az": "Nərgizin atası indi dərs deyirmi?",
                "sample_answer_fa": "نه، پدر نرگس بازنشسته است.",
                "sample_answer_reading_az": "Nə, pedəre Nərges bazneşəste əst.",
                "sample_answer_az": "Xeyr, Nərgizin atası təqaüdçüdür.",
            },
            {
                "question_fa": "پدر نرگس هر روز چه‌کار می‌کند؟",
                "reading_az": "Pedəre Nərges hər ruz çekar mikonəd?",
                "az": "Nərgizin atası hər gün nə edir?",
                "sample_answer_fa": "او گاهی کتاب مطالعه می‌کند و گاهی به مادرم کمک می‌کند.",
                "sample_answer_reading_az": "U gahi ketab motaleə mikonəd va gahi be madərəm komək mikonəd.",
                "sample_answer_az": "O, bəzən kitab oxuyur, bəzən anama kömək edir.",
            },
            {
                "question_fa": "صادق در کدام دانش‌گاه درس می‌خواند؟",
                "reading_az": "Sadeq dər kodam daneşgah dərs mixanəd?",
                "az": "Sadiq hansı universitetdə oxuyur?",
                "sample_answer_fa": "صادق در دانش‌گاه تهران درس می‌خواند.",
                "sample_answer_reading_az": "Sadeq dər daneşgahe Tehran dərs mixanəd.",
                "sample_answer_az": "Sadiq Tehran Universitetində oxuyur.",
            },
            {
                "question_fa": "کدام برادر نرگس، دکترِ قلب است؟",
                "reading_az": "Kodam bəradəre Nərges, doktore qəlb əst?",
                "az": "Nərgizin hansı qardaşı ürək həkimidir?",
                "sample_answer_fa": "برادرش حسن، دکترِ قلب است.",
                "sample_answer_reading_az": "Bəradərəş Həsən, doktore qəlb əst.",
                "sample_answer_az": "Qardaşı Həsən ürək həkimidir.",
            },
            {
                "question_fa": "آیا خانواده‌ی نرگس، چهار نفره هستند؟",
                "reading_az": "Aya xanevade-ye Nərges, çahar-nəfəre həstənd?",
                "az": "Nərgizin ailəsi dörd nəfərlikdirmi?",
                "sample_answer_fa": "نه، خانواده‌ی نرگس شش نفره هستند.",
                "sample_answer_reading_az": "Nə, xanevade-ye Nərges şeş-nəfəre həstənd.",
                "sample_answer_az": "Xeyr, Nərgizin ailəsi altı nəfərlikdir.",
            },
            {
                "question_fa": "سجّاد چه‌کاره است و کجا کار می‌کند؟",
                "reading_az": "Səccad çekare əst va koca kar mikonəd?",
                "az": "Səccad nəçidir və harada işləyir?",
                "sample_answer_fa": "سجّاد مهندس رایانه است و در فرودگاه امام‌خمینی کار می‌کند.",
                "sample_answer_reading_az": "Səccad mohəndese rayane əst va dər forudgahe Emam Xomeyni kar mikonəd.",
                "sample_answer_az": "Səccad kompüter mühəndisidir və İmam Xomeyni hava limanında işləyir.",
            },
        ],
    },
}
