# Dərs 13 — طبیعت (Təbiət)
# Mənbə: کتاب دوم, səh. 159-170

LESSON = {
    "number": 13,
    "title_fa": "طبیعت",
    "title_az": "Təbiət",
    "available": True,
    "vocabulary": [
        {"fa": "خورشید (آفتاب)", "reading": "xorşid (aftab)", "az": "Günəş"},
        {"fa": "ابر", "reading": "əbr", "az": "Bulud"},
        {"fa": "چشمه", "reading": "çeşme", "az": "Bulaq"},
        {"fa": "آبشار", "reading": "abşar", "az": "Şəlalə"},
        {"fa": "رودخانه", "reading": "rudxane", "az": "Çay (irmaq)"},
        {"fa": "دریا", "reading": "dərya", "az": "Dəniz"},
        {"fa": "ساحل", "reading": "sahel", "az": "Sahil"},
        {"fa": "کنار دریا", "reading": "kənare dərya", "az": "Dənizkənarı"},
        {"fa": "جزیره", "reading": "cəzire", "az": "Ada"},
        {"fa": "سد", "reading": "sədd", "az": "Bənd (su bəndi)"},
        {"fa": "گردش", "reading": "gərdeş", "az": "Gəzinti"},
        {"fa": "قلّه", "reading": "qolle", "az": "Zirvə"},
        {"fa": "درّه", "reading": "dərre", "az": "Dərə"},
        {"fa": "چاه", "reading": "çah", "az": "Quyu"},
        {"fa": "گیاه", "reading": "giyah", "az": "Bitki"},
        {"fa": "خاک", "reading": "xak", "az": "Torpaq"},
        {"fa": "گِل", "reading": "gel", "az": "Palçıq"},
        {"fa": "زلزله", "reading": "zelzele", "az": "Zəlzələ"},
        {"fa": "آتش‌سوزی", "reading": "atəşsuzi", "az": "Yanğın"},
        {"fa": "سیل", "reading": "seyl", "az": "Sel"},
        {"fa": "اطراف", "reading": "ətraf", "az": "Ətraf"},
        {"fa": "خنک", "reading": "xonək", "az": "Sərin"},
        {"fa": "می‌بارد", "reading": "mibarəd", "az": "yağır"},
        {"fa": "تماشا می‌کند", "reading": "təmaşa mikonəd", "az": "tamaşa edir"},
        {"fa": "غرق می‌شود", "reading": "qərq mişəvəd", "az": "batır"},
        {"fa": "نجات می‌دهد", "reading": "nəcat midəhəd", "az": "xilas edir"},
        {"fa": "خاموش می‌کند", "reading": "xamuş mikonəd", "az": "söndürür"},
        {"fa": "دربارهٔ", "reading": "dərbareye", "az": "…haqqında"},
        {"fa": "معتدل", "reading": "moetədel", "az": "Mülayim (mötədil)"},
        {"fa": "دیگر", "reading": "digər", "az": "Başqa, digər"},
        {"fa": "بین", "reading": "beyn", "az": "Arasında"},
        {"fa": "تفریح", "reading": "təfrih", "az": "Əyləncə, istirahət"},
        {"fa": "منظره", "reading": "mənzəre", "az": "Mənzərə"},
        {"fa": "مسیر", "reading": "məsir", "az": "Marşrut, yol"},
        {"fa": "به سبب", "reading": "be səbəbe", "az": "…-ə görə, səbəbindən"},
        {"fa": "لذّت‌بخش", "reading": "ləzzətbəxş", "az": "Ləzzətli, xoş"},
        {"fa": "دید (دیدن)", "reading": "did (didən)", "az": "gördü (görmək)"},
        {"fa": "گفت (گفتن)", "reading": "goft (goftən)", "az": "dedi (demək)"},
    ],
    "grammar_notes": [
        {
            "title_az": "Fəsillər",
            "title_fa": "فصل‌ها",
            "conjugations": [
                {"pronoun_fa": "بهار", "form_fa": "Yaz"},
                {"pronoun_fa": "تابستان", "form_fa": "Yay"},
                {"pronoun_fa": "پاییز", "form_fa": "Payız"},
                {"pronoun_fa": "زمستان", "form_fa": "Qış"},
            ],
            "examples": [
                {"fa": "ایران چهار فصل دارد: بهار، تابستان، پاییز و زمستان.", "reading_az": "Iran çəhar fəsl darəd: bəhar, tabestan, payiz va zemestan.", "az": "İranın dörd fəsli var: yaz, yay, payız və qış."},
                {"fa": "بهار، فصل اوّل سال و زمستان، فصل آخر سال است.", "reading_az": "Bəhar, fəsle əvvəle sal va zemestan, fəsle axəre sal əst.", "az": "Yaz ilin ilk, qış isə son fəslidir."},
                {"fa": "فصل بهار زیبا است. در این فصل، هوا خنک است و باران زیاد می‌بارد.", "reading_az": "Fəsle bəhar ziba əst. Dər in fəsl, həva xonək əst va baran ziyad mibarəd.", "az": "Yaz fəsli gözəldir. Bu fəsildə hava sərindir və çox yağış yağır."},
                {"fa": "در فصل تابستان، هوا گرم است. مدرسه‌ها و دانش‌گاه‌های ایران در تابستان تعطیل هستند.", "reading_az": "Dər fəsle tabestan, həva gərm əst. Mædresеha va daneşgahhaye Iran dər tabestan tətil həstənd.", "az": "Yay fəslində hava istidir. İranın məktəbləri və universitetləri yayda tətildə olur."},
                {"fa": "در فصل پاییز، برگ درختان زرد می‌شود.", "reading_az": "Dər fəsle payiz, bərge dərəxtan zərd mişəvəd.", "az": "Payız fəslində ağacların yarpaqları saralır."},
                {"fa": "در فصل زمستان، هوا سرد است. زمستان در بسیاری از شهرها و روستاهای ایران برف می‌بارد.", "reading_az": "Dər fəsle zemestan, həva sərd əst. Zemestan dər besyari əz şəhrha va rustahaye Iran bərf mibarəd.", "az": "Qış fəslində hava soyuqdur. İranın bir çox şəhər və kəndlərində qışda qar yağır."},
            ],
        },
        {
            "title_az": "İran təqviminin ayları",
            "title_fa": "ماه‌ها",
            "conjugations": [
                {"pronoun_fa": "بهار", "form_fa": "فروردین؛ اردیبهشت؛ خرداد"},
                {"pronoun_fa": "تابستان", "form_fa": "تیر؛ مرداد؛ شهریور"},
                {"pronoun_fa": "پاییز", "form_fa": "مهر؛ آبان؛ آذر"},
                {"pronoun_fa": "زمستان", "form_fa": "دی؛ بهمن؛ اسفند"},
            ],
            "examples": [
                {"fa": "یک سال، ۳۶۵ روز است و چهار فصل دارد.", "reading_az": "Yek sal, sisəd o şast o pənc ruz əst va çəhar fəsl darəd.", "az": "Bir il 365 gündür və dörd fəsli var."},
                {"fa": "یک سال، دوازده ماه است. فروردین، ماه اوّل سال و اسفند، ماه آخر سال است.", "reading_az": "Yek sal, davazdəh mah əst. Fərvərdin, mahe əvvəle sal va Esfənd, mahe axəre sal əst.", "az": "Bir il on iki aydır. Fərvərdin ilin ilk, Esfənd isə son ayıdır."},
                {"fa": "یک فصل، سه ماه است. فروردین، اردیبهشت و خرداد، ماه‌های فصل بهار هستند.", "reading_az": "Yek fəsl, se mah əst. Fərvərdin, Ordibeheşt va Xordad, mahhaye fəsle bəhar həstənd.", "az": "Bir fəsil üç aydır. Fərvərdin, Ordibeheşt və Xordad — yazın aylarıdır."},
                {"fa": "تیر، مرداد و شهریور، ماه‌های فصل تابستان هستند. مرداد، گرم‌ترین ماه در ایران است.", "reading_az": "Tir, Mordad va Şəhrivər, mahhaye fəsle tabestan həstənd. Mordad, gərmtərin mah dər Iran əst.", "az": "Tir, Mordad və Şəhrivər — yayın aylarıdır. Mordad İranın ən isti ayıdır."},
                {"fa": "ماه‌های فصل پاییز، مهر، آبان و آذر است.", "reading_az": "Mahhaye fəsle payiz, Mehr, Aban va Azər əst.", "az": "Payızın ayları Mehr, Aban və Azərdir."},
                {"fa": "دی، بهمن و اسفند ماه‌های فصل زمستان هستند.", "reading_az": "Dey, Bəhmən va Esfənd mahhaye fəsle zemestan həstənd.", "az": "Dey, Bəhmən və Esfənd qışın aylarıdır."},
                {"fa": "بیشتر مردم ایران در ماه‌های فصل تابستان برای گردش به کوه، جنگل و دریا می‌روند.", "reading_az": "Bişttər mərdome Iran dər mahhaye fəsle tabestan bəraye gərdeş be kuh, cəngəl va dərya mirəvənd.", "az": "İran əhalisinin çoxu yay aylarında gəzintiyə dağa, meşəyə və dənizə gedir."},
                {"fa": "در فصل تابستان، مدرسه‌ها تعطیل است. دانش‌آموزان، اوّل مهر به مدرسه می‌روند.", "reading_az": "Dər fəsle tabestan, mædresеha tətil əst. Daneşamuzan, əvvəle Mehr be mædrese mirəvənd.", "az": "Yay fəslində məktəblər tətildə olur. Şagirdlər Mehr ayının əvvəlində məktəbə gedirlər."},
            ],
        },
        {
            "title_az": "Sıra sayları",
            "title_fa": "عددهای ترتیبی",
            "conjugations": [
                {"pronoun_fa": "یک → یکم (اوّل)", "form_fa": "ده → دهم"},
                {"pronoun_fa": "دو → دوم", "form_fa": "یازده → یازدهم"},
                {"pronoun_fa": "بیست و یک → بیست و یکم", "form_fa": "بیست → بیستم"},
                {"pronoun_fa": "سی → سی‌ام", "form_fa": "چهل → چهلم"},
                {"pronoun_fa": "صد → صدم", "form_fa": "…"},
            ],
            "examples": [
                {"fa": "ساده عددهر: yekə +ـُم (کسری‌ای مرکب: عدد اصلی + ـُم = عدد ترتیبی، مانند یازده → یازدهم؛ بیست و پنج → بیست و پنجم).", "reading_az": "Ədəde əsli + «-om» = ədəde tərtibi.", "az": "Adi ədədin sonuna «ـُم» şəkilçisi əlavə edilir: on bir → on birinci; iyirmi beş → iyirmi beşinci."},
                {"fa": "در غیرِ عدد مرکب، بیشتر از واژه‌ی «اوّل» استفاده می‌کنیم، مانند: کلاس اوّل؛ کتاب اوّل؛ ایستگاه اوّل.", "reading_az": "Dər qeyre ædæde morəkkəb, bişttər əz vajeye «əvvəl» estefade mikonim, manənde: kelase əvvəl; ketabe əvvəl; istqahe əvvəl.", "az": "Mürəkkəb olmayan ədədlərdə çox vaxt «birinci» (اوّل) sözü işlənir: birinci sinif, birinci kitab."},
                {"fa": "در عدد مرکب از واژه‌ی «یکم» استفاده می‌کنیم، مانند بیست و یکم؛ سی و یکم.", "reading_az": "Dər ædæde morəkkəb əz vajeye «yekom» estefade mikonim, manənde bist o yekom; si o yekom.", "az": "Mürəkkəb ədədlərdə isə «یکم» işlənir: iyirmi birinci, otuz birinci."},
                {"fa": "کتاب دوم درس دارد؛ ما امروز درسِ دوازدهم را می‌خوانیم.", "reading_az": "Ketabe dovvom dərs darəd; ma emruz dərse davazdəhom ra mixanim.", "az": "İkinci kitabın dərsləri var; biz bu gün on ikinci dərsi oxuyuruq."},
                {"fa": "بهار، فصل اوّل سال؛ تابستان فصل دوم؛ پاییز فصل سوم؛ زمستان، فصل چهارم سال است.", "reading_az": "Bəhar, fəsle əvvəle sal; tabestan fəsle dovvom; payiz fəsle sevvom; zemestan, fəsle çəharome sal əst.", "az": "Yaz ilin birinci, yay ikinci, payız üçüncü, qış isə dördüncü fəslidir."},
                {"fa": "من دو برادر دارم. برادر اوّلم، سی و دو سال و برادر دومم، بیست و هفت سال دارد.", "reading_az": "Mən do bəradər daram. Bəradəre əvvələm, si o do sal va bəradəre dovvoməm, bist o həft sal darəd.", "az": "Mənim iki qardaşım var. Birinci qardaşımın otuz iki, ikinci qardaşımın isə iyirmi yeddi yaşı var."},
                {"fa": "روز اوّل هفته، شنبه است.", "reading_az": "Ruze əvvəle həfte, şənbe əst.", "az": "Həftənin birinci günü şənbədir."},
                {"fa": "من دو ماه قبل به ایران آمدم و الآن کتاب دوم را می‌خوانم.", "reading_az": "Mən do mah qəbl be Iran amədəm va əlan ketabe dovvom ra mixanəm.", "az": "Mən iki ay əvvəl İrana gəldim və indi ikinci kitabı oxuyuram."},
            ],
        },
        {
            "title_az": "Sual sözü «چندم» (neçənci?)",
            "title_fa": "واژه‌ی پرسشی «چندم»",
            "conjugations": [
                {"pronoun_fa": "یک هفته چند روز است؟", "form_fa": "یک هفته هفت روز است."},
                {"pronoun_fa": "دوشنبه روز چندم هفته است؟", "form_fa": "دوشنبه روز سوم هفته است."},
                {"pronoun_fa": "شما کتاب چندم را می‌خوانید؟", "form_fa": "ما کتاب دوم را می‌خوانیم."},
            ],
            "examples": [
                {"fa": "مهر، ماه چندم سال است؟ مهر، ماه هفتم سال است.", "reading_az": "Mehr, mahe çəndome sal əst? Mehr, mahe həftome sal əst.", "az": "Mehr ayı ilin neçənci ayıdır? Mehr ilin yeddinci ayıdır."},
                {"fa": "شما دیروز درس چندم را خواندید؟ من دیروز درس دوازدهم را خواندم.", "reading_az": "Şoma diruz dərse çəndom ra xandid? Mən diruz dərse davazdəhom ra xandəm.", "az": "Siz dünən neçənci dərsi oxudunuz? Mən dünən on ikinci dərsi oxudum."},
                {"fa": "تابستان، فصل چندم سال است؟ تابستان، فصل دوم سال است.", "reading_az": "Tabestan, fəsle çəndome sal əst? Tabestan, fəsle dovvome sal əst.", "az": "Yay ilin neçənci fəslidir? Yay ilin ikinci fəslidir."},
                {"fa": "خانه‌ی شما در طبقه‌ی چندم است؟ خانه‌ی ما در طبقه‌ی سوم است.", "reading_az": "Xaneye şoma dər təbəqeye çəndom əst? Xaneye ma dər təbəqeye sevvom əst.", "az": "Sizin eviniz neçənci mərtəbədədir? Bizim evimiz üçüncü mərtəbədədir."},
                {"fa": "شما فرزند چندمِ خانواده هستی؟ من فرزند چهارمِ خانواده هستم.", "reading_az": "Şoma fərzəde çəndome xanevade hasti? Mən fərzəde çəharome xanevade hastəm.", "az": "Sən ailənin neçənci övladısan? Mən ailənin dördüncü övladıyam."},
            ],
        },
    ],
    "exercises": [
        {
            "kind": "fill_blank",
            "instruction_az": "«چند» yoxsa «چندم» ilə tamamlayın.",
            "word_bank": ["چند", "چندم"],
            "items": [
                {
                    "fa_with_blank": "لیلا کتاب ___ را می‌خواند؟ کتاب پنجم.",
                    "correct_answer": "چندم",
                    "reading_az": "çəndom",
                    "az": "neçənci",
                    "full_reading_az": "Leyla ketabe çəndom ra mixanəd? Ketabe pəncom.",
                    "full_translation_az": "Leyla neçənci kitabı oxuyur? Beşinci kitabı.",
                },
                {
                    "fa_with_blank": "من هر روز، ___ بار غذا می‌خورم؟ سه بار.",
                    "correct_answer": "چند",
                    "reading_az": "çənd",
                    "az": "neçə",
                    "full_reading_az": "Mən hər ruz, çənd bar qəza mixorəm? Se bar.",
                    "full_translation_az": "Mən hər gün neçə dəfə yemək yeyirəm? Üç dəfə.",
                },
                {
                    "fa_with_blank": "اسم فرزند سومِ من، محمّد حسین است؛ او فرزند ___ من است؟",
                    "correct_answer": "چندم",
                    "reading_az": "çəndom",
                    "az": "neçənci",
                    "full_reading_az": "Esme fərzəde sevvome mən, Mohəmməd Hoseyn əst; u fərzəde çəndome mən əst?",
                    "full_translation_az": "Üçüncü övladımın adı Məhəmməd Hüseyndir; o mənim neçənci övladımdır?",
                },
                {
                    "fa_with_blank": "کلاس ما در طبقه‌ی ___ است؟ طبقه‌ی دوم.",
                    "correct_answer": "چندم",
                    "reading_az": "çəndom",
                    "az": "neçənci",
                    "full_reading_az": "Kelase ma dər təbəqeye çəndom əst? Təbəqeye dovvom.",
                    "full_translation_az": "Bizim sinfimiz neçənci mərtəbədədir? İkinci mərtəbədə.",
                },
                {
                    "fa_with_blank": "یک ماه، سی روز است. یک ماه ___ روز است؟",
                    "correct_answer": "چند",
                    "reading_az": "çənd",
                    "az": "neçə",
                    "full_reading_az": "Yek mah, si ruz əst. Yek mah çənd ruz əst?",
                    "full_translation_az": "Bir ay otuz gündür. Bir ay neçə gündür?",
                },
            ],
        },
        {
            "kind": "fill_blank",
            "instruction_az": "Ayları fəsillərə görə tamamlayın.",
            "word_bank": ["مهر", "اردیبهشت", "آبان", "بهمن", "اسفند"],
            "items": [
                {
                    "fa_with_blank": "ماه شهریور، بعد از ماه ___ است.",
                    "correct_answer": "مهر",
                    "reading_az": "Mehr",
                    "az": "Mehr",
                    "full_reading_az": "Mahe Şəhrivər, bəd əz mahe Mehr əst.",
                    "full_translation_az": "Şəhrivər ayı Mehr ayından sonradır.",
                },
                {
                    "fa_with_blank": "فروردین، قبل از ___ است.",
                    "correct_answer": "اردیبهشت",
                    "reading_az": "Ordibeheşt",
                    "az": "Ordibeheşt",
                    "full_reading_az": "Fərvərdin, qəbl əz Ordibeheşt əst.",
                    "full_translation_az": "Fərvərdin ayı Ordibeheştdən əvvəldir.",
                },
                {
                    "fa_with_blank": "ماه‌های فصل پاییز، مهر، ___ و آذر است.",
                    "correct_answer": "آبان",
                    "reading_az": "Aban",
                    "az": "Aban",
                    "full_reading_az": "Mahhaye fəsle payiz, Mehr, Aban va Azər əst.",
                    "full_translation_az": "Payızın ayları Mehr, Aban və Azərdir.",
                },
                {
                    "fa_with_blank": "ماه‌های فصل زمستان، دی، ___ و اسفند است.",
                    "correct_answer": "بهمن",
                    "reading_az": "Bəhmən",
                    "az": "Bəhmən",
                    "full_reading_az": "Mahhaye fəsle zemestan, Dey, Bəhmən va Esfənd əst.",
                    "full_translation_az": "Qışın ayları Dey, Bəhmən və Esfənddir.",
                },
                {
                    "fa_with_blank": "آخرین ماه سال، ___ است.",
                    "correct_answer": "اسفند",
                    "reading_az": "Esfənd",
                    "az": "Esfənd",
                    "full_reading_az": "Axərin mahe sal, Esfənd əst.",
                    "full_translation_az": "İlin son ayı Esfənddir.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "«چندم» ilə soruşub cavab verin: «شما فرزند چندمِ خانواده هستید؟ من فرزند سومِ خانواده هستم.»",
            "items": [
                {
                    "prompt_fa": "این کتاب / درس چندم / درس یازدهم",
                    "answer_fa": "این کتاب، درس چندم دارد؟ این کتاب، درس یازدهم را دارد.",
                    "reading_az": "İn ketab, dərse çəndom darəd? İn ketab, dərse yazdəhom ra darəd.",
                    "az": "Bu kitabın neçənci dərsi var? Bu kitabın on birinci dərsi var.",
                },
                {
                    "prompt_fa": "خانه‌ی شما / طبقه‌ی چندم / طبقه‌ی چهارم",
                    "answer_fa": "خانه‌ی شما در طبقه‌ی چندم است؟ خانه‌ی ما در طبقه‌ی چهارم است.",
                    "reading_az": "Xaneye şoma dər təbəqeye çəndom əst? Xaneye ma dər təbəqeye çəharom əst.",
                    "az": "Sizin eviniz neçənci mərtəbədədir? Bizim evimiz dördüncü mərtəbədədir.",
                },
                {
                    "prompt_fa": "امروز / روز چندمِ هفته / روز پنجم",
                    "answer_fa": "امروز روز چندمِ هفته است؟ امروز روز پنجمِ هفته است.",
                    "reading_az": "Emruz ruze çəndome həfte əst? Emruz ruze pəncome həfte əst.",
                    "az": "Bu gün həftənin neçənci günüdür? Bu gün həftənin beşinci günüdür.",
                },
                {
                    "prompt_fa": "بهمن / ماه چندمِ سال / ماه یازدهم",
                    "answer_fa": "بهمن ماه چندمِ سال است؟ بهمن ماه یازدهمِ سال است.",
                    "reading_az": "Bəhmən mahe çəndome sal əst? Bəhmən mahe yazdəhome sal əst.",
                    "az": "Bəhmən ilin neçənci ayıdır? Bəhmən ilin on birinci ayıdır.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi cümlə qurun: «زیباترین جا / دیدن → زیباترین جایی که دیدم، کوه دماوند بود.»",
            "items": [
                {
                    "prompt_fa": "بهترین کتاب / خواندن",
                    "answer_fa": "بهترین کتابی که خواندم، کتاب دوم فارسی بود.",
                    "reading_az": "Behtərin ketabi ke xandəm, ketabe dovvome farsi bud.",
                    "az": "Oxuduğum ən yaxşı kitab ikinci fars dili kitabı idi.",
                },
                {
                    "prompt_fa": "لذیذترین غذا / خوردن",
                    "answer_fa": "لذیذترین غذایی که خوردم، غذای مادرم بود.",
                    "reading_az": "Ləziztərin qəzayi ke xordəm, qəzaye madərəm bud.",
                    "az": "Yediyim ən dadlı yemək anamın yeməyi idi.",
                },
                {
                    "prompt_fa": "شلوغ‌ترین جادّه / دیدن",
                    "answer_fa": "شلوغ‌ترین جادّه‌ای که دیدم، جادّه‌ی شمال بود.",
                    "reading_az": "Şoluğtərin cadeyi ke didəm, cadeye şomal bud.",
                    "az": "Gördüyüm ən izdihamlı yol şimal yolu idi.",
                },
                {
                    "prompt_fa": "خوش‌بوترین گل / بوییدن",
                    "answer_fa": "خوش‌بوترین گلی که بوییدم، گل‌محمّدی بود.",
                    "reading_az": "Xoşbutərin qoli ke buyidəm, gole Mohəmmədi bud.",
                    "az": "İylədiyim ən ətirli gül Məhəmmədi gülü idi.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "«دربارهٔ» ilə cümlə qurun: «دوستم / کشور ایران / کتاب نوشتن → دوستم دربارهٔ کشور ایران کتاب می‌نویسد.»",
            "items": [
                {
                    "prompt_fa": "دوستانم / کوه دماوند / سؤال کردن",
                    "answer_fa": "دوستانم دربارهٔ کوه دماوند سؤال کردند.",
                    "reading_az": "Dustanəm dərbareye kuhe Dəmavənd soəl kərdənd.",
                    "az": "Dostlarım Dəmavənd dağı haqqında sual verdilər.",
                },
                {
                    "prompt_fa": "من / طبیعت ایران / مطالعه کردن",
                    "answer_fa": "من دربارهٔ طبیعت ایران مطالعه می‌کنم.",
                    "reading_az": "Mən dərbareye təbiəte Iran motaleə mikonəm.",
                    "az": "Mən İranın təbiəti haqqında mütaliə edirəm.",
                },
                {
                    "prompt_fa": "ما / امام حسین (ع) / انشا نوشتن",
                    "answer_fa": "ما دربارهٔ امام حسین (ع) انشا نوشتیم.",
                    "reading_az": "Ma dərbareye Emam Hoseyn ənşa neveştim.",
                    "az": "Biz İmam Hüseyn (ə) haqqında inşa yazdıq.",
                },
                {
                    "prompt_fa": "آن‌ها / کشورشان / گفت‌وگو کردن",
                    "answer_fa": "آن‌ها دربارهٔ کشورشان گفت‌وگو کردند.",
                    "reading_az": "Anha dərbareye kəşvəreşan goftogu kərdənd.",
                    "az": "Onlar öz ölkələri haqqında söhbət etdilər.",
                },
            ],
        },
    ],
    "sentence_practice": {
        "listen_exercises": [
            {
                "items": [
                    {
                        "fa": "در کوه و جنگل باران زیاد می‌بارد و در صحرا باران کم می‌بارد.",
                        "reading_az": "Dər kuh va cəngəl baran ziyad mibarəd va dər səhra baran kəm mibarəd.",
                        "az": "Dağda və meşədə çox yağış yağır, səhrada isə az yağır.",
                    },
                    {
                        "fa": "امدادگران هنگام آتش‌سوزی، آتش را خاموش می‌کنند و مردم را نجات می‌دهند.",
                        "reading_az": "Emdadgəran hengame atəşsuzi, atəş ra xamuş mikonənd va mərdom ra nəcat midəhənd.",
                        "az": "Xilasedicilər yanğın zamanı odu söndürür və insanları xilas edirlər.",
                    },
                    {
                        "fa": "من ساحل دریا و تماشاکردن آن را هنگام غروب خورشید دوست دارم.",
                        "reading_az": "Mən sahele dərya va təmaşakərdəne an ra hengame qorube xorşid dust daram.",
                        "az": "Mən dəniz sahilini və günəş batarkən ona tamaşa etməyi sevirəm.",
                    },
                    {
                        "fa": "حسین و خانواده‌اش برای گردش به جزیره‌ی کیش رفتند و سه روز آن‌جا ماندند.",
                        "reading_az": "Hoseyn va xanevadeəş bəraye gərdeş be cəzireye Kiş rəftənd va se ruz anja mandənd.",
                        "az": "Hüseyn və ailəsi gəzinti üçün Kiş adasına getdilər və orada üç gün qaldılar.",
                    },
                    {
                        "fa": "در بعضی از روستاها مردم از آب چاه‌ها برای خوردن و کشاورزی استفاده می‌کنند.",
                        "reading_az": "Dər bəzi əz rustaha mərdom əz abe çahha bəraye xordən va keşavərzi estefade mikonənd.",
                        "az": "Bəzi kəndlərdə insanlar quyu suyundan içmək və əkinçilik üçün istifadə edirlər.",
                    },
                    {
                        "fa": "در اطراف کوه دماوند درّه‌ها، آبشارها، چشمه‌ها و رودخانه‌های بسیار زیبا وجود دارد.",
                        "reading_az": "Dər ətrafe kuhe Dəmavənd dərreha, abşarha, çeşmeha va rudxanehaye besyar ziba vocud darəd.",
                        "az": "Dəmavənd dağının ətrafında çox gözəl dərələr, şəlalələr, bulaqlar və çaylar var.",
                    },
                    {
                        "fa": "دوستانم، پارسال در تعطیلات تابستان برای گردش به ساحل دریای خزر رفتند.",
                        "reading_az": "Dustanəm, parsal dər tətilate tabestan bəraye gərdeş be sahele dəryaye Xəzər rəftənd.",
                        "az": "Dostlarım keçən il yay tətilində gəzinti üçün Xəzər dənizi sahilinə getdilər.",
                    },
                    {
                        "fa": "هنگام آمدن سیل، بعضی از انسان‌ها غرق می‌شوند.",
                        "reading_az": "Hengame amədəne seyl, bəzi əz insanha qərq mişəvənd.",
                        "az": "Sel gələn zaman insanların bəzisi batır.",
                    },
                    {
                        "fa": "امدادگران هنگام زلزله و سیل به مردم کمک می‌کنند و آن‌ها را نجات می‌دهند.",
                        "reading_az": "Emdadgəran hengame zelzele va seyl be mərdom komək mikonənd va anha ra nəcat midəhənd.",
                        "az": "Xilasedicilər zəlzələ və sel zamanı insanlara kömək edir və onları xilas edirlər.",
                    },
                    {
                        "fa": "در بعضی از کوه‌ها، گیاهان گوناگون، مانند درخت، گُل، قارچ و... وجود دارد.",
                        "reading_az": "Dər bəzi əz kuhha, giyahane gunagun, manənde dərəxt, gol, qarç va... vocud darəd.",
                        "az": "Bəzi dağlarda ağac, gül, göbələk və s. kimi müxtəlif bitkilər var.",
                    },
                ],
            },
        ],
        "answer_items": [
            {
                "fa": "آیا در کشور شما دریا وجود دارد؟",
                "reading_az": "Aya dər kəşvəre şoma dərya vocud darəd?",
                "az": "Sizin ölkənizdə dəniz varmı?",
            },
            {
                "fa": "اسم بلندترین کوه در کشور شما چیست؟",
                "reading_az": "Esme boləndtərin kuh dər kəşvəre şoma çist?",
                "az": "Sizin ölkənizdəki ən uca dağın adı nədir?",
            },
            {
                "fa": "آیا در شهر یا روستای شما برف می‌بارد؟",
                "reading_az": "Aya dər şəhr ya rustaye şoma bərf mibarəd?",
                "az": "Sizin şəhərinizdə və ya kəndinizdə qar yağırmı?",
            },
            {
                "fa": "آیا هنگام بیرون رفتن از کلاس، لامپ‌ها را خاموش می‌کنید؟",
                "reading_az": "Aya hengame birun rəftən əz kelas, lampha ra xamuş mikonid?",
                "az": "Sinifdən çıxarkən lampaları söndürürsünüzmü?",
            },
        ],
    },
    "reading_text": {
        "title_fa": "دماوند",
        "title_az": "Dəmavənd",
        "paragraphs_fa": [
            "اسم من امیرحسین است. من اهل اندونزی هستم و در ایران درس می‌خوانم. سه ماه قبل برای دیدن خانواده و دوستان به کشورم رفتم. آن‌ها بسیاری از دوستان به دیدنم آمدند. یکی از آن‌ها دربارهٔ ایران از من سؤال کردند. آن‌ها دربارهٔ آب و هوا و طبیعت ایران پرسید.",
            "من به او گفتم: ایران دارای آب و هوا و طبیعت گوناگونی است. بعضی از جاهای ایران هوا سرد است. بعضی از جاها هوا گرم است و در بعضی از جاها هوا معتدل و خنک است. این کشور دارای جنگل‌ها، دشت‌ها، دریاها و دریاچه‌ها، چشمه‌ها و رودخانه‌ها، صحراها و کوه‌های زیباست.",
            "دوست دیگرم سؤال کرد: زیباترین جایی که در ایران دیدی، کجا بود؟ گفتم: زیباترین جایی که در ایران دیدم «کوه دماوند» بود. دماوند بلندترین کوه ایران و یکی از زیباترین کوه‌های جهان است. این کوه ۵۶۷۱ متر ارتفاع دارد و بین دو شهر تهران و آمل قرار دارد.",
            "مردم از شهرها و کشورهای گوناگون برای گردش و تفریح و دیدن منظره‌های زیبای این کوه و اطرافش به آن‌جا سفر می‌کنند. در مسیر دماوند، کوه‌ها، درّه‌ها، چشمه‌ها و رودخانه‌های زیادی وجود دارد. این مسیر به سبب زیبایی و نزدیک بودن به پایتخت، جنگل‌های شمال و دریاچه‌ی بزرگ مازندران یکی از شلوغ‌ترین جادّه‌های ایران در روزهای تعطیل است.",
            "دیدن قلّه‌ی پر از برف دماوند، رودخانه‌ها و آبشارهای مختلف، سدّ لار، دشت گل‌های شقایق، درّه‌ی گل زرد و چشمه‌های آب‌گرم، بسیار لذّت‌بخش است.",
        ],
        "footnotes": [
            {"fa": "معتدل", "az": "mülayim, mötədil"},
            {"fa": "دربارهٔ", "az": "…haqqında"},
            {"fa": "به سبب", "az": "…-ə görə"},
            {"fa": "لذّت‌بخش", "az": "ləzzətli"},
        ],
        "full_translation_az": (
            "Mənim adım Əmir Hüseyndir. Mən Endoneziyadanam və İranda oxuyuram. Üç ay əvvəl ailəmi və dostlarımı "
            "görmək üçün ölkəmə getdim. Dostlarımın çoxu mənimlə görüşməyə gəldi. Onlardan biri mənə İran "
            "haqqında sual verdi. O, İranın iqlimi və təbiəti haqqında soruşdu.\n\n"
            "Mən ona dedim: İranın müxtəlif iqlimi və təbiəti var. İranın bəzi yerlərində hava soyuqdur. Bəzi "
            "yerlərdə hava istidir, bəzi yerlərdə isə hava mülayim və sərindir. Bu ölkənin meşələri, düzənlikləri, "
            "dənizləri və gölləri, bulaqları və çayları, səhraları və gözəl dağları var.\n\n"
            "Başqa bir dostum soruşdu: İranda gördüyün ən gözəl yer haradır? Dedim: İranda gördüyüm ən gözəl yer "
            "«Dəmavənd dağı» idi. Dəmavənd İranın ən uca dağı və dünyanın ən gözəl dağlarından biridir. Bu dağın "
            "hündürlüyü 5671 metrdir və Tehran ilə Amol şəhərləri arasında yerləşir.\n\n"
            "İnsanlar müxtəlif şəhər və ölkələrdən gəzinti, əyləncə üçün və bu dağın və ətrafının gözəl "
            "mənzərələrini görmək üçün oraya səyahət edirlər. Dəmavəndin yolunda çoxlu dağ, dərə, bulaq və çay "
            "var. Bu marşrut gözəlliyinə və paytaxta, şimalın meşələrinə və böyük Mazandaran gölünə yaxın "
            "olmasına görə istirahət günlərində İranın ən izdihamlı yollarından biridir.\n\n"
            "Dəmavəndin qarla örtülü zirvəsini, müxtəlif çay və şəlalələri, Lar bəndini, şəqayiq gülləri "
            "düzənliyini, sarı gül dərəsini və isti su bulaqlarını görmək çox ləzzətlidir."
        ),
        "sentences": [
            {
                "fa": "اسم من امیرحسین است.",
                "reading_az": "Esme mən Əmirhoseyn əst.",
                "az": "Mənim adım Əmir Hüseyndir.",
                "new_paragraph": True,
            },
            {"fa": "من اهل اندونزی هستم و در ایران درس می‌خوانم.", "reading_az": "Mən əhle Ondonezi hastəm va dər Iran dərs mixanəm.", "az": "Mən Endoneziyadanam və İranda oxuyuram."},
            {"fa": "سه ماه قبل برای دیدن خانواده و دوستان به کشورم رفتم.", "reading_az": "Se mah qəbl bəraye didəne xanevade va dustan be kəşvərəm rəftəm.", "az": "Üç ay əvvəl ailəmi və dostlarımı görmək üçün ölkəmə getdim."},
            {"fa": "آن‌ها بسیاری از دوستان به دیدنم آمدند.", "reading_az": "Anha besyari əz dustan be didənəm amədənd.", "az": "Dostlarımın çoxu mənimlə görüşməyə gəldi."},
            {"fa": "یکی از آن‌ها دربارهٔ ایران از من سؤال کردند.", "reading_az": "Yeki əz anha dərbareye Iran əz mən soəl kərdənd.", "az": "Onlardan biri mənə İran haqqında sual verdi."},
            {"fa": "آن‌ها دربارهٔ آب و هوا و طبیعت ایران پرسید.", "reading_az": "Anha dərbareye abohəva va təbiəte Iran porsid.", "az": "O, İranın iqlimi və təbiəti haqqında soruşdu."},
            {
                "fa": "من به او گفتم: ایران دارای آب و هوا و طبیعت گوناگونی است.",
                "reading_az": "Mən be u goftəm: Iran daraye abohəva va təbiəte gunaguni əst.",
                "az": "Mən ona dedim: İranın müxtəlif iqlimi və təbiəti var.",
                "new_paragraph": True,
            },
            {"fa": "بعضی از جاهای ایران هوا سرد است.", "reading_az": "Bəzi əz cahaye Iran həva sərd əst.", "az": "İranın bəzi yerlərində hava soyuqdur."},
            {"fa": "بعضی از جاها هوا گرم است و در بعضی از جاها هوا معتدل و خنک است.", "reading_az": "Bəzi əz caha həva gərm əst va dər bəzi əz caha həva moetədel va xonək əst.", "az": "Bəzi yerlərdə hava istidir, bəzi yerlərdə isə hava mülayim və sərindir."},
            {"fa": "این کشور دارای جنگل‌ها، دشت‌ها، دریاها و دریاچه‌ها، چشمه‌ها و رودخانه‌ها، صحراها و کوه‌های زیباست.", "reading_az": "In kəşvər daraye cəngəlha, dəştha, dəryaha va dəryaçeha, çeşmeha va rudxaneha, səhraha va kuhhaye zibast.", "az": "Bu ölkənin meşələri, düzənlikləri, dənizləri və gölləri, bulaqları və çayları, səhraları və gözəl dağları var."},
            {
                "fa": "دوست دیگرم سؤال کرد: زیباترین جایی که در ایران دیدی، کجا بود؟",
                "reading_az": "Duste digərəm soəl kərd: Zibatərin cayi ke dər Iran didi, koca bud?",
                "az": "Başqa bir dostum soruşdu: İranda gördüyün ən gözəl yer haradır?",
                "new_paragraph": True,
            },
            {"fa": "گفتم: زیباترین جایی که در ایران دیدم «کوه دماوند» بود.", "reading_az": "Goftəm: Zibatərin cayi ke dər Iran didəm «kuhe Dəmavənd» bud.", "az": "Dedim: İranda gördüyüm ən gözəl yer «Dəmavənd dağı» idi."},
            {"fa": "دماوند بلندترین کوه ایران و یکی از زیباترین کوه‌های جهان است.", "reading_az": "Dəmavənd boləndtərin kuhe Iran va yeki əz zibatərin kuhhaye cəhan əst.", "az": "Dəmavənd İranın ən uca dağı və dünyanın ən gözəl dağlarından biridir."},
            {"fa": "این کوه ۵۶۷۱ متر ارتفاع دارد و بین دو شهر تهران و آمل قرار دارد.", "reading_az": "In kuh pənc hezar o şeşsəd o həftad o yek metr ertefa darəd va beyne do şəhre Tehran va Amol qərar darəd.", "az": "Bu dağın hündürlüyü 5671 metrdir və Tehran ilə Amol şəhərləri arasında yerləşir."},
            {
                "fa": "مردم از شهرها و کشورهای گوناگون برای گردش و تفریح و دیدن منظره‌های زیبای این کوه و اطرافش به آن‌جا سفر می‌کنند.",
                "reading_az": "Mərdom əz şəhrha va kəşvərhaye gunagun bəraye gərdeş va təfrih va didəne mənzərehaye zibaye in kuh va ətrafəş be anja səfər mikonənd.",
                "az": "İnsanlar müxtəlif şəhər və ölkələrdən gəzinti, əyləncə üçün və bu dağın və ətrafının gözəl mənzərələrini görmək üçün oraya səyahət edirlər.",
                "new_paragraph": True,
            },
            {"fa": "در مسیر دماوند، کوه‌ها، درّه‌ها، چشمه‌ها و رودخانه‌های زیادی وجود دارد.", "reading_az": "Dər məsire Dəmavənd, kuhha, dərreha, çeşmeha va rudxanehaye ziyadi vocud darəd.", "az": "Dəmavəndin yolunda çoxlu dağ, dərə, bulaq və çay var."},
            {
                "fa": "این مسیر به سبب زیبایی و نزدیک بودن به پایتخت، جنگل‌های شمال و دریاچه‌ی بزرگ مازندران یکی از شلوغ‌ترین جادّه‌های ایران در روزهای تعطیل است.",
                "reading_az": "In məsir be səbəbe zibayi va nəzdik budən be paytəxt, cəngəlhaye şomal va dəryaçeye bozorge Mazəndəran yeki əz şoluğtərin cadehaye Iran dər ruzhaye tətil əst.",
                "az": "Bu marşrut gözəlliyinə və paytaxta, şimalın meşələrinə və böyük Mazandaran gölünə yaxın olmasına görə istirahət günlərində İranın ən izdihamlı yollarından biridir.",
            },
            {
                "fa": "دیدن قلّه‌ی پر از برف دماوند، رودخانه‌ها و آبشارهای مختلف، سدّ لار، دشت گل‌های شقایق، درّه‌ی گل زرد و چشمه‌های آب‌گرم، بسیار لذّت‌بخش است.",
                "reading_az": "Didəne qolleye por əz bərfe Dəmavənd, rudxaneha va abşarhaye moxtəlef, sədde Lar, dəşte golhaye şəqayeq, dərreye gole zərd va çeşmehaye abgərm, besyar ləzzətbəxş əst.",
                "az": "Dəmavəndin qarla örtülü zirvəsini, müxtəlif çay və şəlalələri, Lar bəndini, şəqayiq gülləri düzənliyini, sarı gül dərəsini və isti su bulaqlarını görmək çox ləzzətlidir.",
                "new_paragraph": True,
            },
        ],
        "comprehension_questions": [
            {
                "question_fa": "دوستان امیرحسین از او چه سؤال‌هایی کردند؟",
                "reading_az": "Dustane Əmirhoseyn əz u çe soəlhayi kərdənd?",
                "az": "Əmir Hüseynin dostları ondan hansı sualları verdilər?",
                "sample_answer_fa": "دوستانش دربارهٔ آب و هوا و طبیعت ایران و زیباترین جایی که دیده بود، سؤال کردند.",
                "sample_answer_reading_az": "Dustanəş dərbareye abohəva va təbiəte Iran va zibatərin cayi ke dide bud, soəl kərdənd.",
                "sample_answer_az": "Dostları İranın iqlimi, təbiəti və gördüyü ən gözəl yer haqqında sual verdilər.",
            },
            {
                "question_fa": "امیرحسین درباره‌ی آب و هوا و طبیعت ایران چه گفت؟",
                "reading_az": "Əmirhoseyn dərbareye abohəva va təbiəte Iran çe goft?",
                "az": "Əmir Hüseyn İranın iqlimi və təbiəti haqqında nə dedi?",
                "sample_answer_fa": "او گفت ایران دارای آب و هوا و طبیعت گوناگونی است: بعضی جاها سرد، بعضی گرم و بعضی معتدل است.",
                "sample_answer_reading_az": "U goft Iran daraye abohəva va təbiəte gunaguni əst: bəzi caha sərd, bəzi gərm va bəzi moetədel əst.",
                "sample_answer_az": "O dedi ki, İranın müxtəlif iqlimi və təbiəti var: bəzi yerlər soyuq, bəzisi isti, bəzisi isə mülayimdir.",
            },
            {
                "question_fa": "کوه دماوند چند متر ارتفاع دارد و بین کدام شهرها قرار دارد؟",
                "reading_az": "Kuhe Dəmavənd çənd metr ertefa darəd va beyne kodam şəhrha qərar darəd?",
                "az": "Dəmavənd dağının hündürlüyü neçə metrdir və hansı şəhərlər arasında yerləşir?",
                "sample_answer_fa": "کوه دماوند ۵۶۷۱ متر ارتفاع دارد و بین دو شهر تهران و آمل قرار دارد.",
                "sample_answer_reading_az": "Kuhe Dəmavənd pənc hezar o şeşsəd o həftad o yek metr ertefa darəd va beyne do şəhre Tehran va Amol qərar darəd.",
                "sample_answer_az": "Dəmavənd dağının hündürlüyü 5671 metrdir və Tehran ilə Amol arasında yerləşir.",
            },
            {
                "question_fa": "سبب شلوغ بودن مسیر دماوند چیست؟",
                "reading_az": "Səbəbe şoluğ budəne məsire Dəmavənd çist?",
                "az": "Dəmavənd yolunun izdihamlı olmasının səbəbi nədir?",
                "sample_answer_fa": "این مسیر به سبب زیبایی و نزدیک بودن به پایتخت، جنگل‌های شمال و دریاچه‌ی مازندران شلوغ است.",
                "sample_answer_reading_az": "In məsir be səbəbe zibayi va nəzdik budən be paytəxt, cəngəlhaye şomal va dəryaçeye Mazəndəran şoluğ əst.",
                "sample_answer_az": "Bu yol gözəlliyinə və paytaxta, şimal meşələrinə və Mazandaran gölünə yaxın olmasına görə izdihamlıdır.",
            },
            {
                "question_fa": "دیدن چه چیزهایی در اطراف دماوند لذّت‌بخش است؟",
                "reading_az": "Didəne çe çizhayi dər ətrafe Dəmavənd ləzzətbəxş əst?",
                "az": "Dəmavəndin ətrafında nələri görmək ləzzətlidir?",
                "sample_answer_fa": "دیدن قلّه‌ی پر از برف، رودخانه‌ها و آبشارها، سدّ لار، دشت گل شقایق و چشمه‌های آب‌گرم لذّت‌بخش است.",
                "sample_answer_reading_az": "Didəne qolleye por əz bərf, rudxaneha va abşarha, sədde Lar, dəşte gole şəqayeq va çeşmehaye abgərm ləzzətbəxş əst.",
                "sample_answer_az": "Qarlı zirvəni, çay və şəlalələri, Lar bəndini, şəqayiq gülləri düzənliyini və isti su bulaqlarını görmək ləzzətlidir.",
            },
            {
                "question_fa": "امیرحسین درباره‌ی زیباترین جای ایران به دوستش چه گفت؟",
                "reading_az": "Əmirhoseyn dərbareye zibatərin caye Iran be dustəş çe goft?",
                "az": "Əmir Hüseyn İranın ən gözəl yeri haqqında dostuna nə dedi?",
                "sample_answer_fa": "او گفت زیباترین جایی که در ایران دیده، کوه دماوند بوده است.",
                "sample_answer_reading_az": "U goft zibatərin cayi ke dər Iran dide, kuhe Dəmavənd bude əst.",
                "sample_answer_az": "O dedi ki, İranda gördüyü ən gözəl yer Dəmavənd dağı olub.",
            },
        ],
    },
}
