# Dərs 7 — پوشاک (لباس) (Geyim)
# Mənbə: کتاب دوم, səh. 87-98

LESSON = {
    "number": 7,
    "title_fa": "پوشاک (لباس)",
    "title_az": "Geyim",
    "available": True,
    "vocabulary": [
        {"fa": "پوشاک مردانه", "reading": "puşake mərdane", "az": "Kişi geyimi"},
        {"fa": "پوشاک زنانه", "reading": "puşake zənane", "az": "Qadın geyimi"},
        {"fa": "پوشاک بچّگانه", "reading": "puşake bəççeqane", "az": "Uşaq geyimi"},
        {"fa": "چادر", "reading": "çador", "az": "Çadra"},
        {"fa": "روسری", "reading": "rusəri", "az": "Baş örtüyü (yaylıq)"},
        {"fa": "مقنعه", "reading": "məqnəe", "az": "Hicab (məqnəə)"},
        {"fa": "مانتو", "reading": "manto", "az": "Manto"},
        {"fa": "پالتو", "reading": "palto", "az": "Palto"},
        {"fa": "کاپشن", "reading": "kapşen", "az": "Gödəkcə (kurtka)"},
        {"fa": "بلوز", "reading": "boluz", "az": "Bluz (sviter)"},
        {"fa": "زیرپوش", "reading": "zirpuş", "az": "Alt köynəyi (mayka)"},
        {"fa": "شورت", "reading": "şort", "az": "Alt paltarı (şort)"},
        {"fa": "چکمه", "reading": "çəkme", "az": "Çəkmə"},
        {"fa": "دمپایی", "reading": "dəmpayi", "az": "Şəpşəp (ev ayaqqabısı)"},
        {"fa": "کفش", "reading": "kəfş", "az": "Ayaqqabı"},
        {"fa": "کمربند", "reading": "kəmərbənd", "az": "Kəmər"},
        {"fa": "دست‌کش", "reading": "dəstkeş", "az": "Əlcək"},
        {"fa": "ضخیم", "reading": "zəxim", "az": "Qalın"},
        {"fa": "نازک", "reading": "nazok", "az": "Nazik"},
        {"fa": "شال", "reading": "şal", "az": "Şal"},
        {"fa": "آستین", "reading": "astin", "az": "Qol (paltarın qolu)"},
        {"fa": "یقه", "reading": "yəqe", "az": "Yaxa"},
        {"fa": "دکمه", "reading": "dokme", "az": "Düymə"},
        {"fa": "زیپ", "reading": "zip", "az": "Zəncirbənd"},
        {"fa": "انتخاب می‌کند", "reading": "entexab mikonəd", "az": "seçir"},
        {"fa": "اتو می‌زند", "reading": "otu mizənəd", "az": "ütüləyir"},
        {"fa": "می‌پوشد", "reading": "mipuşəd", "az": "geyinir"},
        {"fa": "درمی‌آورد", "reading": "dərmiavərəd", "az": "çıxarır (əynindən)"},
        {"fa": "شلوغ", "reading": "şoluğ", "az": "İzdihamlı, qələbəlik"},
        {"fa": "خلوت", "reading": "xəlvət", "az": "Sakit, boş"},
        {"fa": "هنگام", "reading": "hengam", "az": "…zamanı, vaxtı"},
        {"fa": "نو", "reading": "nou", "az": "Təzə"},
        {"fa": "قدیمی", "reading": "qədimi", "az": "Köhnə, qədim"},
        {"fa": "چوب‌لباسی", "reading": "çublebasi", "az": "Paltarasan"},
        {"fa": "آویزان می‌کند", "reading": "avizan mikonəd", "az": "asır"},
    ],
    "grammar_notes": [
        {
            "title_az": "Cəm şəkilçiləri «ها» və «ان»",
            "title_fa": "نشانه‌های جمع «ها» و «ان»",
            "conjugations": [
                {"pronoun_fa": "پسر", "form_fa": "پسرها / پسران"},
                {"pronoun_fa": "شتر", "form_fa": "شترها / شتران"},
                {"pronoun_fa": "درخت", "form_fa": "درخت‌ها / درختان"},
                {"pronoun_fa": "لباس (cansız)", "form_fa": "لباس‌ها ✓ (لباسان ✗)"},
            ],
            "examples": [
                {"fa": "«ها» برای جمع همه‌ی اسم‌ها استفاده می‌شود: استادها؛ دفترها؛ اسب‌ها.", "reading_az": "Ha: ostadha; dəftərha; əsbha.", "az": "«ها» bütün isimlərin cəmində işlənir: müəllimlər, dəftərlər, atlar."},
                {"fa": "«ان» معمولاً برای جمع اسم جان‌داران: زنان؛ مردان؛ دختران؛ پسران؛ کودکان؛ مرغان؛ شیران؛ درختان.", "reading_az": "An: zənan; mərdan; doxtəran; pesəran; kudəkan; morğan; şiran; dərəxtan.", "az": "«ان» adətən canlıların cəmində işlənir: qadınlar, kişilər, qızlar, oğlanlar, uşaqlar."},
                {"fa": "آن‌آقا هر روز پلّه‌های مدرسه را تمیز و جارو می‌کند.", "reading_az": "An ağa hər ruz pellehaye mædrese ra təmiz va caru mikonəd.", "az": "O kişi hər gün məktəbin pillələrini təmizləyir və süpürür."},
                {"fa": "چادر، روسری، مقنعه و مانتو لباس‌های زنانه هستند.", "reading_az": "Çador, rusəri, məqnəe va manto lebashaye zənane həstənd.", "az": "Çadra, yaylıq, məqnəə və manto qadın geyimləridir."},
                {"fa": "صادق به بازار می‌رود و برای فرزندانش لباس‌های زیبا انتخاب می‌کند و می‌خرد.", "reading_az": "Sadeq be bazar mirəvəd va bəraye fərzəndanəş lebashaye ziba entexab mikonəd va mixərəd.", "az": "Sadiq bazara gedir və övladları üçün gözəl paltarlar seçib alır."},
                {"fa": "آن‌ها دانش‌آموزان این مدرسه هستند. آن دانش‌آموزها در کلاس اوّل درس می‌خوانند.", "reading_az": "Anha daneşamuzane in mædrese həstənd. An daneşamuzha dər kelase əvvəl dərs mixanənd.", "az": "Onlar bu məktəbin şagirdləridir. O şagirdlər birinci sinifdə oxuyurlar."},
                {"fa": "رستورانِ سعید در خیابان فلسطین است. دوستان من در آن رستوران کار می‌کنند.", "reading_az": "Restorane Səid dər xiyabane Fələstin əst. Dustane mən dər an restoran kar mikonənd.", "az": "Səidin restoranı Fələstin küçəsindədir. Mənim dostlarım o restoranda işləyirlər."},
                {"fa": "آن خانم‌ها پزشک هستند. آن پزشکان در بیمارستان امام خمینی تهران کار می‌کنند.", "reading_az": "An xanomha pezeşk həstənd. An pezeşkan dər bimarestane Emam Xomeyniye Tehran kar mikonənd.", "az": "O xanımlar həkimdir. O həkimlər Tehranın İmam Xomeyni xəstəxanasında işləyirlər."},
                {"fa": "در جنگل، درختان و حیوان‌های زیادی وجود دارد.", "reading_az": "Dər cəngəl, dərəxtan va heyvanhaye ziyadi vocud darəd.", "az": "Meşədə çoxlu ağac və heyvan var."},
                {"fa": "فرزندان شما پسرند یا دختر؟ من یک فرزند پسر به نام علی و دو فرزند دختر به نام‌های فاطمه و زینب دارم.", "reading_az": "Fərzəndane şoma pesərand ya doxtər? Mən yek fərzəde pesər be name Əli va do fərzəde doxtər be namhaye Fateme va Zeynəb daram.", "az": "Sizin övladlarınız oğlandır, yoxsa qız? Mənim Əli adında bir oğlum, Fatimə və Zeynəb adında iki qızım var."},
            ],
            "drills": [
                {
                    "title_fa": "مانند مثال جمله بسازید",
                    "instruction_az": 'Nümunə kimi cümlə qurun: "خیّاط / لباس / اتو زدن → خیّاط‌ها، لباس‌ها را اتو می‌زنند."',
                    "items": [
                        {"prompt_fa": "آن پسر / کفش / پوشیدن", "answer_fa": "آن پسرها، کفش‌ها را می‌پوشند.", "reading_az": "An pesərha, kəfşha ra mipuşənd.", "az": "O oğlanlar ayaqqabıları geyinirlər."},
                        {"prompt_fa": "استاد / دانش‌جو / درس دادن", "answer_fa": "استادها، به دانش‌جوها درس می‌دهند.", "reading_az": "Ostadha, be daneşcuha dərs midəhənd.", "az": "Müəllimlər tələbələrə dərs deyirlər."},
                        {"prompt_fa": "جوان / پیر / کمک کردن", "answer_fa": "جوان‌ها، به پیرها کمک می‌کنند.", "reading_az": "Cavanha, be pirha komək mikonənd.", "az": "Cavanlar qocalara kömək edirlər."},
                        {"prompt_fa": "رنگ‌کار / دیوار / رنگ زدن", "answer_fa": "رنگ‌کارها، دیوارها را رنگ می‌زنند.", "reading_az": "Rəngkarha, divarha ra rəng mizənənd.", "az": "Rəngsazlar divarları rəngləyirlər."},
                        {"prompt_fa": "پزشک / بیمار / معاینه کردن", "answer_fa": "پزشک‌ها، بیمارها را معاینه می‌کنند.", "reading_az": "Pezeşkha, bimarha ra moayene mikonənd.", "az": "Həkimlər xəstələri müayinə edirlər."},
                        {"prompt_fa": "مادر / فرزند / دوست داشتن", "answer_fa": "مادرها، فرزندانشان را دوست دارند.", "reading_az": "Madərha, fərzəndanəşan ra dust darənd.", "az": "Analar övladlarını sevirlər."},
                    ],
                },
            ],
        },
        {
            "title_az": "Cəm mübtəda və feli (نهادِ جمع و فعل آن)",
            "title_fa": "نهادِ جمع و فعل آن",
            "conjugations": [
                {"pronoun_fa": "دانش‌آموزها در کلاس هستند. ✓", "form_fa": "دانش‌آموزها در کلاس است. ✗"},
                {"pronoun_fa": "این صندلی‌ها تمیز هستند. ✓", "form_fa": "این صندلی‌ها تمیز است. ✓ (cansız üçün hər ikisi olar)"},
            ],
            "examples": [
                {"fa": "این کاغذها سفید هستند. = این کاغذها سفید است.", "reading_az": "İn kağəzha sefid həstənd. = İn kağəzha sefid əst.", "az": "Cansız isimlərdə fel həm cəm, həm tək ola bilər: bu kağızlar ağdır."},
                {"fa": "این دخترها مانتو می‌پوشند. (این دخترها مانتو می‌پوشد ✗)", "reading_az": "İn doxtərha manto mipuşənd.", "az": "Canlı mübtəda cəm olanda fel mütləq cəm olur: bu qızlar manto geyinirlər."},
                {"fa": "پزشکان، بیماران را معاینه می‌کنند. (معاینه می‌کند ✗)", "reading_az": "Pezeşkan, bimaran ra moayene mikonənd.", "az": "Həkimlər xəstələri müayinə edirlər."},
                {"fa": "کارگران بیل و تیشه دارند.", "reading_az": "Kargəran bil va tişe darənd.", "az": "Fəhlələrin beli və külüngü var."},
                {"fa": "جوانان به پیرمردها کمک می‌کنند.", "reading_az": "Cəvanan be pirmərdha komək mikonənd.", "az": "Gənclər qocalara kömək edirlər."},
                {"fa": "آن کودکان درس می‌خوانند و تکلیف می‌نویسند.", "reading_az": "An kudəkan dərs mixanənd va təklif minevisənd.", "az": "O uşaqlar dərs oxuyur və tapşırıq yazırlar."},
            ],
            "drills": [
                {
                    "title_fa": "جمله‌های اشتباه را تصحیح کنید",
                    "instruction_az": "Səhv cümlələri düzəldin (cəm mübtəda → cəm fel)",
                    "items": [
                        {"prompt_fa": "کارگران بیل و تیشه دارد.", "answer_fa": "کارگران بیل و تیشه دارند.", "reading_az": "Kargəran bil va tişe darənd.", "az": "Fəhlələrin beli və külüngü var."},
                        {"prompt_fa": "جوانان به پیرمردها کمک می‌کند.", "answer_fa": "جوانان به پیرمردها کمک می‌کنند.", "reading_az": "Cəvanan be pirmərdha komək mikonənd.", "az": "Gənclər qocalara kömək edirlər."},
                        {"prompt_fa": "آن کودکان درس می‌خواند و تکلیف می‌نویسد.", "answer_fa": "آن کودکان درس می‌خوانند و تکلیف می‌نویسند.", "reading_az": "An kudəkan dərs mixanənd va təklif minevisənd.", "az": "O uşaqlar dərs oxuyur və tapşırıq yazırlar."},
                    ],
                },
            ],
        },
        {
            "title_az": "Deyək — deməyək: برادرِ من (mənim qardaşım) fel uzlaşması",
            "title_fa": "بگوییم – نگوییم",
            "conjugations": [
                {"pronoun_fa": "برادر من درس فارسی می‌خواند. ✓", "form_fa": "برادر من درس فارسی می‌خوانم. ✗"},
                {"pronoun_fa": "برادرهای ما درس فارسی می‌خوانند. ✓", "form_fa": "برادرهای ما درس فارسی می‌خوانیم. ✗"},
            ],
            "examples": [
                {"fa": "من عکّاس هستم. برادر من خیّاط است.", "reading_az": "Mən əkkas hastəm. Bəradəre mən xəyyat əst.", "az": "Mən fotoqrafam. Mənim qardaşım dərzidir — fel «brat»la uzlaşır, «mən»lə yox."},
                {"fa": "شما مهندس هستی. خواهرت دانش‌آموز است و برادرانت دانش‌جو هستند.", "reading_az": "Şoma mohəndes hasti. Xahərət daneşamuz əst va bəradəranət daneşcu həstənd.", "az": "Sən mühəndissən. Bacın şagirddir, qardaşların isə tələbədirlər."},
                {"fa": "دوستان شما پالتو می‌پوشند یا کاپشن؟ دوستان ما گاهی پالتو و گاهی کاپشن می‌پوشند.", "reading_az": "Dustane şoma palto mipuşənd ya kapşen? Dustane ma gahi palto va gahi kapşen mipuşənd.", "az": "Sizin dostlarınız palto geyinirlər, yoxsa gödəkcə? Dostlarımız bəzən palto, bəzən gödəkcə geyinirlər."},
            ],
            "drills": [
                {
                    "title_fa": "تصحیح کنید",
                    "instruction_az": "Səhv cümlələri düzəldin (fel uzlaşması)",
                    "items": [
                        {"prompt_fa": "استادِ شما درس می‌دهید.", "answer_fa": "استادِ شما درس می‌دهد.", "reading_az": "Ostade şoma dərs midəhəd.", "az": "Sizin müəlliminiz dərs deyir."},
                        {"prompt_fa": "فرزندان ما دندان‌پزشک هستیم.", "answer_fa": "فرزندان ما دندان‌پزشک هستند.", "reading_az": "Fərzəndane ma dəndanpezeşk həstənd.", "az": "Övladlarımız diş həkimidir."},
                        {"prompt_fa": "دوستان او لباس‌ها را اتو می‌زند.", "answer_fa": "دوستان او لباس‌ها را اتو می‌زنند.", "reading_az": "Dustane u lebasha ra otu mizənənd.", "az": "Onun dostları paltarları ütüləyirlər."},
                        {"prompt_fa": "هم‌کلاس من این پیراهن را می‌پوشم.", "answer_fa": "هم‌کلاس من این پیراهن را می‌پوشد.", "reading_az": "Həmkelase mən in pirahən ra mipuşəd.", "az": "Mənim sinif yoldaşım bu köynəyi geyinir."},
                    ],
                },
            ],
        },
    ],
    "exercises": [
        {
            "kind": "fill_blank",
            "instruction_az": "Düzgün söz və ya sözlərlə tamamlayın.",
            "word_bank": ["کتاب‌ها", "خانم", "هستند", "کودکان", "می‌پزند", "دارند"],
            "items": [
                {
                    "fa_with_blank": "این ___ رنگی است.",
                    "correct_answer": "کتاب‌ها",
                    "reading_az": "ketabha",
                    "az": "kitablar",
                    "full_reading_az": "İn ketabha rəngi əst.",
                    "full_translation_az": "Bu kitablar rənglidir.",
                },
                {
                    "fa_with_blank": "آن ___ ، لباس می‌دوزد.",
                    "correct_answer": "خانم",
                    "reading_az": "xanom",
                    "az": "xanım",
                    "full_reading_az": "An xanom, lebas miduzəd.",
                    "full_translation_az": "O xanım paltar tikir.",
                },
                {
                    "fa_with_blank": "آن کفش‌ها زنانه ___ .",
                    "correct_answer": "هستند",
                    "reading_az": "həstənd",
                    "az": "-dır",
                    "full_reading_az": "An kəfşha zənane həstənd.",
                    "full_translation_az": "O ayaqqabılar qadın ayaqqabısıdır.",
                },
                {
                    "fa_with_blank": "این ___ ، آبرنگ می‌خواهند.",
                    "correct_answer": "کودکان",
                    "reading_az": "kudəkan",
                    "az": "uşaqlar",
                    "full_reading_az": "İn kudəkan, abrəng mixahənd.",
                    "full_translation_az": "Bu uşaqlar akvarel istəyirlər.",
                },
                {
                    "fa_with_blank": "آشپزها در آشپزخانه غذا ___ .",
                    "correct_answer": "می‌پزند",
                    "reading_az": "mipəzənd",
                    "az": "bişirirlər",
                    "full_reading_az": "Aşpəzha dər aşpəzxane qəza mipəzənd.",
                    "full_translation_az": "Aşpazlar mətbəxdə yemək bişirirlər.",
                },
                {
                    "fa_with_blank": "آن پیراهن‌ها آستین و یقه ___ .",
                    "correct_answer": "دارند",
                    "reading_az": "darənd",
                    "az": "var",
                    "full_reading_az": "An pirahənha astin va yəqe darənd.",
                    "full_translation_az": "O köynəklərin qolu və yaxası var.",
                },
            ],
        },
        {
            "kind": "fill_blank",
            "instruction_az": "Uyğun fellə tamamlayın.",
            "word_bank": ["اتو می‌زنند", "انتخاب می‌کند", "می‌گذارد", "می‌شوید", "می‌کنند"],
            "items": [
                {
                    "fa_with_blank": "دوستان ما لباس‌ها را اتو ___ .",
                    "correct_answer": "اتو می‌زنند",
                    "reading_az": "otu mizənənd",
                    "az": "ütüləyirlər",
                    "full_reading_az": "Dustane ma lebasha ra otu mizənənd.",
                    "full_translation_az": "Dostlarımız paltarları ütüləyirlər.",
                },
                {
                    "fa_with_blank": "برادرت کدام کلاه را انتخاب ___ ؟",
                    "correct_answer": "انتخاب می‌کند",
                    "reading_az": "entexab mikonəd",
                    "az": "seçir",
                    "full_reading_az": "Bəradərət kodam kolah ra entexab mikonəd?",
                    "full_translation_az": "Qardaşın hansı papağı seçir?",
                },
                {
                    "fa_with_blank": "خواهر من لباس‌ها را در لباس‌شویی ___ .",
                    "correct_answer": "می‌گذارد",
                    "reading_az": "migozarəd",
                    "az": "qoyur",
                    "full_reading_az": "Xahəre mən lebasha ra dər ləbasşuyi migozarəd.",
                    "full_translation_az": "Bacım paltarları paltaryuyana qoyur.",
                },
                {
                    "fa_with_blank": "خواهر من لباس‌ها را با لباس‌شویی ___ .",
                    "correct_answer": "می‌شوید",
                    "reading_az": "mişuyəd",
                    "az": "yuyur",
                    "full_reading_az": "Xahəre mən lebasha ra ba ləbasşuyi mişuyəd.",
                    "full_translation_az": "Bacım paltarları paltaryuyanla yuyur.",
                },
                {
                    "fa_with_blank": "آیا دوستانتان در تمیزکردن اتاق به شما کمک ___ ؟",
                    "correct_answer": "می‌کنند",
                    "reading_az": "mikonənd",
                    "az": "edirlər",
                    "full_reading_az": "Aya dustanetan dər təmiz-kərdəne otaq be şoma komək mikonənd?",
                    "full_translation_az": "Dostlarınız otağı təmizləməkdə sizə kömək edirlərmi?",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi əvəz edin: «علی پیراهنش را درمی‌آورد و ژاکت می‌پوشد. — من / کاپشن / پالتو → من کاپشنم را درمی‌آورم و پالتو می‌پوشم.»",
            "items": [
                {
                    "prompt_fa": "ما / کفش / دمپایی",
                    "answer_fa": "ما کفش‌هایمان را درمی‌آوریم و دمپایی می‌پوشیم.",
                    "reading_az": "Ma kəfşhayeman ra dərmiavərim va dəmpayi mipuşim.",
                    "az": "Biz ayaqqabılarımızı çıxarırıq və şəpşəp geyinirik.",
                },
                {
                    "prompt_fa": "من / جوراب نازک / جوراب ضخیم",
                    "answer_fa": "من جوراب نازکم را درمی‌آورم و جوراب ضخیم می‌پوشم.",
                    "reading_az": "Mən curabe nazokəm ra dərmiavəram va curabe zəxim mipuşəm.",
                    "az": "Mən nazik corabımı çıxarıram və qalın corab geyinirəm.",
                },
                {
                    "prompt_fa": "شما / پیراهن / بلوز",
                    "answer_fa": "شما پیراهنتان را درمی‌آورید و بلوز می‌پوشید.",
                    "reading_az": "Şoma pirahənetan ra dərmiavərid va boluz mipuşid.",
                    "az": "Siz köynəyinizi çıxarırsınız və bluz geyinirsiniz.",
                },
                {
                    "prompt_fa": "او / پیراهن آستین‌کوتاه / پیراهن آستین‌بلند",
                    "answer_fa": "او پیراهن آستین‌کوتاهش را درمی‌آورد و پیراهن آستین‌بلند می‌پوشد.",
                    "reading_az": "U pirahəne astin-kutaheş ra dərmiavərəd va pirahəne astin-bolənd mipuşəd.",
                    "az": "O, qısaqollu köynəyini çıxarır və uzunqollu köynək geyinir.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi əvəz edin: «شما از خودکار آبی استفاده می‌کنید. (استاد شما) → استاد شما از خودکار آبی استفاده می‌کند.»",
            "items": [
                {
                    "prompt_fa": "آن‌ها اتاق را تمیز می‌کنند. (دوست آن‌ها)",
                    "answer_fa": "دوست آن‌ها اتاق را تمیز می‌کند.",
                    "reading_az": "Duste anha otaq ra təmiz mikonəd.",
                    "az": "Onların dostu otağı təmizləyir.",
                },
                {
                    "prompt_fa": "من روسری قهوه‌ای را انتخاب می‌کنم. (مادر من)",
                    "answer_fa": "مادر من روسری قهوه‌ای را انتخاب می‌کند.",
                    "reading_az": "Madəre mən rusəriye qəhvei ra entexab mikonəd.",
                    "az": "Anam qəhvəyi baş örtüyünü seçir.",
                },
                {
                    "prompt_fa": "شما لباس‌ها را می‌شویی و اتو می‌زنی. (همسر شما)",
                    "answer_fa": "همسر شما لباس‌ها را می‌شوید و اتو می‌زند.",
                    "reading_az": "Həmsəre şoma lebasha ra mişuyəd va otu mizənəd.",
                    "az": "Sizin həyat yoldaşınız paltarları yuyur və ütüləyir.",
                },
                {
                    "prompt_fa": "ما در زمستان لباس‌های نازک را درمی‌آوریم و لباس‌های ضخیم می‌پوشیم. (دوستان ما)",
                    "answer_fa": "دوستان ما در زمستان لباس‌های نازک را درمی‌آورند و لباس‌های ضخیم می‌پوشند.",
                    "reading_az": "Dustane ma dər zemestan lebashaye nazok ra dərmiavərənd va lebashaye zəxim mipuşənd.",
                    "az": "Dostlarımız qışda nazik paltarları çıxarır və qalın paltarlar geyinirlər.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "«هنگام» sözü ilə cümlə qurun: «من / درس خواندن / اتاق مطالعه / رفتن → من هنگام درس خواندن به اتاق مطالعه می‌روم.»",
            "items": [
                {
                    "prompt_fa": "دوستم / ظرف شستن / مادرش / کمک کردن",
                    "answer_fa": "دوستم هنگام ظرف شستن به مادرش کمک می‌کند.",
                    "reading_az": "Dustəm hengame zərf-şostən be madərəş komək mikonəd.",
                    "az": "Dostum qab yuyarkən anasına kömək edir.",
                },
                {
                    "prompt_fa": "استاد / درس دادن / تابلو و ماژیک / استفاده کردن",
                    "answer_fa": "استاد هنگام درس دادن از تابلو و ماژیک استفاده می‌کند.",
                    "reading_az": "Ostad hengame dərs-dadən əz təblo va majik estefade mikonəd.",
                    "az": "Müəllim dərs deyərkən lövhə və markerdən istifadə edir.",
                },
                {
                    "prompt_fa": "ما / عید / لباس‌های نو / انتخاب کردن و خریدن",
                    "answer_fa": "ما هنگام عید لباس‌های نو انتخاب می‌کنیم و می‌خریم.",
                    "reading_az": "Ma hengame eyd lebashaye nou entexab mikonim va mixərim.",
                    "az": "Biz bayram vaxtı təzə paltarlar seçib alırıq.",
                },
                {
                    "prompt_fa": "آن‌ها / زمستان / لباس‌های ضخیم / خریدن و پوشیدن",
                    "answer_fa": "آن‌ها هنگام زمستان لباس‌های ضخیم می‌خرند و می‌پوشند.",
                    "reading_az": "Anha hengame zemestan lebashaye zəxim mixərənd va mipuşənd.",
                    "az": "Onlar qış vaxtı qalın paltarlar alıb geyinirlər.",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "Nümunə kimi əvəz edin: «من پیراهن سفید را برای پوشیدن انتخاب می‌کنم.»",
            "items": [
                {
                    "prompt_fa": "شما / خودکار آبی / نوشتن",
                    "answer_fa": "شما خودکار آبی را برای نوشتن انتخاب می‌کنید.",
                    "reading_az": "Şoma xodkare abi ra bəraye neveştən entexab mikonid.",
                    "az": "Siz yazmaq üçün mavi tükənməz qələmi seçirsiniz.",
                },
                {
                    "prompt_fa": "آن‌ها / جامعة المصطفی / درس خواندن",
                    "answer_fa": "آن‌ها جامعة المصطفی را برای درس خواندن انتخاب می‌کنند.",
                    "reading_az": "Anha Cameətol-Mostəfa ra bəraye dərs-xandən entexab mikonənd.",
                    "az": "Onlar oxumaq üçün əl-Müstəfa Cəmiyyətini seçirlər.",
                },
                {
                    "prompt_fa": "مادرم / این فروش‌گاه / خریدن پوشاک",
                    "answer_fa": "مادرم این فروش‌گاه را برای خریدن پوشاک انتخاب می‌کند.",
                    "reading_az": "Madərəm in foruşgah ra bəraye xəridəne puşak entexab mikonəd.",
                    "az": "Anam geyim almaq üçün bu mağazanı seçir.",
                },
                {
                    "prompt_fa": "فرزندان او / مقوّای رنگی / نقّاشی کشیدن",
                    "answer_fa": "فرزندان او مقوّای رنگی را برای نقّاشی کشیدن انتخاب می‌کنند.",
                    "reading_az": "Fərzəndane u moqəvvaye rəngi ra bəraye nəqqaşi-keşidən entexab mikonənd.",
                    "az": "Onun övladları rəsm çəkmək üçün rəngli kartonu seçirlər.",
                },
                {
                    "prompt_fa": "برادرم / اداره‌ی پست / کارکردن",
                    "answer_fa": "برادرم اداره‌ی پست را برای کارکردن انتخاب می‌کند.",
                    "reading_az": "Bəradərəm edareye post ra bəraye kar-kərdən entexab mikonəd.",
                    "az": "Qardaşım işləmək üçün poçt idarəsini seçir.",
                },
                {
                    "prompt_fa": "پدرم / آن بنّا / ساختن خانه",
                    "answer_fa": "پدرم آن بنّا را برای ساختن خانه انتخاب می‌کند.",
                    "reading_az": "Pedərəm an bənna ra bəraye saxtəne xane entexab mikonəd.",
                    "az": "Atam ev tikmək üçün o bənnanı seçir.",
                },
            ],
        },
    ],
    "sentence_practice": {
        "listen_exercises": [
            {
                "items": [
                    {
                        "fa": "سارا و یاسر در فروش‌گاه پوشاک کار می‌کنند. آن‌ها لباس‌های زنانه و مردانه می‌فروشند.",
                        "reading_az": "Sara va Yasər dər foruşgahe puşak kar mikonənd. Anha lebashaye zənane va mərdane miforuşənd.",
                        "az": "Sara və Yasər geyim mağazasında işləyirlər. Onlar qadın və kişi geyimləri satırlar.",
                    },
                    {
                        "fa": "پدرم برای من دو پیراهنِ آستین بلند و یک پیراهن آستین کوتاه می‌خرد.",
                        "reading_az": "Pedərəm bəraye mən do pirahəne astin-bolənd va yek pirahəne astin-kutah mixərəd.",
                        "az": "Atam mənə iki uzunqollu köynək və bir qısaqollu köynək alır.",
                    },
                    {
                        "fa": "من در خانه زیرپوش یا پیراهن آستین‌کوتاه و بیرون از خانه پیراهن آستین بلند می‌پوشم.",
                        "reading_az": "Mən dər xane zirpuş ya pirahəne astin-kutah va birun əz xane pirahəne astin-bolənd mipuşəm.",
                        "az": "Mən evdə alt köynəyi və ya qısaqollu köynək, evdən bayırda isə uzunqollu köynək geyinirəm.",
                    },
                    {
                        "fa": "علی و زهرا در روز عید پدر به بازار می‌روند و برای پدرشان یک پیراهن انتخاب می‌کنند و می‌خرند.",
                        "reading_az": "Əli va Zəhra dər ruze eyde pedər be bazar mirəvənd va bəraye pedərşan yek pirahən entexab mikonənd va mixərənd.",
                        "az": "Əli və Zəhra ata günündə bazara gedirlər və ataları üçün bir köynək seçib alırlar.",
                    },
                    {
                        "fa": "همسرم لباس‌های کثیف را با لباس‌شویی می‌شوید و لباس‌های چروک را اتو می‌زند.",
                        "reading_az": "Həmsərəm lebashaye kəsif ra ba ləbasşuyi mişuyəd va lebashaye çoruk ra otu mizənəd.",
                        "az": "Həyat yoldaşım çirkli paltarları paltaryuyanla yuyur və qırışmış paltarları ütüləyir.",
                    },
                    {
                        "fa": "مریم روزهای جمعه در شستن لباس‌ها و تمیزکردن خانه به مادرش کمک می‌کند.",
                        "reading_az": "Məryəm ruzhaye come dər şostəne lebasha va təmiz-kərdəne xane be madərəş komək mikonəd.",
                        "az": "Məryəm cümə günləri paltarları yumaqda və evi təmizləməkdə anasına kömək edir.",
                    },
                    {
                        "fa": "آیا شما در کلاس، کاپشنتان را درمی‌آورید؟ بله، من در کلاسم کاپشنم را درمی‌آورم.",
                        "reading_az": "Aya şoma dər kelas, kapşenetan ra dərmiavərid? Bəle, mən dər kelasəm kapşenəm ra dərmiavəram.",
                        "az": "Siz sinifdə gödəkcənizi çıxarırsınızmı? Bəli, mən sinifdə gödəkcəmi çıxarıram.",
                    },
                    {
                        "fa": "شما کدام روسری را انتخاب می‌کنید؟ من روسری سرمه‌ای را انتخاب می‌کنم.",
                        "reading_az": "Şoma kodam rusəri ra entexab mikonid? Mən rusəriye sormei ra entexab mikonəm.",
                        "az": "Siz hansı baş örtüyünü seçirsiniz? Mən tünd göy baş örtüyünü seçirəm.",
                    },
                    {
                        "fa": "شما در زمستان چه لباس‌هایی می‌پوشید؟ ما در زمستان لباس‌های ضخیم، مانند ژاکت، کاپشن و پالتو می‌پوشیم.",
                        "reading_az": "Şoma dər zemestan çe lebashayi mipuşid? Ma dər zemestan lebashaye zəxim, manənde jaket, kapşen va palto mipuşim.",
                        "az": "Siz qışda hansı paltarları geyinirsiniz? Biz qışda jaket, gödəkcə və palto kimi qalın paltarlar geyinirik.",
                    },
                ],
            },
        ],
        "answer_items": [],
    },
    "reading_text": {
        "title_fa": "بازار",
        "title_az": "Bazar",
        "paragraphs_fa": [
            "در بسیاری از شهرهای ایران، بازار قدیمی و زیبا وجود دارد. در بازار، مغازه‌های زیادی برای فروشِ پوشاک، کفش، فرش، طلا، ظرف، پارچه، پرده و... هست. هر روز مردم زیادی برای خرید به بازار می‌روند. در بازارهای ایران، مسجد هم هست. فروشنده‌ها و خریداران، هنگام اذان برای خواندن نماز به آن‌جا می‌روند.",
            "بازارها نزدیک عید، خیلی شلوغ است. بچّه‌ها در آن روزها با پدر و مادرشان به بازار می‌روند؛ لباس و کفش‌های زیبا انتخاب می‌کنند و می‌خرند. پدر و مادرها هم یا لباس می‌خرند، یا پارچه‌های زیبا انتخاب می‌کنند و خیّاط برای آن‌ها شلوار، پیراهن، چادر و... می‌دوزد.",
            "بچّه‌ها لباس‌های نو را در کمد به چوب‌لباسی آویزان می‌کنند و در روز عید می‌پوشند و به خانه‌ی پدربزرگ‌ها، مادربزرگ‌ها، بستگان و دوستانشان می‌روند.",
        ],
        "footnotes": [
            {"fa": "فروش: فروختن / خرید: خریدن", "az": "satış / alış"},
            {"fa": "قدیمی", "az": "köhnə, qədim"},
            {"fa": "شلوغ / خلوت", "az": "qələbəlik / sakit"},
            {"fa": "هنگام", "az": "…zamanı"},
            {"fa": "چوب‌لباسی", "az": "paltarasan"},
        ],
        "full_translation_az": (
            "İranın bir çox şəhərində köhnə və gözəl bazar var. Bazarda geyim, ayaqqabı, xalça, qızıl, qab-qacaq, "
            "parça, pərdə və s. satışı üçün çoxlu mağaza var. Hər gün çoxlu insan alış-veriş üçün bazara gedir. "
            "İran bazarlarında məscid də var. Satıcılar və alıcılar azan zamanı namaz qılmaq üçün oraya gedirlər.\n\n"
            "Bayrama yaxın bazarlar çox qələbəlik olur. Uşaqlar o günlərdə ata-anaları ilə bazara gedirlər; gözəl "
            "paltar və ayaqqabılar seçib alırlar. Ata-analar da ya paltar alır, ya da gözəl parçalar seçirlər və "
            "dərzi onlar üçün şalvar, köynək, çadra və s. tikir.\n\n"
            "Uşaqlar təzə paltarları şkafda paltarasandan asırlar, bayram günü geyinib babalarının, nənələrinin, "
            "qohumlarının və dostlarının evinə gedirlər."
        ),
        "sentences": [
            {
                "fa": "در بسیاری از شهرهای ایران، بازار قدیمی و زیبا وجود دارد.",
                "reading_az": "Dər besyari əz şəhrhaye Iran, bazare qədimi va ziba vocud darəd.",
                "az": "İranın bir çox şəhərində köhnə və gözəl bazar var.",
                "new_paragraph": True,
            },
            {
                "fa": "در بازار، مغازه‌های زیادی برای فروشِ پوشاک، کفش، فرش، طلا، ظرف، پارچه، پرده و... هست.",
                "reading_az": "Dər bazar, məğazehaye ziyadi bəraye foruşe puşak, kəfş, fərş, təla, zərf, parçe, pərde va ... həst.",
                "az": "Bazarda geyim, ayaqqabı, xalça, qızıl, qab-qacaq, parça, pərdə və s. satışı üçün çoxlu mağaza var.",
            },
            {"fa": "هر روز مردم زیادی برای خرید به بازار می‌روند.", "reading_az": "Hər ruz mərdome ziyadi bəraye xərid be bazar mirəvənd.", "az": "Hər gün çoxlu insan alış-veriş üçün bazara gedir."},
            {"fa": "در بازارهای ایران، مسجد هم هست.", "reading_az": "Dər bazarhaye Iran, məsced həm həst.", "az": "İran bazarlarında məscid də var."},
            {
                "fa": "فروشنده‌ها و خریداران، هنگام اذان برای خواندن نماز به آن‌جا می‌روند.",
                "reading_az": "Foruşendeha va xəridaran, hengame əzan bəraye xandənenəmaz be anja mirəvənd.",
                "az": "Satıcılar və alıcılar azan zamanı namaz qılmaq üçün oraya gedirlər.",
            },
            {
                "fa": "بازارها نزدیک عید، خیلی شلوغ است.",
                "reading_az": "Bazarha nəzdike eyd, xeyli şoluğ əst.",
                "az": "Bayrama yaxın bazarlar çox qələbəlik olur.",
                "new_paragraph": True,
            },
            {
                "fa": "بچّه‌ها در آن روزها با پدر و مادرشان به بازار می‌روند؛ لباس و کفش‌های زیبا انتخاب می‌کنند و می‌خرند.",
                "reading_az": "Bəççeha dər an ruzha ba pedər va madərşan be bazar mirəvənd; lebas va kəfşhaye ziba entexab mikonənd va mixərənd.",
                "az": "Uşaqlar o günlərdə ata-anaları ilə bazara gedirlər; gözəl paltar və ayaqqabılar seçib alırlar.",
            },
            {
                "fa": "پدر و مادرها هم یا لباس می‌خرند، یا پارچه‌های زیبا انتخاب می‌کنند و خیّاط برای آن‌ها شلوار، پیراهن، چادر و... می‌دوزد.",
                "reading_az": "Pedər va madərha həm ya lebas mixərənd, ya parçehaye ziba entexab mikonənd va xəyyat bəraye anha şəlvar, pirahən, çador va ... miduzəd.",
                "az": "Ata-analar da ya paltar alır, ya da gözəl parçalar seçirlər və dərzi onlar üçün şalvar, köynək, çadra və s. tikir.",
            },
            {
                "fa": "بچّه‌ها لباس‌های نو را در کمد به چوب‌لباسی آویزان می‌کنند و در روز عید می‌پوشند و به خانه‌ی پدربزرگ‌ها، مادربزرگ‌ها، بستگان و دوستانشان می‌روند.",
                "reading_az": "Bəççeha lebashaye nou ra dər komod be çublebasi avizan mikonənd va dər ruze eyd mipuşənd va be xane-ye pedərbozorgha, madərbozorgha, bəstegan va dustanəşan mirəvənd.",
                "az": "Uşaqlar təzə paltarları şkafda paltarasandan asırlar, bayram günü geyinib babalarının, nənələrinin, qohumlarının və dostlarının evinə gedirlər.",
                "new_paragraph": True,
            },
        ],
        "comprehension_questions": [
            {
                "question_fa": "در بازار چه مغازه‌هایی وجود دارد؟",
                "reading_az": "Dər bazar çe məğazehayi vocud darəd?",
                "az": "Bazarda hansı mağazalar var?",
                "sample_answer_fa": "در بازار مغازه‌های پوشاک، کفش، فرش، طلا و ظرف وجود دارد.",
                "sample_answer_reading_az": "Dər bazar məğazehaye puşak, kəfş, fərş, təla va zərf vocud darəd.",
                "sample_answer_az": "Bazarda geyim, ayaqqabı, xalça, qızıl və qab-qacaq mağazaları var.",
            },
            {
                "question_fa": "بچّه‌ها هنگام عید چه‌کار می‌کنند؟",
                "reading_az": "Bəççeha hengame eyd çekar mikonənd?",
                "az": "Uşaqlar bayram vaxtı nə edir?",
                "sample_answer_fa": "آن‌ها با پدر و مادرشان به بازار می‌روند و لباس و کفش انتخاب می‌کنند.",
                "sample_answer_reading_az": "Anha ba pedər va madərşan be bazar mirəvənd va lebas va kəfş entexab mikonənd.",
                "sample_answer_az": "Onlar ata-anaları ilə bazara gedir və paltar-ayaqqabı seçirlər.",
            },
            {
                "question_fa": "آیا در بازارهای ایران، مسجد وجود ندارد؟",
                "reading_az": "Aya dər bazarhaye Iran, məsced vocud nədarəd?",
                "az": "İran bazarlarında məscid yoxdurmu?",
                "sample_answer_fa": "چرا، در بازارهای ایران مسجد هم هست.",
                "sample_answer_reading_az": "Çera, dər bazarhaye Iran məsced həm həst.",
                "sample_answer_az": "Xeyr (əksinə), İran bazarlarında məscid də var.",
            },
            {
                "question_fa": "چه وقت بازارهای ایران بسیار شلوغ هستند؟",
                "reading_az": "Çe vaqt bazarhaye Iran besyar şoluğ həstənd?",
                "az": "İran bazarları nə vaxt çox izdihamlı olur?",
                "sample_answer_fa": "بازارهای ایران نزدیک عید، بسیار شلوغ هستند.",
                "sample_answer_reading_az": "Bazarhaye Iran nəzdike eyd, besyar şoluğ həstənd.",
                "sample_answer_az": "İran bazarları bayrama yaxın çox izdihamlı olur.",
            },
            {
                "question_fa": "بچّه‌ها لباس‌های نو را چه‌کار می‌کنند؟",
                "reading_az": "Bəççeha lebashaye nou ra çekar mikonənd?",
                "az": "Uşaqlar təzə paltarları nə edirlər?",
                "sample_answer_fa": "بچّه‌ها لباس‌های نو را در کمد به چوب‌لباسی آویزان می‌کنند.",
                "sample_answer_reading_az": "Bəççeha lebashaye nou ra dər komod be çublebasi avizan mikonənd.",
                "sample_answer_az": "Uşaqlar təzə paltarları şkafda paltarasandan asırlar.",
            },
        ],
    },
}
