# Dərs 5 — شغل ۲ (Peşə 2)
# Mənbə: کتاب دوم, səh. 63-74

LESSON = {
    "number": 5,
    "title_fa": "شغل ۲",
    "title_az": "Peşə 2",
    "available": True,
    "vocabulary": [
        {"fa": "باغبان", "reading": "bağban", "az": "Bağban"},
        {"fa": "کشاورز", "reading": "keşavərz", "az": "Əkinçi"},
        {"fa": "نانوا", "reading": "nanva", "az": "Çörəkçi"},
        {"fa": "آشپز", "reading": "aşpəz", "az": "Aşpaz"},
        {"fa": "آرایش‌گر", "reading": "arayeşgər", "az": "Bərbər"},
        {"fa": "تعمیرکار", "reading": "təmirkar", "az": "Təmirçi"},
        {"fa": "میوه‌فروش", "reading": "miveforuş", "az": "Meyvə satan"},
        {"fa": "کتاب‌فروش", "reading": "ketabforuş", "az": "Kitab satan"},
        {"fa": "طلافروش", "reading": "təlaforuş", "az": "Qızıl satan (zərgər)"},
        {"fa": "نویسنده", "reading": "nevisənde", "az": "Yazıçı"},
        {"fa": "خبرنگار", "reading": "xəbərneqar", "az": "Jurnalist (müxbir)"},
        {"fa": "امدادگر", "reading": "emdadgər", "az": "Xilasedici"},
        {"fa": "خلبان", "reading": "xələban", "az": "Pilot"},
        {"fa": "مهمان‌دار", "reading": "mehmandar", "az": "Stüardessa (bələdçi)"},
        {"fa": "بازرگان (تاجر)", "reading": "bazərgan (tacer)", "az": "Tacir"},
        {"fa": "کارمند", "reading": "karmənd", "az": "İşçi (məmur)"},
        {"fa": "خریدار", "reading": "xəridar", "az": "Alıcı (müştəri)"},
        {"fa": "فروشنده", "reading": "foruşənde", "az": "Satıcı"},
        {"fa": "می‌رود", "reading": "mirəvəd", "az": "gedir"},
        {"fa": "می‌آید", "reading": "miayəd", "az": "gəlir"},
        {"fa": "می‌خرد", "reading": "mixərəd", "az": "alır"},
        {"fa": "می‌فروشد", "reading": "miforuşəd", "az": "satır"},
        {"fa": "روستا (ده)", "reading": "rusta (deh)", "az": "Kənd"},
        {"fa": "باغ‌دار", "reading": "bağdar", "az": "Bağ sahibi"},
        {"fa": "اداره‌ی پست", "reading": "edareye post", "az": "Poçt idarəsi"},
        {"fa": "باهم", "reading": "bahəm", "az": "birlikdə"},
        {"fa": "تنها", "reading": "tənha", "az": "tək"},
        {"fa": "بیرون", "reading": "birun", "az": "bayır, çöl"},
    ],
    "grammar_notes": [
        {
            "title_az": "«از» (…-dan) və «به» (…-a) ön qoşmaları",
            "title_fa": "حرف اضافه‌ی «از» ؛ «به»",
            "conjugations": [],
            "examples": [
                {"fa": "من ساعت هفتِ صبح از خانه به مدرسه می‌روم.", "reading_az": "Mən saəte həfte sobh əz xane be mædrese mirəvəm.", "az": "Mən səhər saat yeddidə evdən məktəbə gedirəm."},
                {"fa": "من ساعت دوازده از مدرسه به خانه می‌آیم.", "reading_az": "Mən saəte davazdə əz mædrese be xane miayəm.", "az": "Mən saat on ikidə məktəbdən evə gəlirəm."},
                {"fa": "من با تاکسی از قم به فرودگاه تهران می‌روم.", "reading_az": "Mən ba taksi əz Qom be forudgahe Tehran mirəvəm.", "az": "Mən taksi ilə Qumdan Tehran hava limanına gedirəm."},
                {"fa": "خانواده‌ام روز یک‌شنبه از پاکستان به ایران می‌آیند.", "reading_az": "Xanevadeəm ruze yekşənbe əz Pakestan be Iran miayənd.", "az": "Ailəm bazar günü Pakistandan İrana gəlir."},
                {"fa": "شما از این‌جا به کجا می‌روید؟ من از این‌جا به خانه‌ی دوستم می‌روم.", "reading_az": "Şoma əz inja be koca mirəvid? Mən əz inja be xane-ye dustəm mirəvəm.", "az": "Siz buradan hara gedirsiniz? Mən buradan dostumun evinə gedirəm."},
            ],
            "drills": [
                {
                    "title_fa": "مانند مثال بگویید",
                    "instruction_az": '"از … به …" ilə nümunə kimi deyin',
                    "example_fa": "فاطمه و مریم می‌روند. (دانش‌گاه ـ خانه) ← فاطمه و مریم *از* دانش‌گاه *به* خانه می‌روند.",
                    "example_reading_az": "Fateme va Məryəm mirəvənd. (Daneşgah - xane) ← Fateme va Məryəm əz daneşgah be xane mirəvənd.",
                    "example_az": "Fatimə və Məryəm gedir. (Universitet - ev) ← Fatimə və Məryəm universitetdən evə gedirlər.",
                    "items": [
                        {
                            "prompt_fa": "این هواپیما می‌رود. (ایران ـ چین)",
                            "answer_fa": "این هواپیما از ایران به چین می‌رود.",
                            "reading_az": "İn həvapeyma əz Iran be Çin mirəvəd.",
                            "az": "Bu təyyarə İrandan Çinə gedir.",
                        },
                        {
                            "prompt_fa": "استادمان با قطار می‌رود. (اصفهان ـ شیراز)",
                            "answer_fa": "استادمان با قطار از اصفهان به شیراز می‌رود.",
                            "reading_az": "Ostademan ba qatar əz Esfəhan be Şiraz mirəvəd.",
                            "az": "Müəllimimiz qatarla İsfahandan Şiraza gedir.",
                        },
                        {
                            "prompt_fa": "زینب و نرگس هر روز می‌آیند. (مدرسه ـ مسجد)",
                            "answer_fa": "زینب و نرگس هر روز از مدرسه به مسجد می‌آیند.",
                            "reading_az": "Zeynəb va Nərges hər ruz əz mædrese be məsced miayənd.",
                            "az": "Zeynəb və Nərgiz hər gün məktəbdən məscidə gəlirlər.",
                        },
                        {
                            "prompt_fa": "من برای دیدن دوستم با قطار می‌روم. (پاکستان ـ هند)",
                            "answer_fa": "من برای دیدن دوستم با قطار از پاکستان به هند می‌روم.",
                            "reading_az": "Mən bəraye didəne dustəm ba qatar əz Pakestan be Hend mirəvəm.",
                            "az": "Mən dostumu görmək üçün qatarla Pakistandan Hindistana gedirəm.",
                        },
                        {
                            "prompt_fa": "من و خواهرم برای درس‌خواندن می‌آییم. (کشورمان ـ ایران)",
                            "answer_fa": "من و خواهرم برای درس‌خواندن از کشورمان به ایران می‌آییم.",
                            "reading_az": "Mən va xahərəm bəraye dərs-xandən əz kəşvəreman be Iran miayim.",
                            "az": "Mən və bacım oxumaq üçün ölkəmizdən İrana gəlirik.",
                        },
                    ],
                },
            ],
        },
        {
            "title_az": "«هستم؛ هستی؛ ...» felinin əvəzedicisi (1): استادم = استاد هستم",
            "title_fa": "جانشین فعل «هستم؛ هستی؛ ...» (۱)",
            "conjugations": [
                {"pronoun_fa": "من", "form_fa": "استاد + ـَم → استادم"},
                {"pronoun_fa": "تو", "form_fa": "استاد + ی → استادی"},
                {"pronoun_fa": "او", "form_fa": "استاد + است → استاد است"},
                {"pronoun_fa": "ما", "form_fa": "استاد + یم → استادیم"},
                {"pronoun_fa": "شما", "form_fa": "استاد + ید → استادید"},
                {"pronoun_fa": "آن‌ها", "form_fa": "استاد + ـَند → استادند"},
            ],
            "examples": [
                {"fa": "من خلبانم و برادرم مهندس رایانه است.", "reading_az": "Mən xələbanəm va bəradərəm mohəndese rayane əst.", "az": "Mən pilotam və qardaşım kompüter mühəndisidir."},
                {"fa": "ما تعمیرکار ساعتیم و آن‌ها تعمیرکار یخچالند.", "reading_az": "Ma təmirkare saətim va anha təmirkare yəxçaland.", "az": "Biz saat təmirçisiyik, onlar isə soyuducu təmirçisidirlər."},
                {"fa": "پدر و برادرم بازرگانند. آن‌ها چای و برنج می‌خرند و می‌فروشند.", "reading_az": "Pedər va bəradərəm bazərganand. Anha çay va berenc mixərənd va miforuşənd.", "az": "Atam və qardaşım tacirdirlər. Onlar çay və düyü alıb-satırlar."},
                {"fa": "من فروشنده نیستم، خریدارم. من برای فرزندم میز و چراغ مطالعه می‌خرم.", "reading_az": "Mən foruşənde nistəm, xəridaram. Mən bəraye fərzəndəm miz va çerağe motaleə mixərəm.", "az": "Mən satıcı deyiləm, alıcıyam. Övladım üçün masa və masa lampası alıram."},
                {"fa": "شما چوپانی یا شکارچی؟ من چوپانم.", "reading_az": "Şoma çupani ya şekarçi? Mən çupanəm.", "az": "Sən çobansan, yoxsa ovçu? Mən çobanam."},
                {"fa": "شما پلیسید یا امدادگرید؟ ما پلیس نیستیم؛ ما امدادگریم.", "reading_az": "Şoma polisid ya emdadgərid? Ma polis nistim; ma emdadgərim.", "az": "Siz polissiniz, yoxsa xilasedici? Biz polis deyilik; biz xilasediciyik."},
            ],
        },
        {
            "title_az": "«هستم؛ ...» felinin əvəzedicisi (2): «ه» ilə bitən sözlər (فروشنده‌ام)",
            "title_fa": "جانشین فعل «هستم؛ هستی؛ ...» (۲)",
            "conjugations": [
                {"pronoun_fa": "من", "form_fa": "فروشنده + ام → فروشنده‌ام"},
                {"pronoun_fa": "تو", "form_fa": "فروشنده + ای → فروشنده‌ای"},
                {"pronoun_fa": "او", "form_fa": "فروشنده + است → فروشنده است"},
                {"pronoun_fa": "ما", "form_fa": "فروشنده + ایم → فروشنده‌ایم"},
                {"pronoun_fa": "شما", "form_fa": "فروشنده + اید → فروشنده‌اید"},
                {"pronoun_fa": "آن‌ها", "form_fa": "فروشنده + اند → فروشنده‌اند"},
            ],
            "examples": [
                {"fa": "ما کتاب‌فروشیم؛ آن‌ها نویسنده‌اند.", "reading_az": "Ma ketabforuşim; anha nevisəndeand.", "az": "Biz kitab satanıq; onlar yazıçıdırlar."},
                {"fa": "آن‌ها خریدار نیستند؛ آن‌ها فروشنده‌اند.", "reading_az": "Anha xəridar nistənd; anha foruşəndeand.", "az": "Onlar alıcı deyillər; onlar satıcıdırlar."},
                {"fa": "آن‌ها دانش‌آموزند؛ ما معلّمیم و ایشان مدیر مدرسه‌اند.", "reading_az": "Anha daneşamuzand; ma moəllemim va işan modire mædreseand.", "az": "Onlar şagirddirlər; biz müəllimik, o (hörmətlə) isə məktəb direktorudur."},
                {"fa": "آیا شما پلیسی؟ نه، من نگهبان مدرسه‌ام.", "reading_az": "Aya şoma polisi? Nə, mən negəhbane mædreseam.", "az": "Sən polissən? Xeyr, mən məktəbin gözətçisiyəm."},
                {"fa": "آیا شما طلبه‌اید؟ بله، ما طلبه‌ایم.", "reading_az": "Aya şoma təllabeid? Bəle, ma təllabeim.", "az": "Siz tələbəsiniz? Bəli, biz tələbəyik."},
                {"fa": "سعید و برادرش چه‌کاره‌اند؟ آن‌ها راننده‌اند.", "reading_az": "Səid va bəradərəş çekareand? Anha ranəndeand.", "az": "Səid və qardaşı nəçidirlər? Onlar sürücüdürlər."},
            ],
            "drills": [
                {
                    "title_fa": "مانند مثال تبدیل کنید",
                    "instruction_az": 'Nümunə kimi çevirin: "من آهنگر هستم = من آهنگرم؛ من راننده هستم = من راننده‌ام"',
                    "items": [
                        {"prompt_fa": "من معلّم هستم.", "answer_fa": "من معلّمم.", "reading_az": "Mən moəlleməm.", "az": "Mən müəlliməm."},
                        {"prompt_fa": "ما مهندس هستیم.", "answer_fa": "ما مهندسیم.", "reading_az": "Ma mohəndesim.", "az": "Biz mühəndisik."},
                        {"prompt_fa": "من و دوستم طلبه هستیم.", "answer_fa": "من و دوستم طلبه‌ایم.", "reading_az": "Mən va dustəm təllabeim.", "az": "Mən və dostum tələbəyik."},
                        {"prompt_fa": "آن‌ها نویسنده هستند.", "answer_fa": "آن‌ها نویسنده‌اند.", "reading_az": "Anha nevisəndeand.", "az": "Onlar yazıçıdır."},
                        {
                            "prompt_fa": "من پرستار هستم؛ پزشک نیستم.",
                            "answer_fa": "من پرستارم؛ پزشک نیستم.",
                            "reading_az": "Mən pərəstaram; pezeşk nistəm.",
                            "az": "Mən tibb bacısıyam; həkim deyiləm.",
                        },
                        {
                            "prompt_fa": "ما امدادگر هستیم؛ پلیس نیستیم.",
                            "answer_fa": "ما امدادگریم؛ پلیس نیستیم.",
                            "reading_az": "Ma emdadgərim; polis nistim.",
                            "az": "Biz xilasediciyik; polis deyilik.",
                        },
                        {"prompt_fa": "آیا شما فروشنده هستی؟", "answer_fa": "آیا شما فروشنده‌ای؟", "reading_az": "Aya şoma foruşəndei?", "az": "Sən satıcısanmı?"},
                        {"prompt_fa": "آیا شما تاجر فرش هستید؟", "answer_fa": "آیا شما تاجر فرشید؟", "reading_az": "Aya şoma tacere fərşid?", "az": "Siz xalça tacirisinizmi?"},
                    ],
                },
            ],
        },
    ],
    "exercises": [
        {
            "kind": "fill_blank",
            "instruction_az": "Boşluqları «از» və ya «به» ilə doldurun.",
            "word_bank": ["از", "به"],
            "items": [
                {
                    "fa_with_blank": "ما ___ لبنان به ایران می‌آییم.",
                    "correct_answer": "از",
                    "reading_az": "əz",
                    "az": "-dan",
                    "full_reading_az": "Ma əz Lobnan be Iran miayim.",
                    "full_translation_az": "Biz Livandan İrana gəlirik.",
                },
                {
                    "fa_with_blank": "آن‌ها ساعت یک از مسجد ___ خانه می‌آیند.",
                    "correct_answer": "به",
                    "reading_az": "be",
                    "az": "-a",
                    "full_reading_az": "Anha saəte yek əz məsced be xane miayənd.",
                    "full_translation_az": "Onlar saat birdə məsciddən evə gəlirlər.",
                },
                {
                    "fa_with_blank": "من برای خریدن لباس و کفش ___ فروش‌گاه می‌روم.",
                    "correct_answer": "به",
                    "reading_az": "be",
                    "az": "-a",
                    "full_reading_az": "Mən bəraye xəridəne lebas va kəfş be foruşgah mirəvəm.",
                    "full_translation_az": "Mən paltar və ayaqqabı almaq üçün mağazaya gedirəm.",
                },
                {
                    "fa_with_blank": "شما ___ کجا می‌آیید و به کجا می‌روید؟",
                    "correct_answer": "از",
                    "reading_az": "əz",
                    "az": "-dan",
                    "full_reading_az": "Şoma əz koca miayid va be koca mirəvid?",
                    "full_translation_az": "Siz haradan gəlir və haraya gedirsiniz?",
                },
                {
                    "fa_with_blank": "من از این‌جا ___ استخر می‌آیم و به رستوران می‌روم.",
                    "correct_answer": "به",
                    "reading_az": "be",
                    "az": "-a",
                    "full_reading_az": "Mən əz inja be estəxr miayəm va be restoran mirəvəm.",
                    "full_translation_az": "Mən buradan hovuza gəlirəm və restorana gedirəm.",
                },
            ],
        },
        {
            "kind": "fill_blank",
            "instruction_az": "Boşluğu söz bankından uyğun peşə ilə doldurun.",
            "word_bank": ["آشپز", "نویسنده", "خبرنگار", "دانش‌آموز", "تاجر", "پزشک"],
            "items": [
                {
                    "fa_with_blank": "این خانم ___ است. او کتاب‌های زیادی می‌نویسد.",
                    "correct_answer": "نویسنده",
                    "reading_az": "nevisənde",
                    "az": "yazıçı",
                    "full_reading_az": "İn xanom nevisənde əst. U ketabhaye ziyadi minevisəd.",
                    "full_translation_az": "Bu xanım yazıçıdır. O, çoxlu kitab yazır.",
                },
                {
                    "fa_with_blank": "محمد و مهدی ___ هستند. آن‌ها بیماران را معاینه می‌کنند.",
                    "correct_answer": "پزشک",
                    "reading_az": "pezeşk",
                    "az": "həkim",
                    "full_reading_az": "Mohəmməd va Mehdi pezeşk həstənd. Anha bimaran ra moayene mikonənd.",
                    "full_translation_az": "Məhəmməd və Mehdi həkimdir. Onlar xəstələri müayinə edirlər.",
                },
                {
                    "fa_with_blank": "برادرم ___ است. او هر روز چهار ساعت به کلاس می‌رود.",
                    "correct_answer": "دانش‌آموز",
                    "reading_az": "daneşamuz",
                    "az": "şagird",
                    "full_reading_az": "Bəradərəm daneşamuz əst. U hər ruz çahar saət be kelas mirəvəd.",
                    "full_translation_az": "Qardaşım şagirddir. O, hər gün dörd saat sinfə gedir.",
                },
                {
                    "fa_with_blank": "ما در آن دانش‌گاه ___ هستیم. ما هر روز برای دانش‌جوها غذا می‌پزیم.",
                    "correct_answer": "آشپز",
                    "reading_az": "aşpəz",
                    "az": "aşpaz",
                    "full_reading_az": "Ma dər an daneşgah aşpəz hastim. Ma hər ruz bəraye daneşcuha qəza mipəzim.",
                    "full_translation_az": "Biz o universitetdə aşpazıq. Biz hər gün tələbələr üçün yemək bişiririk.",
                },
                {
                    "fa_with_blank": "پدر زینب ___ است. او از ایران پسته می‌خرد و در آفریقا و اروپا می‌فروشد.",
                    "correct_answer": "تاجر",
                    "reading_az": "tacer",
                    "az": "tacir",
                    "full_reading_az": "Pedəre Zeynəb tacer əst. U əz Iran peste mixərəd va dər Afriqa va Orupa miforuşəd.",
                    "full_translation_az": "Zeynəbin atası tacirdir. O, İrandan püstə alır və Afrika ilə Avropada satır.",
                },
            ],
        },
        {
            "kind": "multiple_choice",
            "instruction_az": "«فرهاد» mətninə görə düzgün cavabı seçin.",
            "items": [
                {"question_fa": "فرهاد چه‌کاره است؟", "options": ["کارمند دانش‌گاه مشهد", "کارمند اداره‌ی پست", "مدیر مدرسه"], "correct_index": 0},
                {"question_fa": "مریم کارمند کدام اداره است؟", "options": ["اداره‌ی بانک", "اداره‌ی پست", "اداره‌ی مدرسه"], "correct_index": 1},
                {"question_fa": "مریم ناهار را کجا می‌خورد؟", "options": ["در دانش‌گاه", "در اداره", "در خانه، تنها"], "correct_index": 2},
                {"question_fa": "پدر مریم چه‌کاره است؟", "options": ["مدیر مدرسه", "باغ‌دار", "معلّم"], "correct_index": 0},
                {"question_fa": "پدر فرهاد چه‌کاره است و کجا زندگی می‌کند؟", "options": ["کشاورز است؛ در شهر", "باغ‌دار است؛ در روستا", "میوه‌فروش است؛ در نیشابور"], "correct_index": 1},
                {"question_fa": "در باغ پدر فرهاد چه درخت‌هایی وجود دارد؟", "options": ["سیب، انار و هلو", "پرتقال و نارگیل", "گیلاس و زردآلو"], "correct_index": 0},
                {"question_fa": "فرهاد و مریم روزهای جمعه به کجا می‌روند؟", "options": ["به مشهد", "گاهی به روستا و گاهی به نیشابور", "به فرودگاه"], "correct_index": 1},
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "İndi əksinə çevirin: «ما خبرنگاریم = ما خبرنگار هستیم»",
            "items": [
                {"prompt_fa": "آن‌ها راننده‌اند.", "answer_fa": "آن‌ها راننده هستند.", "reading_az": "Anha ranənde həstənd.", "az": "Onlar sürücüdür."},
                {"prompt_fa": "من و برادرم کشاورزیم.", "answer_fa": "من و برادرم کشاورز هستیم.", "reading_az": "Mən va bəradərəm keşavərz hastim.", "az": "Mən və qardaşım əkinçiyik."},
                {"prompt_fa": "من تعمیرکار یخچالم.", "answer_fa": "من تعمیرکار یخچال هستم.", "reading_az": "Mən təmirkare yəxçal hastəm.", "az": "Mən soyuducu təmirçisiyəm."},
                {"prompt_fa": "شما کارمند بانکید.", "answer_fa": "شما کارمند بانک هستید.", "reading_az": "Şoma karmənde bank hastid.", "az": "Siz bank işçisisiniz."},
                {
                    "prompt_fa": "شما کارمند کدام اداره‌اید؟",
                    "answer_fa": "شما کارمند کدام اداره هستید؟",
                    "reading_az": "Şoma karmənde kodam edare hastid?",
                    "az": "Siz hansı idarənin işçisisiniz?",
                },
                {
                    "prompt_fa": "آن‌ها باغبانند یا میوه‌فروشند؟",
                    "answer_fa": "آن‌ها باغبان هستند یا میوه‌فروش هستند؟",
                    "reading_az": "Anha bağban həstənd ya miveforuş həstənd?",
                    "az": "Onlar bağbandır, yoxsa meyvə satan?",
                },
                {
                    "prompt_fa": "شما فروشنده‌ای یا خریدار؟",
                    "answer_fa": "شما فروشنده هستی یا خریدار هستی؟",
                    "reading_az": "Şoma foruşənde hasti ya xəridar hasti?",
                    "az": "Sən satıcısan, yoxsa alıcı?",
                },
            ],
        },
        {
            "kind": "practice_reveal",
            "instruction_az": "«تنها / باهم» ilə nümunə kimi deyin: «من / مدرسه رفتن / دوستم → من تنها به مدرسه نمی‌روم؛ من و دوستم باهم به مدرسه می‌رویم.»",
            "items": [
                {
                    "prompt_fa": "سعید / غذاخوردن / پدربزرگش",
                    "answer_fa": "سعید تنها غذا نمی‌خورد؛ سعید و پدربزرگش باهم غذا می‌خورند.",
                    "reading_az": "Səid tənha qəza nemixorəd; Səid va pedərbozorgəş bahəm qəza mixorənd.",
                    "az": "Səid tək yemək yemir; Səid və babası birlikdə yemək yeyirlər.",
                },
                {
                    "prompt_fa": "فرزندم / خانه آمدن / برادرش",
                    "answer_fa": "فرزندم تنها به خانه نمی‌آید؛ فرزندم و برادرش باهم به خانه می‌آیند.",
                    "reading_az": "Fərzendəm tənha be xane nemiayəd; fərzendəm va bəradərəş bahəm be xane miayənd.",
                    "az": "Övladım evə tək gəlmir; övladım və qardaşı birlikdə evə gəlirlər.",
                },
                {
                    "prompt_fa": "دخترم / فروش‌گاه رفتن / مادرش",
                    "answer_fa": "دخترم تنها به فروش‌گاه نمی‌رود؛ دخترم و مادرش باهم به فروش‌گاه می‌روند.",
                    "reading_az": "Doxtərəm tənha be foruşgah nemirəvəd; doxtərəm va madərəş bahəm be foruşgah mirəvənd.",
                    "az": "Qızım mağazaya tək getmir; qızım və anası birlikdə mağazaya gedirlər.",
                },
                {
                    "prompt_fa": "مادربزرگم / زندگی‌کردن / مادرم",
                    "answer_fa": "مادربزرگم تنها زندگی نمی‌کند؛ مادربزرگم و مادرم باهم زندگی می‌کنند.",
                    "reading_az": "Madərbozorgəm tənha zendegi nemikonəd; madərbozorgəm va madərəm bahəm zendegi mikonənd.",
                    "az": "Nənəm tək yaşamır; nənəm və anam birlikdə yaşayırlar.",
                },
            ],
        },
    ],
    "sentence_practice": {
        "listen_items": [
            {
                "fa": "دوستم مهدی، خبرنگار است و در لبنان زندگی می‌کند.",
                "reading_az": "Dustəm Mehdi, xəbərneqar əst va dər Lobnan zendegi mikonəd.",
                "az": "Dostum Mehdi jurnalistdir və Livanda yaşayır.",
            },
            {
                "fa": "من خلبان هستم و این خانم‌ها مهمان‌دار هواپیما هستند.",
                "reading_az": "Mən xələban hastəm va in xanomha mehmandare həvapeyma həstənd.",
                "az": "Mən pilotam və bu xanımlar təyyarə stüardessalarıdır.",
            },
            {
                "fa": "مریم و فاطمه نویسنده هستند. آن‌ها برای کودکان، کتاب می‌نویسند.",
                "reading_az": "Məryəm va Fateme nevisənde həstənd. Anha bəraye kudəkan, ketab minevisənd.",
                "az": "Məryəm və Fatimə yazıçıdır. Onlar uşaqlar üçün kitab yazırlar.",
            },
            {
                "fa": "پدربزرگم باغبان است. او در باغش درخت‌های گیلاس، سیب و انار دارد.",
                "reading_az": "Pedərbozorgəm bağban əst. U dər bağəş dərəxthaye gilas, sib va anar darəd.",
                "az": "Babam bağbandır. Onun bağında albalı, alma və nar ağacları var.",
            },
            {
                "fa": "پدرم بازرگانِ فرش است. او از ایران فرش می‌خرد و در اروپا می‌فروشد.",
                "reading_az": "Pedərəm bazərgane fərş əst. U əz Iran fərş mixərəd va dər Orupa miforuşəd.",
                "az": "Atam xalça taciridir. O, İrandan xalça alır və Avropada satır.",
            },
            {
                "fa": "امین و رضا آشپز هستند. آن‌ها هر روز در آشپزخانه‌ی دانش‌گاه غذا می‌پزند.",
                "reading_az": "Əmin va Reza aşpəz həstənd. Anha hər ruz dər aşpəzxane-ye daneşgah qəza mipəzənd.",
                "az": "Əmin və Rza aşpazdır. Onlar hər gün universitetin mətbəxində yemək bişirirlər.",
            },
            {
                "fa": "ما به فروش‌گاه می‌رویم و برای فرزندمان دفتر نقّاشی و مدادرنگی می‌خریم.",
                "reading_az": "Ma be foruşgah mirəvim va bəraye fərzəndeman dəftəre nəqqaşi va medadrəngi mixərim.",
                "az": "Biz mağazaya gedirik və övladımız üçün rəsm dəftəri və rəngli karandaş alırıq.",
            },
            {
                "fa": "این آقا میوه‌فروش است. او در مغازه‌اش پرتقال، انار، سیب، نارگیل و... می‌فروشد.",
                "reading_az": "İn ağa miveforuş əst. U dər məğazeəş porteqal, anar, sib, nargil va ... miforuşəd.",
                "az": "Bu kişi meyvə satandır. O, mağazasında portağal, nar, alma, hindistancevizi və s. satır.",
            },
            {
                "fa": "برادرم هر روز، ساعتِ هفت صبح به دانش‌گاه می‌رود و ساعت چهار به خانه می‌آید.",
                "reading_az": "Bəradərəm hər ruz, saəte həft sobh be daneşgah mirəvəd va saəte çahar be xane miayəd.",
                "az": "Qardaşım hər gün, səhər saat yeddidə universitetə gedir və saat dörddə evə gəlir.",
            },
            {
                "fa": "ایشان کارمند فرودگاه امام است. او هر روز، هفت ساعت در فرودگاه امام کار می‌کند.",
                "reading_az": "İşan karmənde forudgahe Emam əst. U hər ruz, həft saət dər forudgahe Emam kar mikonəd.",
                "az": "O, İmam hava limanının işçisidir. O, hər gün yeddi saat İmam hava limanında işləyir.",
            },
        ],
        "answer_items": [
            {
                "fa": "آشپزها چه‌کار می‌کنند؟",
                "reading_az": "Aşpəzha çekar mikonənd?",
                "az": "Aşpazlar nə iş görür?",
                "sample_answer_fa": "آشپزها غذا می‌پزند.",
                "sample_answer_reading_az": "Aşpəzha qəza mipəzənd.",
                "sample_answer_az": "Aşpazlar yemək bişirir.",
            },
            {
                "fa": "خانواده‌ی شما چه‌کاره هستند؟",
                "reading_az": "Xanevade-ye şoma çekare həstənd?",
                "az": "Ailəniz nəçidir?",
            },
            {
                "fa": "آیا دوست شما تاجرِ پسته است؟",
                "reading_az": "Aya duste şoma tacere peste əst?",
                "az": "Dostunuz püstə taciridirmi?",
            },
            {
                "fa": "آشپز غذا می‌پزد یا گوشت می‌فروشد؟",
                "reading_az": "Aşpəz qəza mipəzəd ya qust miforuşəd?",
                "az": "Aşpaz yemək bişirir, yoxsa ət satır?",
                "sample_answer_fa": "آشپز غذا می‌پزد؛ او گوشت نمی‌فروشد.",
                "sample_answer_reading_az": "Aşpəz qəza mipəzəd; u qust nemiforuşəd.",
                "sample_answer_az": "Aşpaz yemək bişirir; o, ət satmır.",
            },
            {
                "fa": "آیا دوست شما تعمیرکار یخچال است؟",
                "reading_az": "Aya duste şoma təmirkare yəxçal əst?",
                "az": "Dostunuz soyuducu təmirçisidirmi?",
            },
            {
                "fa": "آیا شما روزهای جمعه به کلاس می‌آیید؟",
                "reading_az": "Aya şoma ruzhaye come be kelas miayid?",
                "az": "Siz cümə günləri sinfə gəlirsinizmi?",
                "sample_answer_fa": "نه، ما روزهای جمعه به کلاس نمی‌آییم.",
                "sample_answer_reading_az": "Nə, ma ruzhaye come be kelas nemiayim.",
                "sample_answer_az": "Xeyr, biz cümə günləri sinfə gəlmirik.",
            },
        ],
    },
    "reading_text": {
        "title_fa": "فرهاد",
        "title_az": "Fərhad",
        "paragraphs_fa": [
            "فرهاد، کارمندِ دانش‌گاه مشهد است و همسرش مریم، کارمند اداره‌ی پست است. فرهاد و مریم هر روز صبح باهم از خانه بیرون می‌روند. مریم ساعت دو به خانه می‌آید و تنها ناهار می‌خورد؛ امّا همسرش فرهاد تا ساعت چهار در دانش‌گاه است و آن‌جا غذا می‌خورد.",
            "پدر مریم در شهر نیشابور زندگی می‌کند. او مدیر مدرسه است. در مدرسه‌ی او هجده معلّم درس می‌دهند و دانش‌آموزان زیادی درس می‌خوانند.",
            "پدر فرهاد، باغ‌دار است و با خانواده‌اش در روستا زندگی می‌کند. او یک باغ بزرگ و زیبا دارد. در باغ او، درخت‌های سیب، انار، هلو و... وجود دارد.",
            "فرهاد و همسرش روزهای جمعه گاهی به روستا می‌روند و گاهی برای دیدن خانواده‌ی مریم به نیشابور می‌روند.",
        ],
        "footnotes": [
            {"fa": "اداره‌ی پست", "az": "poçt idarəsi"},
            {"fa": "روستا: ده", "az": "kənd"},
            {"fa": "باغ‌دار", "az": "bağ sahibi"},
            {"fa": "تنها / باهم", "az": "tək / birlikdə"},
        ],
        "full_translation_az": (
            "Fərhad Məşhəd Universitetinin işçisidir, həyat yoldaşı Məryəm isə poçt idarəsinin işçisidir. "
            "Fərhad və Məryəm hər gün səhər birlikdə evdən çıxırlar. Məryəm saat ikidə evə gəlir və naharı tək "
            "yeyir; amma həyat yoldaşı Fərhad saat dördə qədər universitetdədir və yeməyini orada yeyir.\n\n"
            "Məryəmin atası Nişapur şəhərində yaşayır. O, məktəb direktorudur. Onun məktəbində on səkkiz müəllim "
            "dərs deyir və çoxlu şagird oxuyur.\n\n"
            "Fərhadın atası bağ sahibidir və ailəsi ilə kənddə yaşayır. Onun böyük və gözəl bir bağı var. Onun "
            "bağında alma, nar, şaftalı və s. ağacları var.\n\n"
            "Fərhad və həyat yoldaşı cümə günləri bəzən kəndə gedir, bəzən də Məryəmin ailəsini görmək üçün "
            "Nişapura gedirlər."
        ),
        "sentences": [
            {
                "fa": "فرهاد، کارمندِ دانش‌گاه مشهد است و همسرش مریم، کارمند اداره‌ی پست است.",
                "reading_az": "Fərhad, karmənde daneşgahe Məşhəd əst va həmsərəş Məryəm, karmənde edareye post əst.",
                "az": "Fərhad Məşhəd Universitetinin işçisidir, həyat yoldaşı Məryəm isə poçt idarəsinin işçisidir.",
                "new_paragraph": True,
            },
            {
                "fa": "فرهاد و مریم هر روز صبح باهم از خانه بیرون می‌روند.",
                "reading_az": "Fərhad va Məryəm hər ruz sobh bahəm əz xane birun mirəvənd.",
                "az": "Fərhad və Məryəm hər gün səhər birlikdə evdən çıxırlar.",
            },
            {
                "fa": "مریم ساعت دو به خانه می‌آید و تنها ناهار می‌خورد؛ امّا همسرش فرهاد تا ساعت چهار در دانش‌گاه است و آن‌جا غذا می‌خورد.",
                "reading_az": "Məryəm saəte do be xane miayəd va tənha nahar mixorəd; əmma həmsərəş Fərhad ta saəte çahar dər daneşgah əst va anja qəza mixorəd.",
                "az": "Məryəm saat ikidə evə gəlir və naharı tək yeyir; amma həyat yoldaşı Fərhad saat dördə qədər universitetdədir və yeməyini orada yeyir.",
            },
            {
                "fa": "پدر مریم در شهر نیشابور زندگی می‌کند.",
                "reading_az": "Pedəre Məryəm dər şəhre Nişabur zendegi mikonəd.",
                "az": "Məryəmin atası Nişapur şəhərində yaşayır.",
                "new_paragraph": True,
            },
            {"fa": "او مدیر مدرسه است.", "reading_az": "U modire mædrese əst.", "az": "O, məktəb direktorudur."},
            {
                "fa": "در مدرسه‌ی او هجده معلّم درس می‌دهند و دانش‌آموزان زیادی درس می‌خوانند.",
                "reading_az": "Dər mædrese-ye u hejdəh moəllem dərs midəhənd va daneşamuzane ziyadi dərs mixanənd.",
                "az": "Onun məktəbində on səkkiz müəllim dərs deyir və çoxlu şagird oxuyur.",
            },
            {
                "fa": "پدر فرهاد، باغ‌دار است و با خانواده‌اش در روستا زندگی می‌کند.",
                "reading_az": "Pedəre Fərhad, bağdar əst va ba xanevadeəş dər rusta zendegi mikonəd.",
                "az": "Fərhadın atası bağ sahibidir və ailəsi ilə kənddə yaşayır.",
                "new_paragraph": True,
            },
            {"fa": "او یک باغ بزرگ و زیبا دارد.", "reading_az": "U yek bağe bozorg va ziba darəd.", "az": "Onun böyük və gözəl bir bağı var."},
            {
                "fa": "در باغ او، درخت‌های سیب، انار، هلو و... وجود دارد.",
                "reading_az": "Dər bağe u, dərəxthaye sib, anar, holu va ... vocud darəd.",
                "az": "Onun bağında alma, nar, şaftalı və s. ağacları var.",
            },
            {
                "fa": "فرهاد و همسرش روزهای جمعه گاهی به روستا می‌روند و گاهی برای دیدن خانواده‌ی مریم به نیشابور می‌روند.",
                "reading_az": "Fərhad va həmsərəş ruzhaye come gahi be rusta mirəvənd va gahi bəraye didəne xanevade-ye Məryəm be Nişabur mirəvənd.",
                "az": "Fərhad və həyat yoldaşı cümə günləri bəzən kəndə gedir, bəzən də Məryəmin ailəsini görmək üçün Nişapura gedirlər.",
                "new_paragraph": True,
            },
        ],
        "comprehension_questions": [
            {
                "question_fa": "فرهاد چه‌کاره است؟",
                "reading_az": "Fərhad çekare əst?",
                "az": "Fərhad nəçidir?",
                "sample_answer_fa": "فرهاد کارمند دانش‌گاه مشهد است.",
                "sample_answer_reading_az": "Fərhad karmənde daneşgahe Məşhəd əst.",
                "sample_answer_az": "Fərhad Məşhəd Universitetinin işçisidir.",
            },
            {
                "question_fa": "مریم کارمند کدام اداره است؟",
                "reading_az": "Məryəm karmənde kodam edare əst?",
                "az": "Məryəm hansı idarənin işçisidir?",
                "sample_answer_fa": "مریم کارمند اداره‌ی پست است.",
                "sample_answer_reading_az": "Məryəm karmənde edareye post əst.",
                "sample_answer_az": "Məryəm poçt idarəsinin işçisidir.",
            },
            {
                "question_fa": "مریم و فرهاد کجا ناهار می‌خورند؟",
                "reading_az": "Məryəm va Fərhad koca nahar mixorənd?",
                "az": "Məryəm və Fərhad harada nahar yeyir?",
                "sample_answer_fa": "مریم در خانه ناهار می‌خورد و فرهاد در دانش‌گاه.",
                "sample_answer_reading_az": "Məryəm dər xane nahar mixorəd va Fərhad dər daneşgah.",
                "sample_answer_az": "Məryəm evdə, Fərhad isə universitetdə nahar yeyir.",
            },
            {
                "question_fa": "پدر فرهاد و پدر مریم چه‌کاره‌اند؟",
                "reading_az": "Pedəre Fərhad va pedəre Məryəm çekareand?",
                "az": "Fərhadın atası və Məryəmin atası nəçidir?",
                "sample_answer_fa": "پدر فرهاد باغ‌دار است و پدر مریم مدیر مدرسه است.",
                "sample_answer_reading_az": "Pedəre Fərhad bağdar əst va pedəre Məryəm modire mædrese əst.",
                "sample_answer_az": "Fərhadın atası bağ sahibidir, Məryəmin atası isə məktəb direktorudur.",
            },
            {
                "question_fa": "آیا مریم و همسرش با هم به خانه می‌آیند؟",
                "reading_az": "Aya Məryəm va həmsərəş ba həm be xane miayənd?",
                "az": "Məryəm və həyat yoldaşı evə birlikdə gəlirmi?",
                "sample_answer_fa": "نه، مریم ساعت دو و فرهاد ساعت چهار به خانه می‌آید.",
                "sample_answer_reading_az": "Nə, Məryəm saəte do va Fərhad saəte çahar be xane miayəd.",
                "sample_answer_az": "Xeyr, Məryəm saat ikidə, Fərhad isə saat dörddə evə gəlir.",
            },
            {
                "question_fa": "خانواده‌ی مریم و فرهاد کجا زندگی می‌کنند؟",
                "reading_az": "Xanevade-ye Məryəm va Fərhad koca zendegi mikonənd?",
                "az": "Məryəm və Fərhadın ailələri harada yaşayır?",
                "sample_answer_fa": "پدر مریم در نیشابور و پدر فرهاد در روستا زندگی می‌کند.",
                "sample_answer_reading_az": "Pedəre Məryəm dər Nişabur va pedəre Fərhad dər rusta zendegi mikonəd.",
                "sample_answer_az": "Məryəmin atası Nişapurda, Fərhadın atası isə kənddə yaşayır.",
            },
            {
                "question_fa": "فرهاد و مریم روزهای جمعه به کجا می‌روند؟",
                "reading_az": "Fərhad va Məryəm ruzhaye come be koca mirəvənd?",
                "az": "Fərhad və Məryəm cümə günləri haraya gedir?",
                "sample_answer_fa": "آن‌ها گاهی به روستا و گاهی به نیشابور می‌روند.",
                "sample_answer_reading_az": "Anha gahi be rusta va gahi be Nişabur mirəvənd.",
                "sample_answer_az": "Onlar bəzən kəndə, bəzən də Nişapura gedirlər.",
            },
        ],
    },
}
