"""
Django settings for zaban_derslik_back project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

if os.environ.get('ALLOWED_HOSTS'):
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS').split(',') if h.strip()]
    if DEBUG and '*' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('*')
else:
    ALLOWED_HOSTS = ['*'] if DEBUG else []

# The Lesson admin page nests many inline formsets several levels deep
# (VocabWord, GrammarNote -> ConjugationRow/ExampleSentence/TopicDrill ->
# TopicDrillItem, FillBlank/TrueFalseImage/MultipleChoice/PracticeReveal ->
# Items, PictureSentenceExercise -> Items -> Sentences, etc.) — a content-rich
# lesson easily produces more POST fields than Django's default limit
# (1000), raising TooManyFieldsSent when saving. This is an internal,
# authenticated admin panel (not a public form), so a much higher cap is safe.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'nested_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'lessons',
]

JAZZMIN_SETTINGS = {
    'site_title': 'Zəban Dərslik Admin',
    'site_header': 'Zəban Dərslik',
    'site_brand': 'Zəban Dərslik',
    'welcome_sign': 'Zəban Dərslik idarəetmə panelinə xoş gəlmisiniz',
    'copyright': 'Zəban Dərslik',
    'show_sidebar': True,
    'navigation_expanded': True,
    # "Dərslər" sidebar-da görünmür: dərslərə yalnız bir sinifin öz səhifəsindəki
    # "Dərslər" siyahısından keçilir (hər sinifin öz strukturu var).
    # "Siniflər" ümumi siyahısı da gizlədilib: onun yerinə hər sinif üçün ayrıca
    # keçid var (aşağıdakı custom_links), birbaşa o sinfin redaktə səhifəsinə aparır.
    'hide_models': ['lessons.lesson', 'lessons.grade'],
    'order_with_respect_to': [
        'lessons',
        '1-ci sinif', '2-ci sinif', '3-cü sinif', '4-cü sinif', '5-ci sinif', '6-cı sinif',
    ],
    # URL-lər sinif *nömrəsinə* görədir (PK deyil): /admin/sinif/N/ →
    # lessons.views.grade_admin_redirect uyğun sinfin redaktə səhifəsinə yönləndirir.
    'custom_links': {
        'lessons': [
            {'name': '1-ci sinif', 'url': '/admin/sinif/1/', 'icon': 'fas fa-graduation-cap'},
            {'name': '2-ci sinif', 'url': '/admin/sinif/2/', 'icon': 'fas fa-graduation-cap'},
            {'name': '3-cü sinif', 'url': '/admin/sinif/3/', 'icon': 'fas fa-graduation-cap'},
            {'name': '4-cü sinif', 'url': '/admin/sinif/4/', 'icon': 'fas fa-graduation-cap'},
            {'name': '5-ci sinif', 'url': '/admin/sinif/5/', 'icon': 'fas fa-graduation-cap'},
            {'name': '6-cı sinif', 'url': '/admin/sinif/6/', 'icon': 'fas fa-graduation-cap'},
        ],
    },
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'default',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zaban_derslik_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zaban_derslik_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Prevent TooManyFieldsSent error in django admin when editing large lessons/grades
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

