# Generated by Django 6.0.6 on 2026-07-16 15:33

import django.db.models.deletion
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillBlankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_az', models.TextField(verbose_name='Tapşırıq (az)')),
                ('word_bank', models.JSONField(blank=True, default=list, verbose_name='Söz bankı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Boşluq doldurma məşğələsi',
                'verbose_name_plural': 'Boşluq doldurma məşğələləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrammarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=255, verbose_name='Başlıq (az)')),
                ('title_fa', models.CharField(max_length=255, verbose_name='Başlıq (fars)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Qrammatika qeydi',
                'verbose_name_plural': 'Qrammatika qeydləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='Başlıq (fars)')),
                ('title_az', models.CharField(max_length=255, verbose_name='Başlıq (az)')),
                ('available', models.BooleanField(default=False, verbose_name='Aktivdir')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Dərs',
                'verbose_name_plural': 'Dərslər',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='FillBlankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_with_blank', models.CharField(max_length=500, verbose_name='Cümlə (boşluqlu)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Düzgün cavab')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lessons.fillblankexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.CharField(max_length=500, verbose_name='Fars')),
                ('az', models.CharField(max_length=500, verbose_name='Azərbaycan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('grammar_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='lessons.grammarnote')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConjugationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun_fa', models.CharField(max_length=100, verbose_name='Əvəzlik (fars)')),
                ('form_fa', models.CharField(max_length=255, verbose_name='Fel forması (fars)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('grammar_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjugations', to='lessons.grammarnote')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_notes', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='fillblankexercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_exercises', to='lessons.lesson'),
        ),
        migrations.CreateModel(
            name='MultipleChoiceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_az', models.TextField(verbose_name='Tapşırıq (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_exercises', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Çoxseçimli məşğələ',
                'verbose_name_plural': 'Çoxseçimli məşğələlər',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fa', models.CharField(max_length=500, verbose_name='Sual (fars)')),
                ('options', models.JSONField(default=list, verbose_name='Variantlar')),
                ('correct_index', models.PositiveIntegerField(default=0, verbose_name='Düzgün variantın indeksi (0-dan başlar)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lessons.multiplechoiceexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeRevealExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_az', models.TextField(verbose_name='Tapşırıq (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_reveal_exercises', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Praktika (özünüyoxlama) məşğələsi',
                'verbose_name_plural': 'Praktika (özünüyoxlama) məşğələləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeRevealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_fa', models.CharField(max_length=500, verbose_name='Sual/tapşırıq (fars)')),
                ('answer_fa', models.CharField(max_length=500, verbose_name='Nümunə cavab (fars)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lessons.practicerevealexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='Başlıq (fars)')),
                ('title_az', models.CharField(max_length=255, verbose_name='Başlıq (az)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil')),
                ('paragraphs_fa', models.JSONField(default=list, verbose_name='Paraqraflar (fars)')),
                ('full_translation_az', models.TextField(verbose_name='Tam tərcümə (az)')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_text', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Oxu mətni',
                'verbose_name_plural': 'Oxu mətnləri',
            },
        ),
        migrations.CreateModel(
            name='ReadingFootnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.CharField(max_length=500, verbose_name='Fars')),
                ('az', models.CharField(max_length=500, verbose_name='Azərbaycan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('reading_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='lessons.readingtext')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrueFalseImageExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_az', models.TextField(verbose_name='Tapşırıq (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_exercises', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Doğru/Yanlış (şəkilli) məşğələsi',
                'verbose_name_plural': 'Doğru/Yanlış (şəkilli) məşğələləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrueFalseImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil')),
                ('statement_fa', models.CharField(max_length=500, verbose_name='Cümlə (fars)')),
                ('statement_az', models.CharField(max_length=500, verbose_name='Cümlə (az)')),
                ('is_true', models.BooleanField(default=True, verbose_name='Doğrudur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lessons.truefalseimageexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VocabWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.CharField(max_length=255, verbose_name='Fars')),
                ('az', models.CharField(max_length=255, verbose_name='Azərbaycan')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Söz',
                'verbose_name_plural': 'Lüğət',
                'ordering': ['order', 'id'],
            },
        ),
    ]
