# Generated by Django 6.0.7 on 2026-07-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_grade_vocab_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentencePractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_practice', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Sözlərin işləndiyi cümlələr',
                'verbose_name_plural': 'Sözlərin işləndiyi cümlələr',
            },
        ),
        migrations.CreateModel(
            name='ListenReadSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.CharField(max_length=500, verbose_name='Cümlə (fars)')),
                ('az', models.CharField(max_length=500, verbose_name='Tərcümə (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_items', to='lessons.sentencepractice')),
            ],
            options={
                'verbose_name': 'Dinlə və oxu cümləsi',
                'verbose_name_plural': 'Dinlə və oxu cümlələri (گوش کنید و بخوانید)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestionSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.CharField(max_length=500, verbose_name='Sual (fars)')),
                ('az', models.CharField(max_length=500, verbose_name='Tərcümə (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_items', to='lessons.sentencepractice')),
            ],
            options={
                'verbose_name': 'Cavab veriləcək sual',
                'verbose_name_plural': 'Cavab veriləcək suallar (لطفاً پاسخ دهید)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
