# Generated by Django 6.0.7 on 2026-07-20 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_sentencepractice_listenreadsentence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infinitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.CharField(max_length=255, verbose_name='Məsdər (fars)')),
                ('reading_az', models.CharField(blank=True, default='', max_length=255, verbose_name='Oxunuşu (az hərfləri ilə)')),
                ('az', models.CharField(max_length=255, verbose_name='Tərcümə (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infinitives', to='lessons.sentencepractice')),
            ],
            options={
                'verbose_name': 'Məsdər',
                'verbose_name_plural': 'Məsdərlər',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConjugatedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('men', 'Mən'), ('sen', 'Sən'), ('o', 'O'), ('biz', 'Biz'), ('siz', 'Siz'), ('onlar', 'Onlar')], max_length=10, verbose_name='Şəxs')),
                ('fa', models.CharField(max_length=255, verbose_name='Fel forması (fars)')),
                ('reading_az', models.CharField(blank=True, default='', max_length=255, verbose_name='Oxunuşu (az hərfləri ilə)')),
                ('az', models.CharField(max_length=255, verbose_name='Tərcümə (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('infinitive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='lessons.infinitive')),
            ],
            options={
                'verbose_name': 'Hallanmış forma',
                'verbose_name_plural': 'Hallanmış formalar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
