# Generated by Django 6.0.7 on 2026-07-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_infinitive_conjugatedform'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplesentence',
            name='reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Üzündən oxunuş (az)'),
        ),
    ]
