# Generated by Django 6.0.7 on 2026-07-20 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_examplesentence_reading_az'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerevealexercise',
            name='grammar_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='lessons.grammarnote'),
        ),
        migrations.AddField(
            model_name='practicerevealexercise',
            name='title_fa',
            field=models.CharField(blank=True, default='', help_text='Yalnız mövzu kartı kimi göstərildikdə istifadə olunur (məs. «مانند مثال جایگزین کنید»).', max_length=255, verbose_name='Başlıq (fars)'),
        ),
        migrations.AddField(
            model_name='practicerevealitem',
            name='az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Cavabın tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='practicerevealitem',
            name='reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Cavabın oxunuşu (az)'),
        ),
        migrations.AlterField(
            model_name='practicerevealexercise',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_reveal_exercises', to='lessons.lesson'),
        ),
    ]
