# Generated by Django 6.0.7 on 2026-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_practicerevealexercise_grammar_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestionsentence',
            name='sample_answer_fa',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavab (fars)'),
        ),
        migrations.AddField(
            model_name='listenreadsentence',
            name='reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Oxunuşu (az hərfləri ilə)'),
        ),
    ]
