# Generated by Django 6.0.7 on 2026-07-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_answerquestionsentence_sample_answer_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestionsentence',
            name='reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Sualın oxunuşu (az hərfləri ilə)'),
        ),
        migrations.AddField(
            model_name='answerquestionsentence',
            name='sample_answer_reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavabın oxunuşu (az hərfləri ilə)'),
        ),
    ]
