# Generated by Django 6.0.7 on 2026-07-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_answerquestionsentence_reading_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerevealexercise',
            name='example_answer_fa',
            field=models.CharField(blank=True, default='', help_text='example_prompt_fa əsasında qurulan nümunə cümlə, eyni *ulduz* qaydası ilə.', max_length=500, verbose_name='Nümunənin işlənmiş cavabı (fars)'),
        ),
        migrations.AddField(
            model_name='practicerevealexercise',
            name='example_fa',
            field=models.CharField(blank=True, default='', help_text='Dərslikdəki nümunə qutusunun baza cümləsi. Vurğulanacaq fel(lər)i *ulduz* içinə al (məs. «...سبز *نیست*؛ قرمز *است*.»).', max_length=500, verbose_name='Nümunə cümlə (fars)'),
        ),
        migrations.AddField(
            model_name='practicerevealexercise',
            name='example_prompt_fa',
            field=models.CharField(blank=True, default='', help_text='Məs. «ماژیک / سیاه\u200cآبی».', max_length=255, verbose_name='Nümunənin söz dəsti (fars)'),
        ),
    ]
