# Generated by Django 6.0.7 on 2026-07-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_practicerevealexercise_example_answer_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestionsentence',
            name='sample_answer_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavabın tərcüməsi (az)'),
        ),
    ]
