# Generated by Django 6.0.7 on 2026-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_answerquestionsentence_sample_answer_az'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillblankitem',
            name='az',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cavabın tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='fillblankitem',
            name='reading_az',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cavabın oxunuşu (az hərfləri ilə)'),
        ),
    ]
