# Generated by Django 6.0.6 on 2026-07-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_fillblankitem_az_fillblankitem_reading_az'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillblankitem',
            name='full_translation_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Cümlənin ümumi tərcüməsi (az)'),
        ),
    ]
