# Generated by Django 6.0.6 on 2026-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_fillblankitem_full_translation_az'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillblankitem',
            name='full_reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Cümlənin oxunuşu (az hərfləri ilə)'),
        ),
    ]
