# Generated by Django 6.0.6 on 2026-07-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_fillblankitem_full_reading_az'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtext',
            name='sentences',
            field=models.JSONField(blank=True, default=list, help_text='Hər biri {"fa", "reading_az", "az", "new_paragraph"} formasında. Boşdursa köhnə paraqraf görünüşü işlədilir.', verbose_name='Cümlələr (toxunanda oxunuş+tərcümə görünür)'),
        ),
    ]
