# Generated by Django 6.0.6 on 2026-07-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_readingtext_sentences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingComprehensionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fa', models.CharField(max_length=500, verbose_name='Sual (fars)')),
                ('reading_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Sualın oxunuşu (az hərfləri ilə)')),
                ('az', models.CharField(blank=True, default='', max_length=500, verbose_name='Sualın tərcüməsi (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('reading_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_questions', to='lessons.readingtext')),
            ],
            options={
                'verbose_name': 'Anlama sualı',
                'verbose_name_plural': 'Anlama sualları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
