# Generated by Django 6.0.6 on 2026-07-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_readingcomprehensionquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingcomprehensionquestion',
            name='sample_answer_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavabın tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='readingcomprehensionquestion',
            name='sample_answer_fa',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavab (fars)'),
        ),
        migrations.AddField(
            model_name='readingcomprehensionquestion',
            name='sample_answer_reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavabın oxunuşu (az hərfləri ilə)'),
        ),
    ]
