# Generated by Django 6.0.7 on 2026-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_readingcomprehensionquestion_sample_answer_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerevealexercise',
            name='example_az',
            field=models.CharField(blank=True, default='', help_text='example_fa (və varsa example_answer_fa) üçün tərcümə.', max_length=500, verbose_name='Nümunənin tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='practicerevealexercise',
            name='example_reading_az',
            field=models.CharField(blank=True, default='', help_text='example_fa (və varsa example_answer_fa) üçün üzündən oxunuş.', max_length=500, verbose_name='Nümunənin oxunuşu (az)'),
        ),
    ]
