# Generated by Django 6.0.7 on 2026-07-24 12:50

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_practicerevealexercise_example_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerevealexercise',
            name='example_image_have',
            field=models.ImageField(blank=True, help_text='Şəkillə göstərilən «has/dارم» tərəfi üçün nümunə şəkli (məs. تصویری بازی/بگویید məşğələləri).', null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Nümunə şəkli («var» tərəfi)'),
        ),
        migrations.AddField(
            model_name='practicerevealexercise',
            name='example_image_not_have',
            field=models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Nümunə şəkli («yoxdur» tərəfi)'),
        ),
        migrations.AddField(
            model_name='practicerevealitem',
            name='image_have',
            field=models.ImageField(blank=True, help_text='Bu sətrin sahib olduğu əşya/xüsusiyyətin şəkli (məs. «دارم» tərəfi).', null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil («var» tərəfi)'),
        ),
        migrations.AddField(
            model_name='practicerevealitem',
            name='image_not_have',
            field=models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil («yoxdur» tərəfi)'),
        ),
    ]
