# Generated by Django 6.0.7 on 2026-07-24 13:41

import django.db.models.deletion
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_practicerevealexercise_example_image_have_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureSentenceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_az', models.TextField(verbose_name='Tapşırıq (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_sentence_exercises', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Şəkilli cümlə məşğələsi',
                'verbose_name_plural': 'Şəkilli cümlə məşğələləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PictureSentenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lessons.picturesentenceexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PictureSentenceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.CharField(max_length=500, verbose_name='Cümlə (fars)')),
                ('reading_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Oxunuşu (az)')),
                ('az', models.CharField(blank=True, default='', max_length=500, verbose_name='Tərcümə (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='lessons.picturesentenceitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
