# Generated by Django 6.0.7 on 2026-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_picturesentenceexercise_picturesentenceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarnote',
            name='note_az',
            field=models.TextField(blank=True, default='', verbose_name='Qeydin tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='note_fa',
            field=models.TextField(blank=True, default='', help_text="Nümunə cümlələrdən sonra göstərilən ayrıca 'Qeyd' kartı — bütün mətn tək blok kimi.", verbose_name='Qeyd (fars, ardıcıl mətn)'),
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='note_reading_az',
            field=models.TextField(blank=True, default='', verbose_name='Qeydin oxunuşu (az hərfləri ilə)'),
        ),
    ]
