# Generated by Django 6.0.7 on 2026-07-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_grammarnote_note_az_grammarnote_note_fa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(blank=True, default='', max_length=255, verbose_name='Başlıq (fars)')),
                ('instruction_az', models.TextField(verbose_name='Tapşırıq (az)')),
                ('note_fa', models.TextField(blank=True, default='', verbose_name='Qeyd (fars, ardıcıl mətn)')),
                ('note_reading_az', models.TextField(blank=True, default='', verbose_name='Qeydin oxunuşu (az hərfləri ilə)')),
                ('note_az', models.TextField(blank=True, default='', verbose_name='Qeydin tərcüməsi (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question_exercises', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Sual-cavab məşğələsi',
                'verbose_name_plural': 'Sual-cavab məşğələləri (لطفاً پاسخ دهید)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestionExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa', models.CharField(max_length=500, verbose_name='Sual (fars)')),
                ('reading_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Sualın oxunuşu (az hərfləri ilə)')),
                ('az', models.CharField(blank=True, default='', max_length=500, verbose_name='Sualın tərcüməsi (az)')),
                ('sample_answer_fa', models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavab (fars)')),
                ('sample_answer_reading_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavabın oxunuşu (az hərfləri ilə)')),
                ('sample_answer_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavabın tərcüməsi (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lessons.answerquestionexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
