# Generated by Django 6.0.7 on 2026-07-26 10:39

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_answerquestionexercise_answerquestionexerciseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunənin tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_fa',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cümlə (fars)'),
        ),
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_image_have',
            field=models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Nümunə şəkli («düz cavab» tərəfi)'),
        ),
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_image_not_have',
            field=models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Nümunə şəkli («səhv/həzf olunan» tərəfi)'),
        ),
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunənin oxunuşu (az)'),
        ),
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='title_fa',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Başlıq (fars)'),
        ),
        migrations.AddField(
            model_name='picturesentenceitem',
            name='image_have',
            field=models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil (düz cavab tərəfi)'),
        ),
        migrations.AddField(
            model_name='picturesentenceitem',
            name='image_not_have',
            field=models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil (səhv/həzf olunan tərəf)'),
        ),
        migrations.AlterField(
            model_name='picturesentenceitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Tək şəkilli element üçün. Cüt şəkilli («bu, yoxsa o?») elementlər üçün bunun əvəzinə aşağıdakı iki sahəni doldurun.', null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Şəkil'),
        ),
    ]
