# Generated by Django 6.0.7 on 2026-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_picturesentenceexercise_example_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_answer_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavabın tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_answer_fa',
            field=models.CharField(blank=True, default='', help_text='Sualın düz cavabı (məs. «مریم غذا می\u200cپزد.»).', max_length=500, verbose_name='Nümunə cavab (fars)'),
        ),
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_answer_reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cavabın oxunuşu (az)'),
        ),
        migrations.AlterField(
            model_name='picturesentenceexercise',
            name='example_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə sualın tərcüməsi (az)'),
        ),
        migrations.AlterField(
            model_name='picturesentenceexercise',
            name='example_fa',
            field=models.CharField(blank=True, default='', help_text='«یا» sualı olan nümunə cümlə (məs. «مریم ظرف می\u200cشوید یا غذا می\u200cپزد؟»).', max_length=500, verbose_name='Nümunə sual (fars)'),
        ),
        migrations.AlterField(
            model_name='picturesentenceexercise',
            name='example_reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə sualın oxunuşu (az)'),
        ),
    ]
