# Generated by Django 6.0.7 on 2026-07-26 11:38

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0023_picturesentenceexercise_example_answer_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='example_image',
            field=models.ImageField(blank=True, help_text='Tək şəkilli nümunə üçün. Cüt şəkilli («bu, yoxsa o?») nümunə üçün bunun əvəzinə aşağıdakı iki sahəni doldurun.', null=True, upload_to=lessons.models.lesson_image_path, verbose_name='Nümunə şəkli (tək)'),
        ),
    ]
