# Generated by Django 6.0.7 on 2026-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_picturesentenceexercise_example_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencepractice',
            name='answer_note_az',
            field=models.TextField(blank=True, default='', verbose_name='Qeydin tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='sentencepractice',
            name='answer_note_fa',
            field=models.TextField(blank=True, default='', help_text="'Suallara cavab verin' siyahısının sonunda göstərilən 'Qeyd' kartı.", verbose_name='Sualların qeydi (fars)'),
        ),
        migrations.AddField(
            model_name='sentencepractice',
            name='answer_note_reading_az',
            field=models.TextField(blank=True, default='', verbose_name='Qeydin oxunuşu (az hərfləri ilə)'),
        ),
    ]
