# Generated by Django 6.0.7 on 2026-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_sentencepractice_answer_note_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestionexercise',
            name='example_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cümlənin tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='answerquestionexercise',
            name='example_fa',
            field=models.CharField(blank=True, default='', help_text='Çalışmanın başında göstərilən «نمونه» qutusu üçün nümunə cümlə (məs. «خانه\u200cی ما ... *دارد*.»).', max_length=500, verbose_name='Nümunə cümlə (fars)'),
        ),
        migrations.AddField(
            model_name='answerquestionexercise',
            name='example_reading_az',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunə cümlənin oxunuşu (az)'),
        ),
    ]
