# Generated by Django 6.0.7 on 2026-07-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0026_answerquestionexercise_example_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceitem',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='truefalseimageexercise',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='truefalseimageitem',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceExercise',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceItem',
        ),
        migrations.DeleteModel(
            name='TrueFalseImageExercise',
        ),
        migrations.DeleteModel(
            name='TrueFalseImageItem',
        ),
    ]
