# Generated by Django 6.0.7 on 2026-07-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_remove_multiplechoiceitem_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabword',
            name='edited_via_app',
            field=models.BooleanField(default=False, help_text='Bu söz mobil tətbiqdəki redaktə ekranından dəyişdirilib/əlavə edilib — seed_lessons yenidən işlədikdə bu sözün fa/az/oxunuş/şəkli fayldakı məzmunla əvəz olunmur.', verbose_name='Tətbiqdən redaktə olunub'),
        ),
    ]
