# Generated by Django 6.0.7 on 2026-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_vocabword_edited_via_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestionsentence',
            name='edited_via_app',
            field=models.BooleanField(default=False, help_text='Sual mobil tətbiqdən dəyişdirilib/əlavə edilib — seed_lessons yenidən işlədikdə üstələnmir.', verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='conjugationrow',
            name='edited_via_app',
            field=models.BooleanField(default=False, help_text='Sətir mobil tətbiqdən dəyişdirilib/əlavə edilib — seed_lessons yenidən işlədikdə üstələnmir.', verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='examplesentence',
            name='edited_via_app',
            field=models.BooleanField(default=False, help_text='Cümlə mobil tətbiqdən dəyişdirilib/əlavə edilib — seed_lessons yenidən işlədikdə üstələnmir.', verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='edited_via_app',
            field=models.BooleanField(default=False, help_text='Qeyd mobil tətbiqdən dəyişdirilib — seed_lessons yenidən işlədikdə üstələnmir.', verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='listenreadsentence',
            name='edited_via_app',
            field=models.BooleanField(default=False, help_text='Cümlə mobil tətbiqdən dəyişdirilib/əlavə edilib — seed_lessons yenidən işlədikdə üstələnmir.', verbose_name='Tətbiqdən redaktə olunub'),
        ),
    ]
