# Generated by Django 6.0.7 on 2026-07-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0029_answerquestionsentence_edited_via_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestionexercise',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='answerquestionexerciseitem',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='fillblankexercise',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='fillblankitem',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='picturesentenceexercise',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='picturesentenceitem',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='practicerevealexercise',
            name='edited_via_app',
            field=models.BooleanField(default=False, help_text='Yalnız Çalışmalar siyahısındakı (lesson-a bağlı) məşğələlər üçün mənalıdır — Qrammatika mövzusunun öz drill kartları (grammar_note-a bağlı) tətbiqdən redaktə olunmur.', verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='practicerevealitem',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='readingcomprehensionquestion',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='readingfootnote',
            name='edited_via_app',
            field=models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='readingtext',
            name='edited_via_app',
            field=models.BooleanField(default=False, help_text='title_fa/title_az/full_translation_az/paragraphs_fa/sentences tətbiqdən dəyişdirilib — seed_lessons yenidən işlədikdə üstələnmir (şəkil ayrıca qorunur, bax _attach_image).', verbose_name='Tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='sentencepractice',
            name='answer_note_edited_via_app',
            field=models.BooleanField(default=False, help_text='answer_note_* sahələri tətbiqdən dəyişdirilib — seed_lessons yenidən işlədikdə üstələnmir.', verbose_name='Qeyd tətbiqdən redaktə olunub'),
        ),
    ]
