# Generated by Django 6.0.7 on 2026-07-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0031_listenreadexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenreadexercise',
            name='note_az',
            field=models.TextField(blank=True, default='', verbose_name='Qeydin tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='listenreadexercise',
            name='note_edited_via_app',
            field=models.BooleanField(default=False, help_text='note_* sahələri tətbiqdən dəyişdirilib — seed_lessons yenidən işlədikdə üstələnmir.', verbose_name='Qeyd tətbiqdən redaktə olunub'),
        ),
        migrations.AddField(
            model_name='listenreadexercise',
            name='note_fa',
            field=models.TextField(blank=True, default='', help_text='Çalışmanın sonunda göstərilən nömrələnmiş izah (məs. sözlərin sinonimləri).', verbose_name='Qeyd (fars)'),
        ),
        migrations.AddField(
            model_name='listenreadexercise',
            name='note_reading_az',
            field=models.TextField(blank=True, default='', verbose_name='Qeydin oxunuşu (az hərfləri ilə)'),
        ),
    ]
