# Generated by Django 6.0.7 on 2026-07-29 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0032_listenreadexercise_note_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiBlankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(blank=True, default='', max_length=255, verbose_name='Başlıq (fars)')),
                ('instruction_az', models.TextField(verbose_name='Tapşırıq (az)')),
                ('word_bank', models.JSONField(blank=True, default=list, verbose_name='Söz bankı')),
                ('example_fa', models.CharField(blank=True, default='', help_text='Vurğulanacaq sözlər `*ulduz*` (yaşıl) / `**iki ulduz**` (qırmızı) içinə alına bilər.', max_length=500, verbose_name='Nümunə cümlə (fars)')),
                ('example_reading_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunənin oxunuşu (az)')),
                ('example_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Nümunənin tərcüməsi (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('edited_via_app', models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_blank_exercises', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Çoxboşluqlu doldurma məşğələsi',
                'verbose_name_plural': 'Çoxboşluqlu doldurma məşğələləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MultiBlankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_with_blanks', models.CharField(help_text='Hər boşluq üçün `___` yazın, məs. «مریم معلّم ___؛ مدیر ___ .»', max_length=500, verbose_name='Cümlə (boşluqlu)')),
                ('correct_answers', models.JSONField(default=list, help_text='Boşluqların sırası ilə eyni ardıcıllıqda siyahı, məs. ["است", "نیست"].', verbose_name='Düzgün cavablar')),
                ('full_reading_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Cümlənin oxunuşu (az)')),
                ('full_translation_az', models.CharField(blank=True, default='', max_length=500, verbose_name='Cümlənin tərcüməsi (az)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('edited_via_app', models.BooleanField(default=False, verbose_name='Tətbiqdən redaktə olunub')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lessons.multiblankexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
