# Generated by Django 6.0.7 on 2026-07-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0033_multiblankexercise_multiblankitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarnote',
            name='explanation_az',
            field=models.TextField(blank=True, default='', help_text='«Qaydalar / Birləşmələr» cədvəlinin altında göstərilən izah qutusu — qaydanın qısa və aydın Azərbaycan dilində şərhi. Sətirlər \\n ilə ayrılır.', verbose_name='Qaydanın izahı (az)'),
        ),
    ]
