# Generated by Django 6.0.7 on 2026-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0034_grammarnote_explanation_az'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarnote',
            name='explanation_edited_via_app',
            field=models.BooleanField(default=False, help_text="İzah qutusu mobil tətbiqdən dəyişdirilib — seed_lessons yenidən işlədikdə üstələnmir. 'Qeyd' kartının öz bayrağından (edited_via_app) ayrıdır.", verbose_name='İzah tətbiqdən redaktə olunub'),
        ),
    ]
