# Generated by Django 6.0.7 on 2026-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0035_grammarnote_explanation_edited_via_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjugationrow',
            name='az',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tərcümə (az)'),
        ),
        migrations.AddField(
            model_name='conjugationrow',
            name='full_fa',
            field=models.CharField(blank=True, default='', help_text='«هستم» ilə tam cümlə, məs. «من استاد هستم.»', max_length=255, verbose_name='Tam forma (fars)'),
        ),
        migrations.AddField(
            model_name='conjugationrow',
            name='reading_az',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Üzündən oxunuş (az)'),
        ),
        migrations.AddField(
            model_name='conjugationrow',
            name='short_fa',
            field=models.CharField(blank=True, default='', help_text='Şəkilçili qısa cümlə, məs. «من استادم.»', max_length=255, verbose_name='Qısa forma (fars)'),
        ),
        migrations.AddField(
            model_name='conjugationrow',
            name='suffix_fa',
            field=models.CharField(blank=True, default='', help_text='Həmin şəxsin şəkilçisi, məs. «ـَم».', max_length=60, verbose_name='Şəkilçi (fars)'),
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='pattern_caption_az',
            field=models.CharField(blank=True, default='', help_text='Cədvəlin başlığının altında göstərilən bir sətirlik izah.', max_length=300, verbose_name='Cədvəlin altyazısı (az)'),
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='pattern_word_az',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nümunə sözün tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='pattern_word_fa',
            field=models.CharField(blank=True, default='', help_text='Cədvəlin başındakı nümunə söz, məs. «استاد». Boş olduqda struktur cədvəl göstərilmir.', max_length=100, verbose_name='Nümunə söz (fars)'),
        ),
    ]
