# Generated by Django 6.0.7 on 2026-07-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0036_conjugationrow_az_conjugationrow_full_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarnote',
            name='note2_az',
            field=models.TextField(blank=True, default='', verbose_name='2-ci qutunun tərcüməsi (az)'),
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='note2_fa',
            field=models.TextField(blank=True, default='', help_text="Doldurulanda eyni 'Qeyd' kartının içində birincidən sonra ayrıca qutu kimi göstərilir.", verbose_name='Qeyd — 2-ci qutu (fars)'),
        ),
        migrations.AddField(
            model_name='grammarnote',
            name='note2_reading_az',
            field=models.TextField(blank=True, default='', verbose_name='2-ci qutunun oxunuşu (az hərfləri ilə)'),
        ),
    ]
